### ISSUE TITLE
Get emacswiki files from the git repo

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#2128]
EmacsWiki is [backed by git](http://www.emacswiki.org/emacs/Git_repository), so rather than scraping EmacsWiki.org, we could just grab `:fetcher wiki` files from there.

https://github.com/emacsmirror/emacswiki.org

**Comment by tarsius** [comment]
So I have had a look at the differences. Looks like it might be a while until you can switch to use my repos. Here are the findings:

* Melpa has 27 wiki packages missing from the Emacsmirror.
* Melpa mirrors 27 wiki packages, which the Emacsmirror gets from elsewhere.
* Emacsmirror has 22 wiki packages, which Melpa gets from elsewhere.

In most cases "elsewhere" is probably preferable over the wiki. Here's the list of packages you might want to check first:

```
(("cal-china-x" "git@github.com:xwl/cal-china-x.git")
 ("dummy-h-mode" "git@github.com:yascentur/dummy-h-mode-el.git")
 ("eimp" "git@github.com:nicferrier/eimp.git")
 ("elisp-depend" "git@github.com:tehom/elisp-depend.git")
 ("fic-mode" "git@github.com:lewang/fic-mode.git")
 ("iy-go-to-char" "git@github.com:doitian/iy-go-to-char.git")
 ("legalese" "git@github.com:jorgenschaefer/legalese.git")
 ("pastebin" "git@github.com:nicferrier/elpastebin.git")
 ("scpaste" "git@github.com:technomancy/scpaste.git")
 ("unbound" "git@github.com:haxney/unbound.git")
 ("wc-mode" "git@github.com:bnbeckwith/wc-mode.git"))
```

**Comment by tarsius** [comment]
I went through the list of packages which Melpa mirrors from the
Emacswiki and which are completely missing from the Emacsmirror.

I have reservations about most of these libraries.  When I first
created the Emacsmirror I quickly reviewed every elisp file to be
found on the Emacswiki.  Obviously I could not spend a lot of time
on each and every library, so it is quite possible that I failed to
import some libraries which are perfectly fine.  This time again I
have reviewed the libraries quickly, take the criticism with a grain
of salt, and try not to be offended - maintaining something like
Melpa and Emacsmirror, and what might seem like nit-picking to
outsiders is essential for such collections to be of any value.

# Good change of being added

## to recent

Generally I think we should start refusing to add any packages which
are created now and only distributed on the Emacswiki (to either the
Emacsmirror or Melpa).  But since you already package these, I am
willing to include them too.

* [ ] [awk-it](.el) 2013-09
* [ ] [delight](.el) 2013-06

Drew (a) advertises his libraries offensively and (b) trying to
boycott him into using version control is futile.  If we refuse to add
his newer creations we would have to explain this to many dissatisfied
users, so I am okay with adding his stuff.

* [ ] [cmds-menu](.el) should be named `recent-cmds`
* [ ] [hl-defined](.el) 
* [ ] [isearch-prop](.el) 
* [ ] [narrow-indirect](.el) 
* [ ] [reveal-next](.el) 
* [ ] [subr+](.el)

## other

* [ ] [bs-ext](.el) author uses git now, why not here?
* [ ] [hippie-exp-ext](.el) upstream should make his git repo available; I am suspicious of extension extensions
* [ ] [swbuff-x](.el) I am suspicious of extension extensions, why not contribute upstream?

# Dire prospects

* [ ] [all-ext](.el) odd missing whitespace
* [ ] [apt-utils](.el) file corrupted on wiki
* [ ] [ascope](.el) odd header, indentation, and closing-parens
* [ ] [ddg](.el) odd headings and closing-parens
* [ ] [ert-expectations](.el) upstream should make his git repo available
* [ ] [font-lock-menus](.el) also provides `font-menus`
* [ ] [gnus-spotlight](.el) Mac OS X Tiger is obsolete
* [ ] [kill-ring-ido](.el) odd indentation
* [ ] [python-magic](.el) is personal configuration
* [ ] [replace-from-region](.el) no prefix
* [ ] [save-load-path](.el) upstream should make his git repo available
* [ ] [setup-cygwin](.el) is personal configuration
* [ ] [smart-operator](.el) should use a minor mode map
* [ ] [sticky-windows](.el) is personal configuration
* [ ] [todochiku](.el) also provides `growl`

**Comment by milkypostman** [comment]
I will take some time and parse all of this over the weekend. So please
excuse my slow response.

**Comment by tarsius** [comment]
I didn't expect this to be taken care of overnight, or over the weekend... :-)

Make sure you view this on Github, urls have been fixed and such.

**Comment by milkypostman** [comment]
so, one thing to consider is that previously we had made an arrangement with drew that all his packages on the wiki would be "locked" and only editable by him. I don't know if this has changed with the recent outage. with that said, I think it would be a good idea to use emacsmirror for his packages.

I am happy with all of your choices here. I didn't personally review them so I trust your considerations.

@purcell after re-skimming this long thread, my current inclination is to either change some of these recipes to `github` fetcher and pull from `emacsmirror/____` or to create a separate `emacsmirror` fetcher. I would still like to have a way to filter these packages as in some cases I don't want to run elisp from emacswiki even if it is through the mirror. 

@tarsius @purcell if we do decide to move some emacswiki packages over should we do this enmasse to all your individual repos or should we just do it on a case-by-case basis?

I am going to file a separate bug that we deprecate emacswiki packages.

**Comment by tarsius** [comment]
There already is an `emacsmirror` fetcher, it's used for packages which I import from non-emacswiki upstreams which use no vcs. For fetching from the Emacswiki, Melpa currently uses `wiki`. You could add an additional `emacswiki` fetcher which gets Emacswiki packages through the Emacsmirror, and migrate those packages to that which actually do exist on the Emacsmirror. But keep using `wiki` for the packages listed above, at least initially.

**Comment by tarsius** [comment]
There were some packages that the Emacsmirror got from the Emacswiki, but which Melpa got from an upstream repository. The Emacsmirror now also uses these repositories, except in the following cases where that is not possible, because it can only mirror complete repositories.

* dired-open, part of https://github.com/Fuco1/dired-hacks which contains various dired extensions.
* autotest and toggle from https://github.com/zenspider/elisp which contains all kinds of things
* toggle from https://github.com/pjones/elisp which contains all kinds of things

@zenspider and @pjones could you please consider only putting related libraries into a repository. You are probably using a workflow which makes it convenient to have everything in one repository, but this makes it harder for other people.

**Comment by Fuco1** [comment]
The dired-open.el file on the wiki doesn't even exist... plus I consider emacswiki the worst possible way to distribute code.  So no, I won't rename. If the possibly anonymous author of the non-existing file on the wiki cares, they can rename their library, which, in all likelyhood, is a subset of what mine does anyway.

**Comment by tarsius** [comment]
> The dired-open.el file on the wiki doesn't even exist...

It does exist.

> plus I consider emacswiki the worst possible way to distribute code.

Everyone here pretty much agrees on that :-) I also just had a look at `dired-open.el` and it indeed seems rather useless in comparison to yours. @milkypostman I recommend you remove it from Melpa and instead add `dired-utils`. Which leads to the next problem:

Melpa would have to distribute each library as a separate package, or consider one of the libraries the "main" library. On the Emacsmirror I currently consider `dired-hacks-utils.el` the main library, with the result that the package description is "Utilities and helpers for dired-hacks collection".

Please consider adding `dired-hacks.el` which just loads the other libraries and contains a Commentary section which provides an overview over the included libraries, much like the Readme does.

**Comment by tarsius** [comment]
It goes a bit against the trend but I am now mirroring those eight wiki packages which I said I would.

**Comment by pjones** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> @zenspider and @pjones could you please consider only putting related
> libraries into a repository. You are probably using a workflow which
> makes it convenient to have everything in one repository, but this
> makes it harder for other people.

Nearly everything in my elisp repository is old and unmaintained.  The
only thing I'm still using these days is the external address book
stuff.

**Comment by tarsius** [comment]
I am importing "plain file" packages again. In other words everything is being updated on the Emacsmirror again.

**Comment by milkypostman** [comment]
So does this mean all the emacswiki packages are now in the git repo?  At
this point I feel like it'd be so much better to use the mirror but I worry
about pulls breaking in the future. But at this point he wiki is so
unreliable.

**Comment by tarsius** [comment]
> So does this mean all the emacswiki packages are now in the git repo?

Unfortunately no. The code is all there but edits are not being pushed to [emacsmirror/emacswiki.org](https://github.com/emacsmirror/emacswiki.org) yet. Since the wiki's recent outage @nicferrier has taken over hosting and so he also has to push to the repository on Github. Unfortunately I overlooked the mails from Alex and Nic about this for a few days, and now it seems to be Nic's turn to let things rest for a while.

Also I am still not mirroring the packages which I haven't ticked off in https://github.com/milkypostman/melpa/issues/2128#issuecomment-68576555. I can go thru that list again, and were necessary and feasible fix things on the Emacswiki myself, but I would rather not include most of these packages.

Most of these libraries get a few basic (and in some cases only superficial) very wrong. These problems might not be important, but they always make me wonder: if the author get's this wrong, then what else is also broken? @purcell is doing a great job reviewing submissions to Melpa and having upstream fix them first. This is very useful as we get to use the package and because the author get's to learn something. With packages from the wiki that doesn't work. It can be hard to contact upsteam and if we apply the fixes ourselves they might be reverted at any time.

Since it is likely that at some point in the future *all* wiki packages are removed from Melpa, could be please remove at least these packages *now*.

**Comment by zenspider** [comment]
> You are probably using a workflow which makes it convenient to have everything in one repository, but this makes it harder for other people.

How? I already have a couple recipes on melpa that have no problems using a subset of a github repo.

**Comment by Fuco1** [comment]
Same question as @zenspider 's here, I don't understand the issue.

**Comment by tarsius** [comment]
> How? I already have a couple recipes on melpa that have no problems using a subset of a github repo.

That's a feature of Melpa and it exists because having e.g. `foo-helm.el` in the same repository as `foo.el` makes sense, even though not every user of `foo` is a `helm` user. Having the two libraries in one repository is convenient for the maintainer, if she changes a function in `foo` which is used in `foo-helm`, then she only needs to write one commit message (which likely will be more useful than a "adapt to changes in foo" message in a separate `foo-helm` package).

At the same time it makes sense for Melpa to split that repository into two packages though, and I am sure you understand why.

And then there are people like me who do not actually use Melpa and install packages using git submodules. I can live with the byte-compiler complaining that `helm` cannot be found when batch compiling the libraries in the `foo` repository.

But it is annoying when a repository contains libraries that have next to nothing to do with each other. As a user I can live with it if I really want to use one of the libraries from one of these grab bag repositories. But as the maintainer of the Emacsmirror I am forced to ignore such repositories, as I would have to name the repository `several-unrelated-libraries-by-xyz`.

**Comment by tarsius** [comment]
@milkypostman I have gone through the list of wiki packages missing from the Emacsmirror again and decided which I am willing to import. And I have opened #2398 to remove the other packages from Melpa too.

**Comment by tarsius** [comment]
I am mirroring `swbuff-x` now, and `swbuff` as a "static" package too. So now all wiki packages can be found on the Emacsmirror, except for the once I have asked you to remove in #2398.

**Comment by zenspider** [comment]
> And then there are people like me who do not actually use Melpa and install packages using git submodules.

So, this really isn't about melpa? I am confused. You're asking @Fuco1 and I, on a melpa issue, to break up my/our repository structure(s) and (potentially) workflow(s) for a _completely non-melpa issue_?

**Comment by tarsius** [comment]
@zenspider It came up in the context of a discussion about Melpa and the Emacsmirror. I like to sometimes have a conversations instead of acting as an issues processor and so the topic shifted a bit. I had hoped that something productive would come out of it, but as it turned out it was confusing and can be interpreted as an attempt to falsely imply the proposed change was for the benefit of Melpa. That is not what I intended and I apologize for having confused you.

I will open a separate issue in your repository.

@Fuco1 Just in case you think that I have asked you to split up `dired-hacks`; I did not and actually don't think that doing so would be reasonable. In your case this was all about a feature conflict. Because you didn't want to rename your library and because I consider your implementation to be superior, I addressed the issue on the Emacsmirror by deleting the other library and mirroring yours instead.

I then went on making another, unrelated request. Turns out that was confusing, I will open a new issue on your repository for that too.

**Comment by zenspider** [comment]
thanks for clarifying.

**Comment by tarsius** [comment]
I've assigned this to myself as a way to keep track of it. This does not necessarily mean I will do something.

**Comment by tarsius** [comment]
Now that https://github.com/melpa/package-build/pull/9 has been merged into Melpa, this is no longer on the table.
