### ISSUE TITLE
Allow recipes to generate Info manuals from Org files

### ISSUE THREAD

**Issue by vermiculus** [melpa/melpa#2251]
This is very much related to #561 (arising from vermiculus/sx.el#109 and somewhat related to #1486). The question is in the title, really. I would like to avoid tracking a generated file if at all possible, but I don't see a good workaround.

**Comment by phillord** [comment]
I would like something similar. In the case of my package, lentic, though, it the org files are themselves generated from the literate source of lentic, using lentic. After that, I generate info files somewhere down the line with org-export. So, if you could let me run arbitrary lisp on your server, that would be excellent....

Working on the basis that this is not going to happen any time soon, can I suggest an alternative? Provide the ability to get the info files from somewhere else, specified in the recipe (which you control because it's in MELPA, so people cannot change it underneath you to something naughty).

Something like

    :info-url "http://example.com/"

in the recipe. You could append commits hashes to this during build, to cope with the versioning issue. That way I can run the arbitrary lisp on my server from a webhook or something, and you download the info files from there.

Just chewing over the ideas here. But it does avoid the nasty alternative of putting generated info files into git.

**Comment by phillord** [comment]
Oh, you said, "Authors have, in many cases, made adjustments to their repos in order to accommodate MELPA.". Can you give an example or elucidate a bit? I don't want to screw up my trunk with generated files, but I could probably bring myself pushing generated info to a branch, as it wouldn't mess with my history.

**Comment by purcell** [comment]
> So, if you could let me run arbitrary lisp on your server, that would be excellent....

Unfortunately, that's one of the things we want to avoid. :-)

> Oh, you said, "Authors have, in many cases, made adjustments to their repos in order to accommodate MELPA.". Can you give an example or elucidate a bit? 

This has tended to involve them removing preprocessing steps and providing us with compatible files directly in the repo. At the end of the day, this is the only option which provides an author with a reliable method of generating the content he wants using his source format and tools of choice.

> I don't want to screw up my trunk with generated files, but I could probably bring myself pushing generated info to a branch, as it wouldn't mess with my history.

Branches aren't a great fit for this IMO, because they can diverge, and MELPA wants to reliably track the development branch. But a compromise might be to check in a "dist" subdir or similar containing the icky generated file. Don't think of it as polluting your repo as much as a practical solution which gives you full control over the generation process. :-)

I'm as much of an SCM puritan as anyone, so I understand the desire to keep a repo pristine, but this issue comes down to asking us to add a great deal of complexity to MELPA to accommodate a workflow which is currently very rare.

**Comment by phillord** [comment]
I understand your point, although resolving a few URLs seems low on complexity (most of which would be at my end, making sure that the URLs resolve). I would be willing to provide a patch to that end.

No worries if not; I understand that it's rare -- the majority of emacs-lisp packages do run directly from source.

**Comment by purcell** [comment]
> I understand your point, although resolving a few URLs seems low on complexity (most of which would be at my end, making sure that the URLs resolve). I would be willing to provide a patch to that end.

It's really not low on complexity, though. How would we reliably obtain a timestamp for those remote files, in order to combine it with the previous files? Even if that were possible, what if those timestamps changed spuriously, or the files went missing in future, or the server were inaccessible? Does the timestamp of the resulting package go back in time, even if there are newer commits in the repo?

We can only do this stuff reliably with the help of a proper SCM, which is why we don't have a flavour of `:fetcher` which just grabs URLs (a la `el-get`, which has no concept of versions).

**Comment by phillord** [comment]
Sure, these problems are there. In terms of "timestamp", I would give a URL as a format string "http://example.com/lentic/%s" which gets passed the git hash as an argument. If it it not there (because the server is not accessible or what ever) there are two options: the attempt to build that recipe terminates which should result in a retry next time around; or the build completes with an incomplete package.

Obviously an incomplete package is not ideal. For lentic, it is no worse than now, of course. For others, it might also result in a broken or uninstallable package. But, that is also true now, given that I think the majority of emacs developers run with a dirty head.

So, it still has most of the advantages of a SCM based system. I realise that it requires a degree of trust that the URL resolution is doing what it claims to do.

Again, no worries if it is not possible. If it is possible, then am willing to write the code to get it working.

**Comment by Bruce-Connor** [comment]
@phillord One alternative (which we're currently considering for sx) is to have Travis compile the info files for you. Travis can compile the files whenever there's a new push to `master`, and push the result to another branch (called `melpa`, or `distrib`). Then you just point the Melpa recipe to point to the `distrib` branch instead of master.

The disadvantage is that Travis can sometimes take a few hours to finish, and that really increases the time between a push and a Melpa build.

**Comment by vermiculus** [comment]
> Again, no worries if it is not possible. If it is possible, then am willing to write the code to get it working.

The best way to find out if something is possible is to implement the solution :smile: I worry though about separating the documentation from the repository. It may be better to provide an `eval-when-compile` form that process the documentation on the client emacs, but I personally haven't figured out how to truly implement this.

From a `package.el` perspective, is it possible to add a 'hook' of sorts onto the download? In that case, then no such `eval-when-compile` form would be needed; a repository would just specify a hook to be run after the package installs.

I see one potential problem with the hook approach, though – if packages are being updated automatically on the client emacs, then the installation of one package has the potential to be indefinitely blocking.

**Comment by Bruce-Connor** [comment]
> I'm not sure about this one, the more I think about it. We could definitely set up Travis to push to the branch after every build, but remember these builds include PRs that may not ever be merged

You can configure a Travis recipe to only build from specific branches (in this case, `master`).

**Comment by Bruce-Connor** [comment]
> It may be better to provide an eval-when-compile form that process the documentation on the client emacs, but I personally haven't figured out how to truly implement this.
This might actually work. :-) The only problem is that the user might not have the necessary build tools installed. I'm also not sure how ethical it is... You're imposing a very slow build process on the user that isn't really necessary, every time they upgrade.

> From a package.el perspective, is it possible to add a 'hook' of sorts onto the download? In that case, then no such eval-when-compile form would be needed; a repository would just specify a hook to be run after the package installs.

I've been meaning to add a post-execute hook to package.el (similar to what I've added to Paradox), but I don't see how that could help here. Adding a function like `my-package--build-info` to this hook as part of installation is pretty much the same thing as manually calling the function during installation.

**Comment by phillord** [comment]
@vermiculus So, my documentation IS in my repository -- it's part of the .el files, which get transformed to org, which in turn gets transformed to info. 

@Bruce-Connor Yes, this might be a solution, although how can travis push to github? It would need keys, which would have to be in git? Still doing this on my local machine I can understand. The only problem that I can see is that for MELPA-stable I'd have to get my release tags on the right place.

The other option would be to pull if from MELPA and just host release versions on Marmalade. Nic is very keen on the idea that packages are not the same thing as source, and this seems to be a case in point.

**Comment by Bruce-Connor** [comment]
> @Bruce-Connor Yes, this might be a solution, although how can travis push to github? It would need keys, which would have to be in git?

Yes, it needs a Github key. You need to provide it in your `.travis` file and [you can hide it with encryption](http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci).

**Comment by vermiculus** [comment]
> You can configure a Travis recipe to only build from specific branches (in this case, `master`).

Yes, but I'm not sure if that would nix PR builds. I'll try to test it out later on this week, but moving-related things are coming to a climax this week.

> I've been meaning to add a post-execute hook to package.el […]

Might it be more appropriate then to offer post-processing capabilities to `package.el` rather than MELPA? It is a bit of a shame considering the processing would be done on the client *n* times rather than upstream *once*, but it's an option to consider.

> So, my documentation IS in my repository -- it's part of the .el files, which get transformed to org, which in turn gets transformed to info.

With all due respect (which is massive at this point), you're *insane*. :wink: You should consider going the other way around with org-babel, but that's a discussion for not-this-thread. Perhaps gitter chat on vermicululs/sx.el? The repo page has a link.

> […] although how can travis push to github? It would need keys, which would have to be in git?

The link @Bruce-Connor provided is good, but there's also a repository out there that will track this kind of information very well. I can't for the life of me find it, though :frowning: I thought I starred it…

**Comment by Bruce-Connor** [comment]
For the record. @lunaryorn [blog](https://github.com/lunaryorn/blog) is an example of this "use-travis-to-push-to-githuv" setup.

**Comment by phillord** [comment]
@vermiculus good to be called insane in a respectful way! org-babel is cute, and I could do that, but that would break melpa in the same way (actually worse -- lentic runs but you can't see the documentation, which is surely better than being able to see the documentation but not run it!)

**Comment by lunaryorn** [comment]
@Bruce-Connor It used to while I were using Github Pages, but it's on a private server now, and I do not longer use Travis CI to build the blog.

Being mentioned, I might as well add my opinion on this issue, too:   I do not think that MELPA needs to provide anything beyond the standard Emacs toolchain—`makeinfo`, that is.   Any addition to the server side build system, however simple and small, adds complexity that needs to be maintained—maintained by volunteers who have already more than anyone of us to serve our community.

With this in mind, I find that desire to keep the history of your repositories clean is not a sufficient reason to put even more work on MELPA's shoulders.  They are doing more than enough for you already.  In other words, I think that putting some generated files into your repository and updating them from time to time is a **very small price** you pay for the convenience that MELPA gives you, and that you'll hardly find in any other programming language or community.

Just my 2 cents, as the maintainer of one of the most popular packages on MELPA, with a large, and generated manual.

**Comment by phillord** [comment]
@lunaryorn In general, I'd agree, but then at one point MELPA didn't do texi if I remember. And, the "standard emacs toolchain" is one very much under discussion at the moment. It's worth at least discussing whether some minimal extension point can be added.

If in the end, I have a distrib branch with generated files, then okay, I cope with that.

**Comment by lunaryorn** [comment]
@phillord MELPA does Texinfo because it's the standard route to Info, which is what Emacs wants, even more, because it's easy and cheap.  I don't think that it needs to support anything, specifically if it's not cheap and easy.  Org Mode isn't.  Curling random URLs isn't either.

And if this “limitation” puts a little work onto our shoulders, and adds a little clutter to our repo, so what?  

It's just one generated file in your repo, after all.  What harm does that do, other than a funny feeling that your repo history might be “unclean”?  

I can think of none.  Yet, to relieve this small nuisance you ask MELPA to implement *and maintain* a complex pipeline to fetch or build info files?

I find this imbalance striking.

**Comment by phillord** [comment]
@lunaryorn Chill out, man. The question here is whether it is possible or not, and whether the MELPA maintainers would be willing to take it if it is. I didn't ask them to implement or maintain anything. As it happens, (done simply) it is not hard to implement because I did it this morning. Done well, I don't know, it would probably take longer yes. And, yes, it would need maintaining.

In my case, it's the same number of files as I have lisp files and if they are to be in sync, they need to be regenerated *every time* the lisp changes. Negative impact? Every check in gets a bunch of false diffs.

I now have two workable solutions: auto-commit info files on a branch, or complete a MELPA download based system. Is the later a big ask? I don't know, that's why I am asking.

**Comment by purcell** [comment]
> I now have two workable solutions: auto-commit info files on a branch, or complete a MELPA download based system. Is the later a big ask? I don't know, that's why I am asking.

I really am not keen to go the latter route at this stage, I'm afraid.

**Comment by lunaryorn** [comment]
@purcell :+1:

**Comment by phillord** [comment]
@purcell No worries, will complete the other option.

@lunaryorn MELPAs tool chain is hardly it's selling point -- I can (and do) use Cask client side to achieve the same thing. The curated recipes and that fact that it is in one place is.

Regardless, I will move forward with the solution that I have.

**Comment by tarsius** [comment]
I've assigned this to myself as a way to keep track of it. This does not necessarily mean I will do something.

**Comment by purcell** [comment]
Closing because I don't think there's any plan or desire to implement this.

**Comment by tarsius** [comment]
Maybe there's a newer issue about this, but that's the one I found, so I comment here. This came up again in https://github.com/melpa/package-build/issues/88. The technical issue mentioned there has been addressed.

> Closing because I don't think there's any plan or desire to implement this.

I have implemented it a few years ago. I believe we decided to not use this on Melpa due to security considerations.

FWIW, here's how this feature would be used.

Simple case:

```elisp
(transient
 :fetcher github
 :repo "magit/transient"
 :files (:defaults "docs/transient.org")
 :org-exports ("docs/transient.org"))
```

If the file names don't match:

```elisp
(jinx
 :fetcher github
 :repo "minad/jinx"
 :files (:defaults "jinx-mod.c" "emacs-module.h" "README.org")
 :org-exports (("README.org" "jinx.texi")))
```

This could be enabled with `(setq package-build-run-recipe-org-exports t)`. I am not necessarily arguing that we should do that. I would like to not have to check in the generated texi files for my own packages anymore, but respect the security argument.

Over at https://github.com/melpa/package-build/issues/88#issuecomment-2351633624, @jian-lin asks whether we would be willing to accept pull-requests that add `:org-exports` to some recipes, even though Melpa itself doesn't use it.

I'll let him argue here why we should.
