### ISSUE TITLE
Melpa stable can't find package-build

### ISSUE THREAD

**Issue by nlamirault** [melpa/melpa#2557]
could you please create a tag to use package-build using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by purcell** [comment]
Sure, we can do this at some point. Note that in general you're going to have a hard time if you try to use MELPA Stable without MELPA: see #1955.

**Comment by nlamirault** [comment]
Yes. I creates a lots of issue to packages maintainer to creates tag.

**Comment by purcell** [comment]
Okay, great. At some point in the dependency chain, though, you might find dependencies on packages which come from the emacswiki or SCMs which we don't yet support with MELPA Stable.

**Comment by nlamirault** [comment]
Yeah. I use only one dependency which comes from Wiki (multi-term). I send a mail to the maintainer to check if he could migrate to a Git repository.

**Comment by tarsius** [comment]
@purcell Since it's in its own repo now, we should tag `package-build`. I think `v1.0.0` would be fitting. Being in its own repo it might get more attention now and those might result in backward incompatible changes. So it might be good to bump the major version once that has happened, but for that we need there to be major version we can bump from.

**Comment by purcell** [comment]
Good idea, done.
