### ISSUE TITLE
Can't reach melpa

### ISSUE THREAD

**Issue by MatthewRock** [melpa/melpa#3471]
I have two PCs that I've used from various locations(so I'd rule out internet issue). On both PCs, I use Emacs with Prelude. Now I can't reach melpa when using epl-refresh. I can connect elpa just fine, but it gets stuck on melpa, with message:

Contacting host: melpa.org:80

How can I fix the issue? Any ideas?

**Comment by dunn** [comment]
Does it work if you change `http://melpa.org` to `https://melpa.org`?

**Comment by milkypostman** [comment]
are you still having this problem? i can get to it.
http://www.downforeveryoneorjustme.com/melpa.org

**Comment by purcell** [comment]
@MatthewRock Just because the last message you see is `Contacting host: melpa.org:80` doesn't mean that that is where Emacs is hanging. A recently-fixed-in-Emacs quirk is that the message isn't cleared once the package index has been downloaded. Perhaps enable `debug-on-quit`, and then hit `C-g` once hanging: you may then get a backtrace with useful info.

**Comment by berhoel** [comment]
"melpa.milkbox.net/packages" currently returns "No such site at :80" for http and https, and melpa.org is not responing at all (from a browser).

**Comment by purcell** [comment]
@berhoel Resolved now, sorry for the interruption of service.
