### ISSUE TITLE
Make our website's Javascript acceptable to LibreJS

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#3731]
See #3728 and [this reddit thread](https://www.reddit.com/r/emacs/comments/4d0r7c/rms_there_is_a_big_ethical_problem_with_site/) in relation to RMS's assertion that our website has "ethical problems".

In short, we would like to help the GNU LibreJS browser extension to correctly detect that all the Javascript we serve is open source software.

Quoting @artlogic in #3728:

> Obviously, the site specific JS could be given a proper LibreJS tag: https://www.gnu.org/software/librejs/manual/html_node/Setting-Your-JavaScript-Free.html
> 
> I'm not sure if LibreJS is smart enough to notice that Mithril and moment.js are MIT Licensed (headers exist in their minified source code). Lodash is also MIT licensed, but refers to it's website instead of stating it outright. Cookies.js has no license header and appears to be public domain - see: https://github.com/ScottHamper/Cookies/blob/master/UNLICENSE (I realize both the "MIT License" and public domain are contentious topics).
> 
> I'm hoping to make most of these dependencies progressive enhancement, but it would still be nice to understand what LibreJS will do in the above cases. Does anyone know?

**Comment by artlogic** [comment]
After learning a bit more about LibreJS, I've sent a request to the mailing list in the hopes of whitelisting all the external Javascript. If that's successful, I'll submit a pull request adding the proper headers to `melpa.js`.

**Comment by purcell** [comment]
Thanks! There's probably still something to be done around putting copyright info in `melpa.js`.

**Comment by artlogic** [comment]
Yup - I'll submit a pull request. I was just waiting to hear back from the LibreJS people.

**Comment by aplaice** [comment]
(Disclaimer: not affiliated with librejs, don't actually use it; think blacklisting of MELPA over such triviality would be stupid)

According to [the most comprehensive guide](https://www.gnu.org/software/librejs/free-your-javascript.html), the easiest way to inform LibreJS that a given js file is FOSS, is using web labels, effectively creating an html file containing a table with the URLs of all the scripts you load (including scripts from other domains!), their licenses and links to their unminified forms.

LibreJS does, indeed recognise some js files as free based on their hash, but I'm not sure how scalable and easily-updatable this approach is. (Currently the list of pre-approved files is [here](http://bzr.savannah.gnu.org/lh/librejs/dev/annotate/head:/data/script_libraries/script-libraries.json).)

In the case of inline (embedded) javascript one needs to surround all the javascript used with `// @license` and `// @license-end` tags (or have a license section in the document header).

For MELPA, all the scripts needed for basic functionality are already free and the following changes should make the site work with LibreJS:
1. change `melpa/html/index.html`, adding:
```html
    <a href="/jslicense" data-jslicense="1">JavaScript license information</a
```
somewhere (for example in the footer) and
2. create `melpa/html/jslicense` with (at least) the following table:
```html
<table id="jslicense-labels1">
	<thead>
	  <tr>
	    <th>Script</th>
	    <th>License</th>
	    <th>Source</th>
	  </tr>
	</thead>
	<tr>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/mithril/0.2.0/mithril.min.js">mithril.min.js</a></td>
          <td><a href="http://www.jclark.com/xml/copying.txt">Expat</a></td>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/mithril/0.2.0/mithril.js">mithril.js</a></td>
	</tr>
	<tr>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js">moment.min.js</a></td>
          <td><a href="http://www.jclark.com/xml/copying.txt">Expat</a></td>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.js">moment.js</a></td>
	</tr>
	<tr>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js">lodash.min.js</a></td>
          <td><a href="http://www.jclark.com/xml/copying.txt">Expat</a></td>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js">lodash.js</a></td>
	</tr>
	<tr>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/Cookies.js/1.1.0/cookies.min.js">cookies.min.js</a></td>
          <td><a href="http://www.jclark.com/xml/copying.txt">Unlicense</a></td>
          <td><a href="//cdnjs.cloudflare.com/ajax/libs/Cookies.js/1.1.0/cookies.js">cookies.js</a></td>
	</tr>
	<tr>
          <td><a href="/js/melpa.js">melpa.js</a></td>
          <td><a href="http://www.gnu.org/licenses/gpl-3.0.html">GNU-GPL-3.0-or-later</a></td>
          <td><a href="/js/melpa.js">melpa.js</a></td>
	</tr>
</table>
```

(Here are the full files: [index.html](http://pastebin.com/GSPxz8jx) and [jslicense](http://pastebin.com/tyVq1ifD) — if you prefer I could send a pull request.)

I've tested this, so it should just work. However, that was on my system for which I had to change the paths (so that melpa "worked") and I might not have changed everything back correctly.

Obviously, this will not make LibreJS accept the twitter or google-analytics javascript, since these are not FOSS, but at least the core functionality will work.

**Comment by artlogic** [comment]
@aplaice That would certainly be the quickest way to get things going. I have yet to hear back from the LibreJS folks. You can see my request here: http://lists.gnu.org/archive/html/help-librejs/2016-04/msg00000.html

If you have the work done already, and if @purcell agrees, I'd be happy to test your code to verify it works on my system.

**Comment by aplaice** [comment]
I've sent a pull request melpa/melpa#3753 (though obviously the MELPA maintainers may want to take a different approach/forgo LibreJS support if it's more effort than it's worth).

**Comment by artlogic** [comment]
@aplaice I've tested and commented in the pull request. Unfortunately it looks like we'll need to wait and see about the "unlicensed" piece of code.

**Comment by artlogic** [comment]
@purcell I've emailed the LibreJS maintainer in an attempt to move things along.

> Another developer and I have made a couple of requests about whitelisting libraries and licenses on both bug-librejs and help-librejs, but there has been no response. Here are the relevant posts:
>
> http://lists.gnu.org/archive/html/help-librejs/2016-04/msg00000.html
> http://lists.gnu.org/archive/html/bug-librejs/2016-04/msg00001.html
>
> I hope you don’t mind me emailing you directly, but we’re attempting to get LibreJS to recognize the MELPA repository website as free software: http://melpa.org/
>
>Is there anything I can do to help make this happen?

**Comment by purcell** [comment]
Great -- thanks so much for your help with this.

**Comment by artlogic** [comment]
@purcell - I got to thinking, since the hold-up here is Cookies.js, and it's barely used, how would you feel about stubbing out a mock object that would be used if window.Cookies is undefined?

```js
window.Cookies = window.Cookies || {
  get: function () { },
  set: function () { },
  expire: function () { }
};
```

I'd be happy to submit a pull request if this would be acceptable.

**Comment by purcell** [comment]
I'd rather not put too much effort into working around this just for a handful of users. We can consider our options when and if we get a response from the LibreJS folks.

**Comment by artlogic** [comment]
I just heard back from the LibreJS maintainer. He will be adding Unlicense. Additionally, the four libraries will be whitelisted at some point in the future. I don't believe there's any further work to be done on this issue other than testing once LibreJS is updated.

**Comment by aplaice** [comment]
@artlogic Thank very much for e-mailing the LibreJS maintainer directly, as it seems to have sped things up considerably (he finally replied both to your [initial question](http://lists.gnu.org/archive/html/help-librejs/2016-04/msg00003.html) and my [later one](http://lists.gnu.org/archive/html/bug-librejs/2016-04/msg00008.html)).

@purcell Thank you for merging the patch!

**Comment by purcell** [comment]
Thanks so much for your help with this, folks!

**Comment by tarsius** [comment]
So this has been taken care of. (Of course if someone actually installed librejs and reported the result, that would be nice.)

**Comment by purcell** [comment]
I recall trying it at some point, and I think it was fine. I'm sure someone will file a fresh issue if not.

**Comment by To1ne** [comment]
The site is fully functional with LibreJS enabled (6.0.13). But there is still a "Complain" tab because the Google Analytics code is non-free (although, I don't mind it being blocked).

**Comment by wasamasa** [comment]
I've retested and found that the non-HTTPS version of the website still fails the LibreJS checks. The HTTPS version is fine. Trying to access the non-HTTPS version results in a client-side redirect to HTTPS, most likely due to the Strict-Transport-Security header. Could someone please ensure either feature parity between both versions or that there's a hard redirect from HTTP to HTTPS?

**Comment by milkypostman** [comment]
what kind of redirect would work? seems like what we have is just a
standard nginx redirect. its all available in the repo if you could explain
what we're doing wrong that would help.

its not soft in that its not in JS or anything, its a 301 or whatever http
code.

**Comment by wasamasa** [comment]
Hm, looking closer at this, the served website is identical for both versions, so this might be a false positive from LibreJS and they have a bug loading HTTPS resources from a HTTP site.

For the record:

```
$ curl -I http://melpa.org 
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 26 May 2020 11:20:23 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3864
Last-Modified: Fri, 10 Apr 2020 04:47:54 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "5e8ffa7a-f18"
Strict-Transport-Security: max-age=15768000
Accept-Ranges: bytes
```

I don't see any redirects other than for obsolete domains in https://github.com/melpa/melpa/blob/master/docker/nginx/default.conf. Should I create a pull request to update the config?

**Comment by milkypostman** [comment]
yeah I'm not sure the best way to reconcile this. I'd guess that its mostly
hardcoded. will see if there is something we can do. if you have
suggestions or a PR that would expedite things.

**Comment by aplaice** [comment]
The LibreJS issue is caused by the protocol for the external JS resources being hardcoded as `https`,  in [`index.html`](https://github.com/melpa/melpa/blob/master/html/index.html), but `jslicense.html` inheriting the protocol (using `\\`) in its list. This means that when melpa is loaded from `http://melpa.org`, then there's a mismatch between the URLs that `jslicense.html` reports as free (`http://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.5/mithril.min.js` etc.) and what the browser actually tries to load (`https://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.5/mithril.min.js` etc.).

Testing locally, changing `jslicense.html` to use strict `https` for its list of external js sources (to match what's already used in the `script src`s in `index.html`) resolves the issue.

**Comment by wasamasa** [comment]
Thanks, that resolved that issue indeed.
