### ISSUE TITLE
waiting for refresh to finish....

### ISSUE THREAD

**Issue by sjLambda** [melpa/melpa#3752]
For the last few days my packages-list-packages stopped working. I get a permanent hang on "waiting for refresh to finish" message.

M-x list-processes shows it failed on melba; I've used both http and https URLs. 

I also tried 
M-x toggle-debug-on-error 
M-: (switch-to-buffer (url-retrieve-synchronously "http://melpa.org")) 

and I get the usual headers followed by:
      Please see the <a href="/">main page</a> for a full package
      listing. You will be redirected automatically.

I am using the most recent emacs git sources from savannah.
M-x version is: GNU Emacs 25.1.50.1 on Mac OSX. 

I've recompiled and reinstalled emacs as well. I've tried emacs with --no-init-file and -Q also.

Is there any hope?

Thanks.
--Lambda Coder

**Comment by liotev** [comment]
I have the same problem, also on Mac OS X.

**Comment by purcell** [comment]
Nothing has changed on our side over the last few days. Is the problem due to your recent emacs snapshot? Can you reproduce it with the last stable Emacs release?

**Comment by purcell** [comment]
More details needed, please. I can't reproduce this locally. Perhaps it is due to proxy settings or similar. Note that GNU ELPA is always enabled by default, and it has had some issues recently, so seeing the "waiting for refresh to finish" message is not necessarily an indication that MELPA is at fault.

**Comment by liotev** [comment]
Sorry, here are more details: this happens with Emacs snapshot, I pull it from the Git repo and compile it locally. When I switch to Emacs 24 it does not happen. The function "package-menu-mark-upgrades" is different in the latest Emacs code, I think this the reason for the issue.

**Comment by purcell** [comment]
Yeah, could be an Emacs snapshot bug, then. I'm using a recent snapshot too and I don't see that problem. `configure` flags can potentially make a difference too, because they can affect the SSL connection methods used (gnutls vs openssl etc.). Not sure there's anything I can follow up on here, sorry.

**Comment by tarsius** [comment]
@sjLambda @liotev is this still an issue?

**Comment by liotev** [comment]
@tarsius No , with the latest Emacs version this does not happen any more.
