### ISSUE TITLE
Is there a way to automatically tangle org files as part of build process?

### ISSUE THREAD

**Issue by stig** [melpa/melpa#3777]
I maintain [ox-jira.el](https://github.com/stig/ox-jira.el). The primary source for this is in `ox-jira.org`, but I would love to avoid having the ox-jira.el checked in, as it complicates contributions. (Case in point: I just received a PR that touched only the generated ox-jira.el, and have to instruct them to make changes to the corresponding .org file instead.)

**Comment by purcell** [comment]
It's not currently possible, but I can see how it would be nice.

It's quite a niche use-case overall, and I'm concerned that supporting it would complicate the `package-build` code considerably. Plus, all source `.org` files would have to contain headers like your `;;; ox-jira.el --- JIRA Backend for Org Export Engine` in order to tangle into valid packages, so it's perhaps non-trivial for authors to reliably create well-formed packages.

**Comment by stig** [comment]
Yeah, I currently have to include the special headers in my org file:
https://github.com/stig/ox-jira.el/blob/master/ox-jira.org#header

I have a small shell wrapper that tangles that file before running the
tests:

    #!/bin/sh -e
    
    # first regenerate *.el files from *.org  sources
    cask eval '(load-file "tangle-org-files.el")'
    
    # Now run tests
    cask exec ert-runner -L . -L test "$@"

I totally understand that it's a bit niche though.


The other thing I thought of was to writing a tiny "bootloader" that
just called `(org-babel-load-file "ox-jira-real.org")`, but I'm not sure
if that would be considered bad form.

**Comment by purcell** [comment]
Looking back at this, I'm going to close it as "won't fix": I value the simplicity of the MELPA build process, and authors can tangle upstream in order to distribute plain `.el`, albeit at the expense of needing to commit duplicate files.
