### ISSUE TITLE
htmlize source no longer exists

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4125]
The url for its git repo just returns 404 now.  I don't know what the usual procedure is for things like this.

**Comment by dunn** [comment]
Oh dear: http://fly.srk.fer.hr/

If anyone has contact information for Hrvoje Nikšić they could see if he can move the source to GitHub or GitLab.

**Comment by purcell** [comment]
If someone can/will create a fork in the meantime, we can point the recipe at that.

**Comment by tarsius** [comment]
Org also bundles a copy of `htmlize` (at `contrib/lisp/htmlize.el`) but it is behind a few releases (`1.43` vs. `1.47`) and also contains some changes that probably haven't made it upstream.

I think it would be best if these two versions could be merged, be maintained in a repository separate from the Org repository, and be added to GNU Elpa so that the "Org with contributions" flavor can easily depend on it. Maybe the Org maintainers would we willing to do that if someone asked nicely.

**Comment by purcell** [comment]
Yeah, I'm not sure the `org` folks are very big on modularised packages, judging by their work to date. In an ideal world, all of their contribs would be separate packages...

**Comment by dunn** [comment]
I have a local copy of the repository up to the 1.47 tag; I think that's the latest commit.  If that sounds right I can throw it up somewhere as a mirror.

**Comment by purcell** [comment]
Probably worthwhile, I guess. In the meantime that looks like the author's email address, so can you send a quick email to enquire about the missing repo?

**Comment by dunn** [comment]
Email sent; in the meantime here we go: https://github.com/dunn/htmlize-mirror

**Comment by purcell** [comment]
Done in 8d1d4a1, thanks. I'll leave this issue open now pending a reply from the author.
