### ISSUE TITLE
bbdb-20160720.2318 fails to compile due mu4e-view requirement

### ISSUE THREAD

**Issue by jhartotr** [melpa/melpa#4287]
The package includes bbdb-mu4e.el which requires mu4e-view. Compilation fails on environments without mu4e as follows:

bbdb-mu4e.el:28:1:Error: Cannot open load file: No such file or directory, mu4e-view

**Comment by syohex** [comment]
Because [mu4e](https://github.com/djcb/mu) is not melpa package. Please install it before using it.

**Comment by jhartotr** [comment]
that's exactly the issue. I don't use mu4e but gnus. Compilation of the bbdb package should succeed without installing mu4e.

**Comment by syohex** [comment]
BTW this is `bbdb` issue.

**Comment by purcell** [comment]
Ideally, `mu4e` would be an installable package, so that any code which used it could declare a package dependency. It isn't an installable package, though, so currently we have two options:
1. Keep the current situation, which I believe results in a single file not getting byte-compiled at installation time. The bbdb package should otherwise work okay.
2. Exclude `bbdb-mu4e` from our `bbdb` package, and build a separate package for it. This would involve changes to `bbdb-mu4e.el` so that it declares a package dependency on `bbdb`

@jhartotr Would you like to talk to the bbdb maintainers about this issue, and suggest option 2?

**Comment by tarsius** [comment]
@jhartotr Did you follow up on this with the bbdb maintainers?

**Comment by purcell** [comment]
Closed due to lack of response.
