### ISSUE TITLE
Should shen-elisp be removed?

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#4370]
1. A package is supposed to provide a library whose name matches the package name, but `shen-elisp` does not provide a library `shen-elisp.el`. This could be fixed by either adding such a library, or by renaming the package to `shen`.
2. The library `shen.el`, which I consider to be the "main library" for now, does not have a proper library header and commentary.
3. That library is also extremely messy.

@deech do you consider this package to be something anyone would want to use or is it a personal project for learning purposes? In the latter case I think this should be removed from Melpa.

**Comment by deech** [comment]
1. Shen Elisp is an implementation of the Shen programming language in Elisp.
2. I can add a header to `shen.el` if that's a requirement of `melpa`. When I submitted it for inclusion I wasn't aware of that.
3. `shen.el` is generated code which is why it's messy. The commented code which generates it is here https://github.com/deech/shen-elisp/blob/master/shen-elisp.org. That file was rejected for inclusion it wasn't an Elisp file.

It is meant for people to use. Please see further motivation in the README. https://github.com/deech/shen-elisp

**Comment by tarsius** [comment]
> I can add a header to `shen.el` if that's a requirement of `melpa`.

That would be nice, thanks. But then the Melpa package should also be renamed to `shen`, which might not be the worst option. If you would rather keep the name `shen-elisp`, then you should either rename `shen.el` to `shen-elisp.el` or add an additional library `shen.el`, which just contains the package metadata and `(require 'shen)`.

**Comment by deech** [comment]
I'm happy to change the file name to `shen-elisp.el` and add a header.

**Comment by tarsius** [comment]
Great, thanks!

**Comment by deech** [comment]
This issue has now been addressed (https://github.com/deech/shen-elisp/commit/640f06c25da260ef8ff219c31946f3971a6a5d00). Please close the issue if it is satisfactory.

**Comment by tarsius** [comment]
That covers the most important part. The library should also have a proper header - I've opened a pr for that #13.

**Comment by purcell** [comment]
Great outcome, thanks.
