### ISSUE TITLE
Specify Package-Requires versions as commit hashes?

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4673]
Installing packages from not-stable, occasionally I'll install a newer version of Package A that has been updated to work with a backwards-incompatible version of Package B, but not install the newer version of Package B because I don't want to upgrade everything at once, and Package A doesn't depend on the newer version of Package B.  Of course, since non-stable uses the automatically generated datestamp-type version numbers, it's not possible for package authors to mark a dependency on non-stable package versions.

So, what if packages could specify versions in `Package-Requires` as commit hashes?  Could the MELPA scripts then convert that into a datestamp-style version number, and thereby force packages to upgrade their dependencies when necessary?  Of course, this still requires the package author to update the commit hashes when a dependency makes a breaking change, but at least it would make it possible to actually version dependencies in non-stable builds.

(Alternatively, maybe PEBKAC because I like to upgrade packages piecemeal instead of all-at-once.  ;)

Thanks.

**Comment by milkypostman** [comment]
I think that originally this is how I had dependencies specified but after brief discussion it was deemed this was a bad idea. I cannot remember all the reasons but one thing to be aware of is that occasionally it can happen that package numbers go back in time because commits in git are not always in descending time. it's rare but it can happen that someone merges a commit or rebases on top of another commit but their time for the actual commit was earlier than the previous commit. we do our best to avoid the problem with merge commits but we can't always detect it or find a way to avoid it.

there was also a problem of people wanting a dependency to be an older *stable* version and if we set the dependency version as the melpa version they would not be able to do that.

**Comment by alphapapa** [comment]
I see, thanks.  :)
