### ISSUE TITLE
php+-mode is missing a file

### ISSUE THREAD

**Issue by chris-vale-ck** [melpa/melpa#4756]
`php+-mode`s [current build](https://melpa.org/#/php%2B-mode) is lacking the file`php-test.el`. This file exists in the [recipe repo](https://github.com/echosa/phpplus-mode) but didn't make it all the way through to the built package. As a consequence the mode installs and fails to load.

**Comment by aplaice** [comment]
The absence of `*-test.el` files, in the package, is intentional ([see here](https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L142)).  However, briefly looking at [`php-test.el`](https://github.com/echosa/phpplus-mode/blob/master/php-test.el), it seems that it's intended to be part of the package, rather than for testing the package, so arguably it should be included.

Installing and loading `php+-mode`:
```elisp
(use-package php+-mode
  :ensure t)
```
does result in an error:

    Cannot open load file: no such file or directory, php-test

further suggesting that `php-test.el` is indeed required.

Changing the recipe for php+-mode (currently [this](https://github.com/melpa/melpa/blob/master/recipes/php+-mode)) to:

```elisp
(php+-mode
 :fetcher github
 :repo "echosa/phpplus-mode"
 :files (:defaults "php-test.el"))
```
and building the package locally resolves the error. (Disclaimer: I have never used this package and have no idea what it's supposed to do, so I'm not sure whether the package built from this recipe actually works, other than loading without an error... Someone who uses it should look at this in more detail.)

What is slightly weird is that the package seems to be relatively frequently used (5000 downloads), but there haven't been any recent changes to the recipe (or relevant changes to `package-build.el`) that would cause the breakage.

**Comment by purcell** [comment]
I've fixed this, though I'm fairly -1 on keeping this package in MELPA over the longer term, since it's explicitly obsolete and unmaintained.

**Comment by chris-vale-ck** [comment]
Thanks for the quick turnaround on this. Where can I find the docs on the recipies and for how the build system works? I feel like had I understood the process I could have fixed the issue once Identified. In that vein is there doc about how to elect (or promote or designate) a new maintainer for a package? I'm not so keen but my shop needs the package for now so there's that.

**Comment by purcell** [comment]
I'm not going to disappear the package any time soon, but it could be a candidate in future. If someone wants to step up as a maintainer, we'd normally ask that they get the blessing of the original author if possible. If that happens, or if the original author is not responsive within a few weeks, we'll generally be happy to switch our recipe to point at the new maintainer's fork instead.
