### ISSUE TITLE
Melpa creates dir for bug-reference-github, but there is no info manual at all

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#4948]
Just installed `bug-reference-github` from Melpa via `package.el`, it adds a `Bug Reference Github` menu in Info, but there is no info manual provided by  bug-reference-github.

- https://github.com/arnested/bug-reference-github
- https://github.com/melpa/melpa/blob/master/recipes/bug-reference-github

**Comment by purcell** [comment]
That *is* interesting. The resulting package contains a `dir` file, which is why the menu entry is present, but there are indeed no info files or a dir file in the source repo... Will have to look into this sometime.

**Comment by aplaice** [comment]
The issue _is_ with the git repo itself, as the HEAD appears to be on the [develop](https://github.com/arnested/bug-reference-github/tree/develop) branch, not on master.  The develop branch does indeed contain a `dir` file without a corresponding `info` or `texi` file.

Looking at the Makefile, it seems that it's expected that the `texi` file will be generated automatically from the `README.md`, using pandoc (which is actually a clever idea, but since neither MELPA nor (afaik) Marmalade actually execute the Makefile, it's not ideally implemented in this case — generating it using a pre-commit hook like in [writeroom-mode](https://github.com/joostkremers/writeroom-mode) would have probably been preferable).

Should I ask the maintainer to resolve this (though it's technically not a bug)?

**Comment by purcell** [comment]
Thanks for investigating. Yes, please feel free to contact the maintainer. Otherwise I'm inclined to just point the recipe at `master`.

**Comment by tarsius** [comment]
*Cross referencing https://github.com/arnested/bug-reference-github/issues/3*

**Comment by aplaice** [comment]
Fixed:

https://github.com/arnested/bug-reference-github/commit/ee36f6f3f120ba9edf48753a20b1b137d789507f

**Comment by tarsius** [comment]
Thanks!
