### ISSUE TITLE
New release of caml

### ISSUE THREAD

**Issue by Chris00** [melpa/melpa#5002]
The files in the _caml_ package have been updated since 2015.  Please do a new release.

**Comment by aplaice** [comment]
Has the official/canonical source moved from the [svn repository](https://caml.inria.fr/svn/ocaml/trunk/emacs/) to [github](https://github.com/ocaml/ocaml/tree/trunk/emacs)? The MELPA caml ["recipe"](https://github.com/melpa/melpa/blob/master/recipes/caml) currently still points to svn, which hasn't been updated since 2015 — MELPA packages are updated automatically based on changes in the source repository.

**Comment by Chris00** [comment]
I think it is better to use the Github repository.

**Comment by purcell** [comment]
Hey @Chris00, note that `caml` is in danger or being removed from MELPA due to invalid package formatting (see #5010). Perhaps you'd like to follow up upstream to get those problems fixed?

**Comment by Chris00** [comment]
@purcell Thanks for letting me know.  Would these header be fine https://github.com/Chris00/ocaml/blob/melpa/emacs/caml.el ?  (If yes, I'll submit a PR to the main repo.)

**Comment by purcell** [comment]
Yes, that looks great!

**Comment by Chris00** [comment]
Here is the [PR](https://github.com/ocaml/ocaml/pull/1346).
