### ISSUE TITLE
Dodgy version of file installed when installing  go-mode

### ISSUE THREAD

**Issue by gnufied** [melpa/melpa#5019]
This one is really weird and I have tried to chase down where the bug exists.

I have go-mode installed from melpa and version installed looks like:

```
go-mode is a dependency package.

     Status: Installed in ‘go-mode-20170726.555/’ (unsigned).
    Version: 20170726.555
    Summary: Major mode for the Go programming language
Required by: go-rename-20161117.331, go-projectile-20170302.1705, go-guru-20170718.1046, go-eldoc-20170305.627
   Homepage: https://github.com/dominikh/go-mode.el
   Keywords: languages go 
Other versions: 20170726.555 (melpa), 20131222 (marmalade).

[back]
```

This should be the content of `go-mode-autoloads.el` - https://github.com/dominikh/go-mode.el/blob/master/go-mode-autoloads.el but when I see the disk the installed version is - https://gist.github.com/gnufied/be2cf169791dc84b0e4e30d26defa52c

The major difference is, missing :
```
(provide 'go-mode-autoloads)
```

line.

**Comment by purcell** [comment]
I imagine this is because you're including the `-autoloads.el` file in your repository, which you simply shouldn't do: it's a file that should be created locally by the Emacs that installs it, and the act of installing the package via `package.el` will cause that file to be generated. So you should remove the file, and just ensure that you have the appropriate `;;;###autoload` cookie comments in the main source file.

**Comment by gnufied** [comment]
Let me open a bug in `go-mode` repo with PR.

**Comment by tarsius** [comment]
*Cross referencing https://github.com/dominikh/go-mode.el/pull/213*

**Comment by purcell** [comment]
@gnufied Realised now that I was mistakenly addressing you as the author - thanks for rolling with it and following up with an upstream PR.

**Comment by tarsius** [comment]
The file was removed.
