### ISSUE TITLE
homepage button should point to homepage

### ISSUE THREAD

**Issue by wbolster** [melpa/melpa#5285]
the ‘homepage’ button on melpa pages behaves in an odd way.

for instance, look at https://melpa.org/#/direnv and click the homepage button.

expected result: link points to https://github.com/wbolster/emacs-direnv/

actual result: link points to `https://github.com/wbolster/emacs-direnv/tree/<commit-id>`

**Comment by purcell** [comment]
Thanks. I'm also finding this a bit unexpected sometimes. I made the change to address #5159, but I'll try to make it a little less invasive when I get time.

**Comment by purcell** [comment]
I chose the current behaviour because it unambigously points to the exact source tree from which the package was built, which is generally a sane thing to do, so I might just change the "Homepage" link label to read "Source". Separately packages can supply a `;; Homeapage:` or `;; URL:` header, and the ideal would be to link to that with the label "Homepage" if it is present. Currently we don't use that info in the web front end at all.

**Comment by wbolster** [comment]
thanks, i understand.

fwiw, having both the home page and commit as two links would be best.

**Comment by tarsius** [comment]
> expected result: link points to https://github.com/wbolster/emacs-direnv/

That's what we do now.

> Separately packages can supply a ;; Homeapage: or ;; URL: header, and the ideal would be to link to that with the label "Homepage" if it is present.

Since I have to deal with some related breakage anyway, I will try to look into that.

**Comment by purcell** [comment]
This got done recently, see #6914. :)
