### ISSUE TITLE
Package list panel to the top of the Melpa's homepage 

### ISSUE THREAD

**Issue by lyr3** [melpa/melpa#5322]
Could you guys get rid of this annoying huge panel: 

![panel](https://i.imgur.com/kPpJrN9.png)

> - Huge Melpa title
> - Info panel (pretty useless)
> - Current build panel should be on the page's menu

Thanks for the great work, anyway!

**Comment by purcell** [comment]
Thanks!

> Huge Melpa title

This is unlikely to change.

> Info panel (pretty useless)

For regular visitors, yes, but not for new users. I think it does a good job of summarising what MELPA's about. The panel could be made more compact though!

> Current build panel should be on the page's menu

Could you explain what you mean by "the page's menu" please?

I've noticed for myself that I routinely skip past the info panel to get to the search box, but I _do_ regularly look at the build status box, and the search box is still normally visible in the browser without scrolling, so I don't find this super problematic.

**Comment by lyr3** [comment]
Wow, Purcel...

hum hum...

Fair enough. Just some suggestions.


Page's menu:

![menu](https://i.imgur.com/bB7OM2f.png)

**Comment by purcell** [comment]
> It would be great if the current build is always visible as we scroll down the page!

Got it, thanks!

**Comment by tarsius** [comment]
> It would be great if the current build is always visible as we scroll down the page!

This sounds like change for its own sake.

You might come to the landing page because you
1. want to learn about Melpa,
2. want to browse the list of packages, or
3. need to figure out if/when a package was build.

I think what we currently have is the optimal compromize between these needs. I see no reason why it would be beneficial to keep the build status thingy always visible. Why would you scroll down doing (2) and then realize that you actually came to the page for (3)? And even if you did, why can't you just scroll to the top again? People who only came to the page to do (2) will however be distracted by the sticky build status.

I vote for leaving this as is.
