### ISSUE TITLE
Package org-fstree outdated

### ISSUE THREAD

**Issue by TobiasZawada** [melpa/melpa#5334]
The package org-fstree is outdated.

I just found the question https://emacs.stackexchange.com/questions/39087/error-with-org-fstree-symbols-function-definition-is-void-reduce#39087 that shows that there are serious problems with that package.

Since orgmode evolved very far since 2009 I doubt that the package works anymore. I cannot test that because I do not know what the package is supposed to do (the defuns in the package have no doc strings). But, there are also installation problems.

- `reduce` should be replaced by `cl-reduce`
- The order of `defconst org-fstree-heading-regexp` and `defun org-fstree-extract-path-from-headline` is wrong.
- There should be the magic comment `;;;###autoload` before the two hooks at the end of the library and before the definitions of the two hooked functions.
- There should be a `require` for `org-colview` or a `declare-function` for `org-columns-quit`.

Since the melpa version of the library is not equal to the version of the original author (comment at the end of that file) I don't know who actually maintains the package.
I cannot write a pull-request since the site that hosts the git-repro is strange to me.
I cannot make a promise that I cannot hold. Therefore I will not take on the maintenance of that package.

Notifying the melpa maintainers about the problem is all I can do at the moment.

With best regards,
Tobias Zawada

**Comment by aplaice** [comment]
Thanks for bringing this up! The comment at the end of the file is automatically added by the [MELPA build script](https://github.com/melpa/melpa/blob/e5cfaa4b5fda97054d45691fad9d79b559f2df14/package-build/package-build.el#L548), as is the `Package-Version:` header. (These are the only two differences, as shown by: `diff <( curl http://repo.or.cz/org-fstree.git/blob_plain/HEAD:/org-fstree.el ) <( curl https://melpa.org/packages/org-fstree-20090723.819.el )`, so the version distributed by MELPA is the one produced by the original author.)

An additional issue with the "strange" hosting site is that it doesn't support https (with in-chain certificates) and `org-fstree` is one of the three remaining recipes which fetch from unauthenticated upstreams (https://github.com/melpa/melpa/issues/3004). I've e-mailed the author of the package regarding this issue, but (unsurprisingly considering the time since the last issue and the fact they may have moved on) they haven't responded.

Considering that it might be worth either removing `org-fstree` from MELPA or (considering it's apparent popularity — 30,000 downloads) asking whether some user might wish to take over its maintenance (on [emacs-tangents](https://lists.gnu.org/archive/html/emacs-tangents/) perhaps (?)).

**Comment by tarsius** [comment]
I have now remove this package. See https://github.com/melpa/melpa/issues/3004#issuecomment-375910969.
