### ISSUE TITLE
glab: broken on melpa-stable

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#5337]
I don't quite understand the mechanism---certainly the recipe looks correct---or I'd fix it and send in a pr.

Ultimately, you can see the problem by going to the stable glab page (http://stable.melpa.org/#/glab), and hitting either the `Homepage` button, or the link next to `Source`.

@tarsius I think this has been broken since you updated the recipe 8 days ago...

**Comment by tarsius** [comment]
`glab.el` no longer is a modified copy of a very old version of `ghub.el`. Instead it is now implemented as a thin wrapper around a new version of `ghub.el`. I have not yet created new releases for `ghub` and `glab`, but expect to be doing it within the next two weeks.

I did not realize that this change would cause the latest tagged release to be removed Melpa, but since I am somewhat familiar with the code I should have. Sorry about that. I recommend you keep the installed version around and wait for the releases. If you would like help testing, then you could also install the new version before it is released. That would probably be a good idea since otherwise it's possible that `glab-2.0` will be releases without anyone every having used it.

**Comment by tarsius** [comment]
I have release v2, see https://emacsair.me/2018/03/20/ghub-2.0/.
