### ISSUE TITLE
Providing help

### ISSUE THREAD

**Issue by DamienCassou** [melpa/melpa#5345]
I think melpa is really important for the Emacs community. Can I help reviewing PRs? Is there any tool needed to facilitate auto-reviewing from PR authors?

**Comment by milkypostman** [comment]
that would be awesome! for the time being the proper procedure is probably
to provide the review -- provide comments in the PR -- and then those that
have merge permissions can commit the recipe.

**Comment by DamienCassou** [comment]
Donald Curtis <notifications@github.com> writes:
> that would be awesome! for the time being the proper procedure is probably
> to provide the review -- provide comments in the PR -- and then those that
> have merge permissions can commit the recipe.

are there any guidelines for reviews beyond CONTRIBUTING.md?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by milkypostman** [comment]
Yeah contributing.md is the best source

**Comment by DamienCassou** [comment]
Should we close PRs/Issues which are waiting for author feedback for
some period? E.g., 1 month.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tarsius** [comment]
> Should we close PRs/Issues which are waiting for author feedback for some period? E.g., 1 month.

I usually do it after about 3-6 months after pinging several times. By that point it is clear that the author either is really busy or won't be doing a good job as a maintainer. In both cases it doesn't make much sense to add the package, but just because someone is a bit busy for a while is not reason enough to close a pr.

I would however like it if we closed old issues more aggressively. I think many of the ancient issues are obsolete but only @purcell and @milkypostman know for sure, so they will have to do the work. I would also close many of the feature requests. If we haven't gotten around to implement those things for a few years, then we probably won't ever get around to do it.

**Comment by milkypostman** [comment]
3-6 mos is plenty of time. So I’m all for that. 

We may want to add a blurb in the docs for this.

**Comment by diasjorge** [comment]
Why not automate it with something like: https://probot.github.io/apps/stale/

**Comment by tarsius** [comment]
@DamienCassou Thanks for you help :wink: 

Ps: I have just done another round of closing old pull-requests.
