### ISSUE TITLE
Failed to download 'melpa' archive.

### ISSUE THREAD

**Issue by ShualLiu** [melpa/melpa#5381]
Today I use M-x package-list-packages to update archive. But I got the error below in the *Message* buffer.
```
Importing package-keyring.gpg...done
gnutls.el: (err=[-110] The TLS connection was non-properly terminated.) boot: (:priority NORMAL :hostname melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/ca-bundle.pem) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download ‘melpa’ archive.
Package refresh done
error in process sentinel: Error retrieving: http://elpa.gnu.org/packages/archive-contents "incomprehensible buffer" 
```
I think it's maybe a ca error... How Can I get the correct result?
#### My PC:
* OS: openSUSE Tumbleweed
* Emacs Version: 25.3.1
* Region: China
* Config: use [melpa config](https://melpa.org/#/getting-started)
* But it's ok using China Mirror.

**Comment by milkypostman** [comment]
It looks like both melpa and gnu repos has problems. If this has worked before I would suggest contacting whoever provides your internet service. I don’t have any experience personally with debugging these problems.  But it doesn’t seem melpa specific. 

You could try using non https temporarily just to see if that works. Otherwise maybe you need a newer version of emacs.

**Comment by ShualLiu** [comment]
@milkypostman Thanks, sir. Maybe it's my ISPs disturbed me.  When I use **China Telecom** to connect network, the problem happend again. But it will has  exactly the reverse effect when using **China Mobile**.

**Comment by purcell** [comment]
I think the China mirror of MELPA exists exactly because of this issue, so I'm not sure that there's an alternative solution we can offer, sorry.
