### ISSUE TITLE
Move Helm organization to Savannah / GitLab / NotABug?

### ISSUE THREAD

**Issue by Ambrevar** [melpa/melpa#5542]
The recent acquisition of GitHub might serve as a reminder that GitHub may not be an ideal platform for hosting free software projects, especially when GPL-licensed.

What do you people think about moving away from GitHub to more open platforms?

Also see other conversations:
- emacs-evil/evil-collection#141
- emacs-helm/helm#2054

**Comment by milkypostman** [comment]
I think I would probably just repeat everything said by @wasamasa if I tried to put in my opinion. 

You statement of “if we all move now, visibility will come along.” seems flawed to me simply because “we” don’t have critical mass. 

I do understand the point of view that “free” software should support free platforms and tools but we played that game and unfortunately the ability to pay developers to work on something drives the market. Right now github is frankly better than other tools. 

Ultimately acquisition has changed nothing and I don’t see any reason for Microsoft to change that given their support of VSCode and other open source projects.

**Comment by Ambrevar** [comment]
Well, someone has to take the first step, or there won't ever be critical mass.
Also mass helps with features and quality which would defeat the argument of GitHub being superior in quality.

Which does not mean that MELPA should move now in my opinion, but it's also nice to discuss it and spread the word.  I think it's a good thing to keep raising awareness towards the diversity of options that exist out there.

**Comment by purcell** [comment]
> Right now github is frankly better than other tools.

I agree with @milkypostman here. I'm pretty certain I wouldn't work on this project if I couldn't rely on the efficient workflow that Github currently allows. For example, it's so trivial for me to submit little changes to people's elisp libraries on github that I do it a lot. When code is hosted on gitlab, I simply don't do that, even though I have an account there. It's okay for us to maximise for current productivity, IMO, as long as we keep our options open for the long term.

**Comment by contrapunctus-1** [comment]
Would MELPA now be willing to move to GitLab or Gitea?
1. By now, GitLab/Gitea probably have all the features discussed above.
2. I know a number of contributors who are not willing to contribute to projects hosted on GitHub, MELPA included - who don't even want to maintain a GitHub account.

Alternatively, would MELPA be willing start a mailing list to which patches can be sent?

PS - please edit the issue title, since this issue is about MELPA and not Helm (?)

**Comment by wasamasa** [comment]
Another reason to switch over: https://github.blog/2022-05-04-software-security-starts-with-the-developer-securing-developer-accounts-with-2fa/
