### ISSUE TITLE
MELPA is broke.

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#5584]
So, if you build a package like `anti-zenburn-theme` and then you build `archive-contents`, and then you try to build the json it will fail with the error,

```
Wrong type argument: listp, "m00naticus@gmail.com"
make: *** [html/archive.json] Error 255
```

some recent change messed up the format of the `archive-contents` file so that emails are printed as,

```
(:authors ("Andrey Kotlarski" . "m00naticus@gmail.com"))
```

which the json encoder cannot handle. I am trying to figure out a quick fix for this so we can get unblocked but until then we are in a deep dark place and very broken.

**Comment by milkypostman** [comment]
i temporarily fixed this by not dumping extras in the entry file. this means that our `archive-contents` file will be missing the "extra" metadata we have been including.

I don't know how long this has been going on. it may be almost a month since we've actually updated any packages...

@tarsius we need to be more careful about testing things that change in `package-build.el`. while i very much appreciate all the hard work you've put into using some of more advanced eieio packages and such, i'm a bit worried because it's increasingly becoming a codebase i'm not very close to and have a hard time debugging.

**Comment by tarsius** [comment]
I think what changed is that  we updated Emacs on the server. That caused a different code-path in `package-build--package-buffer-info-vec` to be taken. This probably broke four years ago in https://github.com/melpa/package-build/commit/0fc03afcf07b0609327d092603093daa103ff1e8. But apparently that didn't matter because Melpa continued to use an old Emacs version and other callers did not try to turn the result into json.

This could be fixed by post-processing the value returned by `package-desc-extras` to something json can handle, maybe

    (:authors ("Andrey Kotlarski <m00naticus@gmail.com>"))

`:maintainer` would have to be modified accordingly.

Or we stop using `package-desc-extras` and instead always collect the information we care about ourselves (not just when using an old Emacs version).

**Comment by tarsius** [comment]
I've pushed a possible fix to https://github.com/melpa/package-build/compare/fix-5584?expand=1.

It's pretty late and the change is quite ugly, so don't merge just yet.

**Comment by milkypostman** [comment]
@tarsius are you going to work on fixing this or should I do something?

**Comment by tarsius** [comment]
The branch I mentioned above fixes the issue. (The commit message was wrong though and a second commit was needed to handle a (non-fatal) edge-case.) I'll open a pr.

**Comment by tarsius** [comment]
And that is merged now.
