### ISSUE TITLE
melpa.org: Versions no longer updating

### ISSUE THREAD

**Issue by cmccloud** [melpa/melpa#5662]
It seems melpa.org isn't pulling in the correct version for packages updated after the 27th. Links to outdated packages result in a 404, and obviously sorting by date gives incorrect results.

**Comment by milkypostman** [comment]
Could you please point to specific instances of problems?

We have made extensive changes to improve the stability of melpa but as with any software change it’s likely we introduced bugs. I’m happy to investigate these problems but I need a little guidance on where to look.

**Comment by cmccloud** [comment]
Sure, and thanks for the prompt response.

Go to https://melpa.org/#/?sort=version&asc=false and you'll notice that the latest package versions are from the 27th.

Take the eglot packge which should be the second most recent, for example. On melpa.org, its listed version is 20180727.906, and its link, https://melpa.org/packages/eglot-20180727.906.el gives a 404 error. 

From within emacs, melpa lists the latest version of eglot correctly as 20180730.2017, and installs and updates without issue. Melpa.org also serves https://melpa.org/packages/eglot-20180730.2017.el without issue, so it looks like maybe just the search page isn't updating correctly. 

Let me know if I've left anything unclear.

**Comment by alphapapa** [comment]
Yes, I just noticed that `magit-todos` hasn't been built since the 17th, but I pushed new commits yesterday.  And the MELPA homepage says:

> Next build: in an hour, last ended 14 minutes ago and took 2 hours

But 2 hours ago was on 1 August, and the latest package versions are from 27 July.

**Comment by milkypostman** [comment]
Well I’m guessing that something about JSON file generation is broke. Not easy for me to test right now but since emacs list is up to date I’m going to push this a bit and get to it on Friday. 

Sorry for the delay. 

If someone has time to debug we can push new versions to the server and fix the issue.

**Comment by greghendershott** [comment]
In case it helps to have another example with details, a few minutes ago someone on `#racket` IRC just told me:

> M-x package-install <RET> racket-mode
> leads to: package-install-from-archive: http://melpa.org/packages/faceup-20170925.1246.el: Not found

racket-mode.el has:

```elisp
;; Package-Requires: ((emacs "24.3") (faceup "0.0.2") (s "1.9.0"))
```

So IIUC it ought to be able to use the latest https://melpa.org/packages/faceup-20170925.1946.el.

**Comment by tarsius** [comment]
I was going to suggest reverting https://github.com/melpa/package-build/pull/21, at least temporarily, but I merged that ten days ago and data on the homepage didn't get stuck until six days ago. Still it might be related. The issue that https://github.com/melpa/package-build/pull/21 was supposed to fix was due to a different code-path being taken due to another Emacs version being used, and that causes an old bug to surface. At least that is what I concluded back then. While I did test this change I didn't test with a bunch of different Emacs versions. What version is Melpa using now? Did the version change when you switched servers and when did you switch?

**Comment by milkypostman** [comment]
Using whatever Debian unstable has.

**Comment by tarsius** [comment]
> Using whatever Debian unstable has.

24.5 https://packages.debian.org/stretch/emacs24

**Comment by tarsius** [comment]
> Using whatever Debian unstable has.

25.2 https://packages.debian.org/sid/emacs, which seem reasonable.

**Comment by milkypostman** [comment]
@greghendershott i think your problem may be syncing packages. i have looked and archive contents shows the correct version of faceup. my guess is that it updated and you haven't synced recently.

**Comment by milkypostman** [comment]
the problem with packages not updating json is that when we added back in the "metadata" for the packages, some of the old builds didn't have this data. so one of the entries in the `.entry` file was the new metadata and it was required. normally this would work itself out but some packages are not properly updating now.

for now the solution is to manually remove broken packages.

**Comment by milkypostman** [comment]
This has been fixed. Painstakingly :)

**Comment by greghendershott** [comment]
@milkypostman Thanks! Although this was a user of racket-mode, of course you're right, I should have thought to ask them to `M-x package-refresh-contents`; sorry for the noise.

**Comment by cmccloud** [comment]
@milkypostman Much appreciated. Thanks.
