### ISSUE TITLE
Invalid version list in archive contents

### ISSUE THREAD

**Issue by kmshanah** [melpa/melpa#5676]
When running package-list-packages (Centos 7.1, emacs 24.3.1) I have started getting the following error:

Invalid version list `(2018 -4 3 -4 21)'

This appears to be coming from the elscreen package entry in archive-contents.  This package hasn't been updated for quite a while, but this error just started showing up recently.  Has something gone wrong with extraction of the version from upstream when generating the archive contents?

Manually removing the '-4' entries from the version list above allows me to load the package list again.

**Comment by milkypostman** [comment]
this doesn't seem to be a problem in emacs 25.3.1 and i'm not sure why it's an issue. But i did open a package that had a dependency on a version `0.29-cvs` and `package.el` parsed it as `(0 29 -4)` which i suspect is just what `package.el` does. If this is a problem you may want to send an email to the emacs-devel mailing list but i suspect the best advice is to upgrade Emacs. Unfortunately we can't support all older versions (arguably 24 is not "old") but as of now we're relying on emacs 25. Likely the problem is that we recently upgraded the build server.

**Comment by kmshanah** [comment]
Interesting.  I just checked and in my Emacs 24, (version-to-list "2018-03-21") returns (2018 -3 3 -3 21), which the package-list-packages command is happy with, if I manually edit archive-contents and package-initialize.  So somewhere along the line, the dash "-" started getting parsed as -4 instead of -3?

**Comment by milkypostman** [comment]
`(version-to-list "2018-03-21")` parses to `(2018 -4 3 -4 21)`for me on 25

**Comment by milkypostman** [comment]
is there anything we could do to help or is it just that we are now incompatible with emacs? i have very little time to make major changes and given this is first we're hearing about it I don't feel like it must be impacting many people.

**Comment by kmshanah** [comment]
Alternatively, I could ask the elscreen author to change their version string from "2018-03-21" to "2018.03.21" or "20180321".  That would work.  That is the only package in the repo that is currently broken for Emacs 24.

**Comment by milkypostman** [comment]
Hrm. Is this on stable? Cause we generate versions for packages on the main melpa repo. 

I’m wondering if what you’re seeing isn’t a dependency on elscreen.

**Comment by kmshanah** [comment]
Yes, this is on stable.  The full entry looks like this (if I've got the right start/end position):

(elscreen . [(2018 -4 3 -4 21) ((emacs (24))) "Emacs window session manager" tar ((:commit . "02164afab2c5fbff6e4aa7c59e0daedc6c504772") (:keywords "window" "convenience") (:authors ("Naoto Morishima" . "naoto@morishima.net")) (:maintainer "Akinori MUSHA" . "knu@iDaemons.org") (:url . "https://github.com/knu/elscreen"))])

You can see the version string "2018-03-21" in the file here:
https://github.com/knu/elscreen/blob/master/elscreen.el

**Comment by milkypostman** [comment]
Yeah just ask them to tag a new version. That’d be easiest.

**Comment by kmshanah** [comment]
I expect this will fix it: https://github.com/knu/elscreen/pull/33

**Comment by mikedll** [comment]
I was getting this error on Windows 7 with Emacs 24 < 24.5. I upgraded to 24.5 and the issue went away.

**Comment by tarsius** [comment]
> I expect this will fix it: knu/elscreen#33

Or not, maybe we need to start looking for a new maintainer.

@knu's become the upstream in response to #2064. All they did (as far as I can tell) is that they merged a few outstanding pull-requests from the old upstream. The situation now is very similar, the "new" upstream mostly ignores the open issues.

**Comment by tarsius** [comment]
> Or not, maybe we need to start looking for a new maintainer.

Yep: https://github.com/knu/elscreen/issues/31.

**Comment by hajovonta** [comment]
This problem still persists, I happen to have 24.3.1 and it still comes up.

**Comment by purcell** [comment]
Is this still an issue?

**Comment by kmshanah** [comment]
Yes.  M-x package-list-packages still fails with: Invalid version list `(2018 -4 3 -4 21)'

**Comment by kmshanah** [comment]
The commit ID for elscreen in the archive-contents file is still "02164afab2c5fbff6e4aa7c59e0daedc6c504772", which does not include the fix for the version number (should be "cc58337faf5ba1eae7e87f75f6ff3758675688f2").

**Comment by milkypostman** [comment]
please verify in package-list-packages. it looks like there was a problem
because of timestamps and when the new version was merged.

**Comment by kmshanah** [comment]
Sorry, I don't understand what you're asking.
package-list-packages still gives me the error:  Invalid version list `(2018 -4 3 -4 21)'

**Comment by milkypostman** [comment]
The archive contents is updated to the commit that was referenced in the
comment here. It should have the fix after a manual rebuild. Did you JUST
sync with Melpa and got this error again?

**Comment by kmshanah** [comment]
Yes, I did.  This also shows the bad version string:

curl -s https://stable.melpa.org/packages/archive-contents | grep '^(elscreen '
(elscreen . [(2018 -4 3 -4 21) ((emacs (24))) "Emacs window session manager" tar ((:commit . "02164afab2c5fbff6e4aa7c59e0daedc6c504772") (:keywords "window" "convenience") (:authors ("Naoto Morishima" . "naoto@morishima.net")) (:maintainer "Akinori MUSHA" . "knu@iDaemons.org") (:url . "https://github.com/knu/elscreen"))])

**Comment by milkypostman** [comment]
as i said in https://github.com/melpa/melpa/issues/5676#issuecomment-411655450 the only way to fix this is to have them add a tag that is greater than the current tag.

Currently the tag is `2018-03-21` and that is the problem. We get the version number from `git tag` not from the header metadata.  The alternative, which I'd prefer to avoid, would be to add a `:version-regexp` to the recipe. The current version number is very non-standard since this is for *stable* we are typically looking for a release number, i.e., `1.0`. `2018-03-21` is not a valid version number as far as emacs is concerned so there isn't much to do here.

Suggestion is still to get @knu to tag a new version such as `20190501`. Melpa will pick this up automatically.

**Comment by knu** [comment]
OK, I've just added a tag `20180321` that matches the `Version` number.

**Comment by kmshanah** [comment]
Hey, that's worked - nice!
