### ISSUE TITLE
Should company-solidity still be a separate MELPA package from solidity-mode?

### ISSUE THREAD

**Issue by dcorking** [melpa/melpa#5762]
I am a bit confused by this commit 04296213 because it broke loading of solidity-mode _for me_, because I hadn't installed company-solidity from MELPA yet.

[When company-solidity moved into solidity-mode, ](https://github.com/ethereum/emacs-solidity/commit/1a9a7ad499e311af6f11b24a9de0accdc7ca2975#diff-4a03fbcb6037b028f195e05212c55976) they added this code that assumes company-solidity is present. 
```
;;; --- autcompletion back-end for company-mode, loads if company mode is installed ---
(when (require 'company nil 'noerror)
  (require 'company-solidity))
```

However as MELPA moves company-solidity.el into a separate package, this will error when company-solidity isn't installed. `File error: Cannot open load file, No such file or directory, company-solidity`

For now I can work around it by replacing above with
```
;;; --- autocompletion back-end for company-mode, installs if company mode is installed ---
(when (require 'company nil 'noerror)
  (package-install 'company-solidity))
```
which is a bit hackish and I am sure won't be accepted by the solidity-mode package author.

What is the best permanent solution that will stop other users getting errors?

@ssmolkin1 @tarsius @LefterisJP

**Comment by tarsius** [comment]
> I am a bit confused by this commit 0429621

That commit is broken, which makes it even more confusing. Later commits set the `:repo` to "ethereum/emacs-solidity" for both packages as intended, and add a missing parentheses.

> When company-solidity moved into solidity-mode, they added this code that assumes company-solidity is present.

They shouldn't have done that and possibly used this instead:

```
(require 'company-solidity nil t)
```

Or the could have left it to the user altogether. That would allow users to install `company-solidity` without actually using it.

Maintaining libraries like `company-solidity` in the "greater repository" is fine, but they should be split out into separate packages. This allows users who don't use `company` to forgo installing `company-<something>`. Actually this is possible here too because `company` is not specified as a dependency. However if it is not installed, then there will be many warnings when compiling `company-solidity.el`.

**Comment by dcorking** [comment]
Thanks; I'll make a PR upstream 😄 (Sorry I should have linked the full diff to show your repair commit 82931cd5e .)
