### ISSUE TITLE
cleaning up GitHub branches?

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#6107]
@tarsius can we delete the `debian` branch?

**Comment by tarsius** [comment]
I'll have a look soon at this and other old branches that I created and that are still laying around. I cannot do it on Github though because for some branches it claims that the it (a) has been merged into master and (b) is ahead of master. That can't be right...

**Comment by tarsius** [comment]
Ah, its because these branches were integrated into `master` using the "change the commit by changing the committer even though a fast-forward 'merge' would have been possible, needlessly making things more complicated" merge method. (That's one of the reasons I *never* merge using Github in my own projects.)

See #5822 for an example.

**Comment by tarsius** [comment]
I have deleted all "merged" branches, including some I was not involved in.

Three feature branches remain, all by me. I'll look at those at a later time. They are all in "maybe we shouldn't do that" limbo. I'll either delete or make an argument as to why we should do what those branches suggest should I decide I still think that's the way to go.
