### ISSUE TITLE
What is general strategy for multi files with multi dependency?

### ISSUE THREAD

**Issue by conao3** [melpa/melpa#6262]
CC: @akirak

Hi!
First, thank you for longtime maintenance for MELPA.

I found broken elisp package which is consist of multi files with each dependency.
This is https://github.com/akirak/org-starter especially `org-starter-swiper.el`.

I get below error when execute `make sandbox INSTALL=org-starter` at the root of the fork melpa/melpa.
```
^L
Compiling no file at Wed Jul  3 08:16:13 2019
Leaving directory ‘/Users/conao/dev/repos/melpa/sandbox/elpa/org-starter-20190701.427’
^L
Compiling file /Users/conao/dev/repos/melpa/sandbox/elpa/org-starter-20190701.427/org-starter-extras.el at Wed Jul  3 08:16:13 2019
Entering directory ‘/Users/conao/dev/repos/melpa/sandbox/elpa/org-starter-20190701.427/’
^L
Compiling file /Users/conao/dev/repos/melpa/sandbox/elpa/org-starter-20190701.427/org-starter-swiper.el at Wed Jul  3 08:16:13 2019
org-starter-swiper.el:35:1:Error: Cannot open load file: No such file or directory, swiper
^L
Compiling file /Users/conao/dev/repos/melpa/sandbox/elpa/org-starter-20190701.427/org-starter.el at Wed Jul  3 08:16:13 2019
```

`org-starter-swiper.el`'s header is below
```
;;; org-starter-swiper.el --- Swiper for org-starter -*- lexical-binding: t -*-

;; Copyright (C) 2019 Akira Komamura

;; Author: Akira Komamura <akira.komamura@gmail.com>
;; Version: 0.1
;; Package-Requires: ((emacs "25.1") (swiper "0.11"))
;; URL: https://github.com/akirak/org-starter
```
but MELPA parses dependency as below cited from https://melpa.org/#/org-starter
```
Downloads  269 (all versions), percentile: 15.06
Source  github (commit 60ccfd)
Dependencies  dash 2.12 / dash-functional 1.2.0 / emacs 25.1
Needed by
```

So, he and we should describe all dependency in main elisp file only?
Or MELPA plans to crawl all elisp files and gather dependencies in the future?
It seems that it related to #1307

**Comment by purcell** [comment]
MELPA only looks at the main `.el` file (or `-pkg.el` file, if provided, though we discourage that). If you have different optional parts of a large package, each of which has different dependencies, then these should really be published as separate packages. Otherwise, the only correct way to do things is to add all of the package dependencies to the main `.el` file, but that means that users will often have unwanted packages installed.

In the case of `org-starter-swiper`, the helm, counsel and swiper files should each be packaged separately, and each should depend on `org-starter`. So you'd change the `org-starter` recipe to include `org-starter.el` and `org-starter-extras.el` (listing all the dependencies in `org-starter.el`), and then you'd submit 3 additional recipes, each listing one of the other files.

**Comment by conao3** [comment]
Thanks for your quick response!

I understand now.
Actually, I was confused about how to describe it before. This information is very useful. I will send a PR to edit contributing.org, so I hope you are considering merging.

**Comment by akirak** [comment]
Thank you for reporting this. I knew I had to update the recipe for org-starter, but I forgot it. I'll submit an updated recipe soon.

@purcell Your explanation made the situation clear. Thank you.

**Comment by conao3** [comment]
@purcell, I have 1 question.
> MELPA only looks at the main .el file

How does MELPA find **main** .el file?

**Comment by conao3** [comment]
Now I found the code!
Using `recipe-name`.el as the main .el file.
