### ISSUE TITLE
Maintainance of packages by ShingoFukuyama

### ISSUE THREAD

**Issue by cireu** [melpa/melpa#6347]
It seems that the author and maintainer of [helm-swoop](https://github.com/ShingoFukuyama/helm-swoop) disappeared since last commit in Feb 2018.

Now the package has some bugs and conflicts with its dependency [helm](https://github.com/emacs-helm/helm) https://github.com/ShingoFukuyama/helm-swoop/issues/133 https://github.com/ShingoFukuyama/helm-swoop/issues/123.

And the only way to contact with author I found is twitter, personally I don't use twitter at all.

I create my fork of [this](https://github.com/cireu/helm-swoop) and fix some issues, what should I do if I want to help maintain this package?

**Comment by tarsius** [comment]
This is also being discussed on `helm-swoop`'s issue tracker at https://github.com/ShingoFukuyama/helm-swoop/issues/143.

**Comment by cireu** [comment]
@JesusMtnez What's your opinion?

**Comment by conao3** [comment]
CC: @alphapapa, @purcell 

[ov.el](https://github.com/ShingoFukuyama/ov.el) has same issue see https://github.com/ShingoFukuyama/ov.el/pull/15 and https://github.com/ShingoFukuyama/ov.el/issues/14 .
I try to contact via Issue mention, Twitter DM, E-mail, mention in Slack in Japanese community but he never responded.
It seems he exited Emacs community and all his repositories are abandoned.

There is all package list he created.

Name | DL count | Last updated
------------ | --------- | ----
[helm-swoop](https://github.com/ShingoFukuyama/helm-swoop) | 337,785 | 20180215
[helm-css-scss](https://github.com/ShingoFukuyama/helm-css-scss) | 111,128 | 20140627
[ov](https://github.com/ShingoFukuyama/ov.el) | 44,081 | 20150312
[swoop](https://github.com/ShingoFukuyama/emacs-swoop) | 3,616 | 20160120
[manage-minor-mode](https://github.com/ShingoFukuyama/manage-minor-mode) | 1,657 | 20140310
[readability](https://github.com/ShingoFukuyama/emacs-readability) | 638 | 20140716

I've already created a fork for all of them and be ready for ongoing maintenance.
If possible, change their recipe to my forks.
If you don't trust me to do ongoing maintenance, I can create forks under the control of [Emacs-JP](https://github.com/emacs-jp).

**Comment by JesusMtnez** [comment]
> @JesusMtnez What's your opinion?

I haven't received a response from @ShingoFukuyama yet. It seems he is no longer maintaining them. I think it is a good solution forking them and keep updating the packages. Let me know if I could help maintaining them, specially `helm-swoop`.

Which would be the official forks then?

**Comment by conao3** [comment]
I plan to create new organization. Famous and useful packages should be maintain well.

It is a problem that packages that are indispensable for using Emacs are not even merged despite the presence of PR. It is reasonable to create a new organization to make it clear that multiple people have the authority to manage and manage the *orphaned* packages there.

**Comment by JesusMtnez** [comment]
Sounds like a really good idea! Thank you @conao3
Please, count me in to help as co-organizer / maintainer :smile:

**Comment by conao3** [comment]
I think all of the packages he created is going to list in https://emacsmirror.net/stats/emacsorphanage.html#org22ec261 .
But https://github.com/emacsorphanage is an organization to which the only @tarsius belongs.
I think that @tarsius already manage many large and useful packages, I would like to contribute to that orphaned packages maintain, not impose a job. To that end, I think a new organization should be created and the packages maintained by the community

**Comment by cireu** [comment]
@conao3 count me too, plz. I'm interested in taking part in maintainance of helm-swoop

**Comment by alphapapa** [comment]
I still have `helm-swoop` installed, but I don't use it often.

I submitted one of the PRs to `ov` that hasn't been merged.  I'd be glad to help maintain `ov`.

**Comment by tarsius** [comment]
It's great that multiple users want to help maintain this. In light of this it would be best to move the package to some organization instead of to a personal account. Emacs-JP doesn't seem like the appropriate organization in this case. I suggest the [Emacs Orphanage](https://github.com/emacsorphanage), which I created exactly for situations like this (among other things).

**Comment by conao3** [comment]
Great. How do you operate the organization? Only @tarsius belongs to the organization and has the only push right, we make a proposal in PR?
Or would you allow us to join the organization and actively engage in maintenance?

**Comment by tarsius** [comment]
I'll create the repositories and then give the three of you admin rights for just those repositories.

It would be best if @ShingoFukuyama could transfer the repositories to the `emacsorphanage` organization. That way issues, pull-requests and other information would be preserved. I'll contact him again on twitter.

**Comment by conao3** [comment]
Sounds nice! And contact him again is very an important point. Thanks.

**Comment by ShingoFukuyama** [comment]
@cireu @conao3 @JesusMtnez @alphapapa Sorry for not responding even though you contacted me several times, I only open Twitter sometimes lately.
@tarsius Thank you for letting me know about this page. I'd like to transfer `helm-swoop` and `ov.el` to `emacsorphanage`.

**Comment by tarsius** [comment]
> so please kindly accept them if you got emails.

Did you already initiate the transfer? I checked my email and haven't received anything yet. According to the [documentation](https://help.github.com/en/articles/transferring-a-repository#about-repository-transfers) the "new owner" is informed by email. Unfortunately it does not say what email address is used when the owner is a organization, not a user account. As far as I can tell three email addresses are associated with the `emacsorphanage` organization. In the interface these fields are named:

1. Email (will be public)
2. Billing email (Private)
3. Gravatar email (Private)

I would expect the message to be send to (2) but have not received anything there yet. (1) is empty and (3) I no longer have access too. I forgot to renew emacsmirror.org and lost it to a domain squatter years ago. I just checked again and they have finally given up! I own the domain again. Now I have to setup an MX record and in 24 to 48 hours I should be able to receive email.

By that time the invitations will have timed out, so please stick around and I will tell you when I am ready to receive the emails so that you can initiate the transfers again. Or you could just transfer to my personal account (`tarsius`) and I then transfer from there to `emacsorphanage`.

> I'd like to transfer `helm-swoop` and `ov.el`

What about the others? Are you still maintaining those?

**Comment by ShingoFukuyama** [comment]
Looks like my transfers failed with this error "You don't have the permission to create repositories on emacsorphanage"

I found another documentation.
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

It says "Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own.".

So, could you give me the permission until complete the transferring process?

I appreciate it if you accept other repositories.

**Comment by tarsius** [comment]
> It says "Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own.".

That's how I remembered it too and I was pleasantly surprised they "changed it". Turns out they only changed the documentation, not the actual functionality. :frowning_face: 

> So, could you give me the permission until complete the transferring process?

I have just invited you as a "member" of `emacsorphanage`. After accepting you should be able to transfer repositories in. (You are also able to create new repositories and view information about other members including "private" members. You shouldn't have any other permissions.)

If this works, then I will document what I did.

**Comment by tarsius** [comment]
> I appreciate it if you accept other repositories.

Feel free to transfer the other packages too.

Out of curiosity; did you stop using Emacs or just don't have the time to maintain these packages anymore? Do you have any intention of coming back at a later time and maintain or at least contribute to these packages again?

**Comment by ShingoFukuyama** [comment]
@conao3 Oh, I overlooked your comment.
Thank you for your kind suggestion that I couldn't come up with.
I would love to try the option if they agree.

**Comment by cireu** [comment]
> I would love to try the option if they agree.

I'm OK with it.

**Comment by ShingoFukuyama** [comment]
@tarsius Thank you for inviting me, but on second thought, @conao3's suggestion would be nice.

> Out of curiosity; did you stop using Emacs or just don't have the time to maintain these packages anymore? Do you have any intention of coming back at a later time and maintain or at least contribute to these packages again?

I'm currently working as an iOS app developer, so mainly using Xcode. But also using Emacs on a daily basis just for memo, some text manipulations, magit, dired, etc. Even though I created some Emacs Lisp packages before, I rarely use them recently...

And I'm just lazy enough to not checking GitHub or Slack notifications. It might be a good opportunity to change my habit.

**Comment by milkypostman** [comment]
I would strongly suggest if you’re happy with collaborators that you create
an organization and invite people as collaborators. This will alleviate
some of the necessity to stay vigilant on notifications and removes your
name from the package directly.

**Comment by conao3** [comment]
Wait. Why do you want to remove @ShingoFukuyama's name from the package?
As I am not an English native, I may misunderstand your message meanings but I don't think he needs to remove his name from the package.

For Emacs community and for MELPA, where the repository is placed has no direct meaning. If that is the case, it is natural to place it under the original author, and there should be no reasonable reason to create an organization and move the repository or transfer repository.

If the author invites us as collaborators, the original purpose will be achieved without any excess or deficiency. Am I wrong?
If we are *watch* the repository, we will be notified of the same kind as the regular repository.

Once more. I was thinking of maintaining these packages temporarily in a different location, but then returning the recipe to the original location when the author returns. Our goal should not be to take away this repository from him.

**Comment by milkypostman** [comment]
it just shows less ownership or responsibility. that was partially the
reason that i transferred the melpa repository to the melpa organization a
long time ago. it's really maintained by a community now and not just me
and even though i had a large influence and impact on getting it going,
it's much larger than me now.

**Comment by ShingoFukuyama** [comment]
I don't mind removing my name from the packages, and @milkypostman's suggestion is also reasonable.
But I guess my repositories are not so big enough to create another organization.

**Comment by cireu** [comment]
Melpa is a big project, ShigoFukuyama's contribution just some elisp libraries, It maybe unecessary to create a single orgnization in my opinion.

I suggest ShingoFukuyama add us as collaborator and add `Maintainer: somebody` at header of all his work. It's convenience(no need to change recipe and transfer repo) and I' sure that ShingoFukuyama won't be disturbed if user can find a maintainer.

**Comment by alphapapa** [comment]
@ShingoFukuyama There's no greater compliment for a creator than for his work to outlive his own interest in it.  :)  Thanks for your work on these packages.

**Comment by cireu** [comment]
So what's the conclusion?

**Comment by tarsius** [comment]
> Melpa is a big project, ShigoFukuyama's contribution just some elisp libraries, It maybe unecessary to create a single orgnization in my opinion.

That's why I still think moving the repositories to the Emacsorphanage would be a good idea. A single organization where multiple authors can drop of their creations.

**Comment by conao3** [comment]
If you are attempt to transfer to Emacsorphanage, add us to Emacsorphanage and give us an opportunity to show other people that we are managing packages belonging to Emacsorphanage. This is not an essential issue, but it does motivate us.

I don't think it's a good situation to have someone who is not part of organization effectively managing the repositories that belong to that organization. (same MELPA does.)

**Comment by conao3** [comment]
Anyone who participates in this thread is prepared and motivated to be a *parent*.

**Comment by tarsius** [comment]
I don't intend to give everyone who is offering to maintain some package which might be added to the organization access to *all* repositories of the organization. The sequence of events and extend of permissions I had in mind is this:

1. @ShingoFukuyama transfers some or all of his packages to the `emacsorphanage`.
2. I ask all of you to again state in unambiguous term which of these repositories each one of you wants to maintain.
3. I invite each of the volunteers to become a "member" (not "owner") of the organization.

   * I would like to encourage you to make your membership public, so that visitors can see it here: https://github.com/emacsorphanage/people.
   * Even if you don't make it public it will still say "Member" at the top of each post that you make on an issue belonging to a repository of the organization.
   * Most other organization-wide permissions that can be granted to organization members I *won't* grant to any of you.
   * One exception will be "create new repositories", which is necessary to transfer repositories into the organization.

4. You accept the invitation.
5. I give you "admin" rights for the repositories that you have volunteered to maintain.
6. You can start maintaining the package(s) and users will be able to see that you are a maintainer.

Currently @purcell is the only organization member beside myself. He did not make his membership public and as far as I remember did never actually perform any action that required membership permissions. If he agrees I can promote him to become co-owner beside myself, thereby reducing the bus-factor.

Most of this I had already stated before just less explicitly.

> I don't think it's a good situation to have someone who is not part of organization effectively managing the repositories that belong to that organization. (same MELPA does.)

I believe I have no described how the new maintainers "officially" and visibly become the maintainers aka "members". Does this satisfy your concerns?

(As far as Melpa goes: I also think it would be better if @riscy were invited to become a Melpa member and then made his membership public.)

**Comment by cireu** [comment]
Thanks for your detailed description, in fact I don't know anything about Github's permission control before @tarsius

**Comment by conao3** [comment]
You said 4 days ago in https://github.com/melpa/melpa/issues/6347#issuecomment-518609998
> I'll create the repositories and then give the three of you admin rights for just those repositories.

I understood that @tarsius make us a collaborator for those packages, but not members of the organization from *"give the three of you admin rights for just those repositories"*.
However, it turned out that the understanding was wrong. I apologize.

**Comment by tarsius** [comment]
No need to apologize. My statements weren't clear enough.

**Comment by conao3** [comment]
Thanks @tarsius.
Finally, how this issue solve to depends on @ShingoFukuyama. Any decisions are welcome for me.

**Comment by jjzmajic** [comment]
Sorry if I'm being ignorant, but I thought swoop was largely made superfluous by the recent upgrades to the built-in helm-occur? I could be wrong though

**Comment by tarsius** [comment]
@jjzmajic Let's talk about this later. This is off-topic as far as this conversation goes.

**Comment by ShingoFukuyama** [comment]
My decision is to transfer all elisp repositories to emacsorphanage. 
Thank you all for taking time to discuss about it. 
I'm glad someone still interested in some of the repositories.

**Comment by cireu** [comment]
Now ShingoFukuyama transfer all his package to emacsorphange.

I'd like to help maintain `helm-swoop`, but I may be not familiar with other packages.

**Comment by tarsius** [comment]
I have updated Melpa and the Emacsmirror to get the packages from the Emacsorphanage. I have added @cireu and @conao3 as maintainers of `helm-swoop`. Tell me what other packages you want to maintain. @conao3 mentioned having forks of all packages--do you intend to maintain them all? I have also invited @alphapapa and intend to add him to `ov` once he accepts.

**Comment by alphapapa** [comment]
@tarsius Accepted, thank you.

**Comment by conao3** [comment]
Yes, I intend to maintain his all packages. And in the future, I intend to maintain more packages.
I want to contribute the Emacs community by contributing emacsorphanage activity.

**Comment by tarsius** [comment]
> Yes, I intend to maintain his all packages. And in the future, I intend to maintain more packages.
I want to contribute the Emacs community by contributing emacsorphanage activity.

Great thanks for doing that!

**Comment by tarsius** [comment]
I've added you two as maintainers of the requested repository/-ies.

**Comment by alphapapa** [comment]
For future reference, is there an easy to find out who has commit rights on a repo?  I'd like to know exactly who I'm collaborating with so we can coordinate.  I can't find any such list on the `ov` repo's pages.

**Comment by tarsius** [comment]
> Could the "teams" feature be used to put people in teams for certain repos?

That would work. (I had the same idea, just didn't put into action yet.) It's slightly more work for me, but not much.

**Comment by alphapapa** [comment]
BTW, I just noticed the Emacs Orphanage...logo.  That's kind of funny and terrifying at the same time.  :D

**Comment by tarsius** [comment]
Finally... took years for someone to mention that.

**Comment by tarsius** [comment]
For context also see the Emacsmirror and Emacsattic logos.

**Comment by alphapapa** [comment]
> Finally... took years for someone to mention that.

LOL  :)

> For context also see the Emacsmirror and Emacsattic logos.

Cute and brutal, respectively.

It takes a substantial sense of humor to accomplish all that you have in Emacsland.  :)
