### ISSUE TITLE
incomplete test of gnutls-available-p in example code to add to .emacs

### ISSUE THREAD

**Issue by young-git2046** [melpa/melpa#6430]
On https://melpa.org/#/getting-started, the code displayed to show how to enable package installation via Melpa incompletely tests gnutls-available-p. The code reads:

```elisp
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
       ...)
```

On a machine not running Windows-NT or MS-DOS and where gnutls is not installed, this code leads to no-ssl to be set, incorrectly I think, to "https".

**Comment by tarsius** [comment]
Did you actually run into an issue, which you then fixed by making the implied change?

I was unable to find an explanation about this but believe the reasoning behind the existing code is something like this:

* Emacs can use either gnutls or if that is unavailable then some other ssl implementation.
* That does not apply to Windows, where gnutls is the only option available.

So I believe this code is correct, but have not actually proven it.

I am closing this. We can deal with this if it turns out that there actually is a problem.
