### ISSUE TITLE
maintenance of highlight.el

### ISSUE THREAD

**Issue by steckerhalter** [melpa/melpa#6436]
Hi. I haven't updated `highlight.el` by Drew Adams from emacswiki in quite a while and I think I'd like to withdraw from this job. I'm talking about this recipe: https://github.com/melpa/melpa/blob/master/recipes/highlight

So maybe you can find someone else to maintain a git copy or else remove the package since it's not properly updated anymore?

Thanks

**Comment by tarsius** [comment]
Could you please post links to the discussions we had about you proxy-maintain this? I vaguely remember that this was done because some non-emacswiki on Melpa depended on this emacswiki package.

And the alternative would have been to drop those other packages. We might end up going that way instead. In which case it would be good if affected users could easily find the related discussions.

**Comment by steckerhalter** [comment]
it started here: https://github.com/melpa/melpa/pull/5008#issuecomment-360103510
I don't use melpa so for me it's not really an issue. I have just opened this ticket to let you know that I don't intend to update `highlight.el` anymore.

**Comment by steckerhalter** [comment]
Thanks
