### ISSUE TITLE
update applescript-mode master

### ISSUE THREAD

**Issue by jdtsmith** [melpa/melpa#6552]
An improved and somewhat more recent version of applescript-mode is https://github.com/kalifg/applescript-mode.  Should probably replace the very old version Melpa references.

**Comment by tarsius** [comment]
@jdtsmith also brought that up at https://github.com/ieure/applescript-mode/pull/1.

@ieure already replied, stating that he would be happy to transfer ownership to someone else.

@kalifg hasn't replied yet and we cannot assume that he is interested in maintaining this. He submitted a few "Bug fixes and new features" *seven years* ago and hasn't made any other changes since. He also made no effort to get his changes merged after initially creating the pull-request. Which is perfectly fine, but lacks the kind of enthusiasm I would like to see in a maintainer.

http://www.melpa.org lists a few reasons for why it is great. Among this is:

> Curated - no obsolete, renamed, forked or randomly hacked packages

Frankly I think every adjective except *curated* (and possibly *randomly* (though that is an adverb)) in there is already... not the whole truth. Never-the-less we cannot make some fork the new upstream just because it happens to have a handful of additional commits. A maintainer is someone who not only happened to scratch his own itch a few years back but who is also willing to work with other contributors to get their changes merged and who is willing to work on bugs and help users.

@purcell We should think about how we want to handle such issues and document it. We shouldn't setup some rigid rules, but we should make it more predictable how we will act.

Lately what we have been doing in such cases is to have the former maintainer transfer the repository to the [`emacsorphanage`](https://github.com/emacsorphanage) organization, which is owned by me. I then give the new maintainers the appropriate permissions, but "ownership" remains with me.

Actually @purcell is also an "owner" or `emacsorphanage`, but I don't remember him ever actually performing an action that would require such permissions. Never-the-less, since this has started to come up in the context of Melpa, I think you should make your status public, making the relationship between the two accounts more obvious.

The orphanage is also used for packages that aren't even on Melpa, so I'll have to write some text about the various purposes it serves. Currently we have https://emacsmirror.net/stats/emacsorphanage.html and on https://emacsmirror.net:

> If other mirrored packages still depend on a package whose upstream has disappeared or no longer maintains the package, then it is copied to the Emacsorphanage. The Emacsmirror then mirrors that repository from the orphanage. The orphanage repository serves as a temporary home until someone volunteers to take over as maintainer. While a package is in the orphanage, the maintainer of the Emacsmirror makes an effort to merge pull requests from users.

**Comment by kalifg** [comment]
Sorry I was slow to reply on ieure/applescript-mode#1.  I just haven't been online for the last 14 hours.

> He submitted a few "Bug fixes and new features" seven years ago and hasn't made any other changes since.

It's a really simple, niche piece of code and after a few fixes it has just worked.  I don't use it that often but I'm not sure anyone does.   If they do they haven't submitted any PRs.  If they fit your idea of a maintainer better they are welcome to it.

> He also made no effort to get his changes merged after initially creating the pull-request

It's not my habit to be pushy about having PRs merged.  I expect if it was useful to the author or someone else it will get merged; if not I don't need it merged to use it myself. 

> is also willing to work with other contributors to get their changes merged and who is willing to work on bugs and help users

I'm willing.  I've just never seen any traffic like that in regards to this repo.  

You're clearly very passionate about the quality of MELPA, which is great!  I don't think forking is necessary.  I think that merging of that single PR (whether by @ieure, myself, you or whoever he transfers ownership to) should address this issue.

**Comment by tarsius** [comment]
@kalifg Just to make sure: I wasn't trying to suggest you should already have responded by the time I wrote the above or that you would not be qualified. The point I was trying to make was that you might simply not be interested in doing so. *And* I was using this particular package and you as potential new maintainer as a handy *example*, because as I mentioned, we get requests like this quite often.

But back to this particular package.

> You're clearly very passionate about the quality of MELPA, which is great! I don't think forking is necessary. I think that merging of that single PR (whether by @ieure, myself, you or whoever he transfers ownership to) should address this issue.

Yes, in this case simply merging this after a review seems to be the best/simplest solution.

**Comment by kalifg** [comment]
Cool, thanks for the explanation!  That makes more sense now; it was an oddly complex comment to see in regards to this little emacs mode. :)  The bigger picture is clearer to me now and I'm sorry I came off so defensive.

**Comment by jdtsmith** [comment]
@ieure mentioned they are no longer on a Mac, so by that argument @kalifg would likely be a better maintainer match even if his interest was only minimal.  

I do quite like the idea of the "orphanage", especially if the orphanage maintainer took on the role of "being pushy", which is a hard thing to do when you are taking advantage of someone else's contributed labor!  I presume there is no equivalent for Emacs-included packages (of which I have a fairly orphaned major mode :/ ).  BTW, I'd use AppleScript-mode no more than once or twice a year, which I'd guess is typical usage.  

My latest script I used it to help develop is however very highly useful to me:

```AppleScript
#!/usr/bin/env osascript
-- pages2pdf: Creates a PDF file /path/to/filename.pdf from one or more Pages documents,
-- passed as arguments
on run argv
	set AppleScript's text item delimiters to {"."}
	repeat with theFile in argv
	       set fullFile to do shell script "realpath " & the quoted form of theFile
	       log "Processing " & theFile
	       set theExt to last text item of theFile
	       tell application "Pages"
			set theDoc to open fullFile
			set pdfFile to (text 1 through ((count of fullFile) - ¬
			    (count of theExt)) of fullFile) & "pdf"
			export theDoc as PDF to POSIX file pdfFile
		       	close theDoc
	       end tell
	end repeat
end run
```

**Comment by tarsius** [comment]
Ah right... yes migrating to the orphanage would make sense then.

@ieure This is how it would work. I make you a member of the `emacsorphanage`, so that you can transfer your repository there. You do so and I then revoke your membership.

We probably don't even need a maintainer beyond what I provide as the maintainer of the complete organization. I would appreciate your (@jdtsmith) support reviewing the current pull-request thought.

**Comment by jdtsmith** [comment]
I tried out @kalifg's PR, and other than the naming convention issues you noticed, found nothing amiss.  I did not try out the compile/decompile however.

**Comment by tarsius** [comment]
> @ieure This is how it would work. I make you a member of the `emacsorphanage`, so that you can transfer your repository there. You do so and I then revoke your membership.

Friendly ping! @ieure should we proceed like this? I've already made you a temporary member to speed this up a bit.

**Comment by ieure** [comment]
> > @ieure This is how it would work. I make you a member of the `emacsorphanage`, so that you can transfer your repository there. You do so and I then revoke your membership.
> 
> Friendly ping! @ieure should we proceed like this? I've already made you a temporary member to speed this up a bit.

This is fine with me.  I tried transferring ownership, but:

> You don’t have the permission to create public repositories on emacsorphanage

And I don't see myself in https://github.com/orgs/emacsorphanage/people

**Comment by ieure** [comment]
Got the org invite earlier today, just transferred ownership.  Goodnight, sweet prince.

**Comment by tarsius** [comment]
Great thanks!

Do you want to keep write access to this repository or should I remove you again?

**Comment by tarsius** [comment]
@kalifg please open your pull-request in https://github.com/emacsorphanage/applescript-mode now.
