### ISSUE TITLE
matlab in MELPA, configuration? matlab-mode-pkg.el enough?

### ISSUE THREAD

**Issue by ouboub** [melpa/melpa#6626]
Hello

I am maintaining (but not really developing, more testing) matlab-mode for Emacs. 
There are two repositories we use:
 the original one is in sourceforge and a mirror in github.
I do remember that, around 3 years ago I added the following 
matlab-mode-pkg.el file to the repository:

```
  (define-package "matlab-mode" "3.3.5" "Major mode for MATLAB(R) dot-m files"
  'nil
  :keywords
  '("matlab" "programming" "language" "(X)emacs")
  :url "http://sourceforge.net/projects/matlab-emacs/"
  )
```

and indeed then it appears in MELPA. Now it was pointed out to me, that the MELPA repository 
misses some important subdirectories, especially toolbox/+emacs
I really don't remember all the syntax details, so
can I just stick with this pkg file or do I need now to add a directory recipies and change the syntax 
according to the instructions in 
https://github.com/melpa/melpa?
I just checked the recipe file in 
https://github.com/melpa/melpa/blob/master/recipes/matlab-mode
is not correct, but should be enhanced. 
It is not clear to me, how to do that. 
Any pointers?

thanks and regards
Uwe Brauer

**Comment by ouboub** [comment]
Here is a patch, which should solve the problem
[matlab-recip-patch.txt](https://github.com/melpa/melpa/files/4025565/matlab-recip-patch.txt)

**Comment by tarsius** [comment]
Please provide that as a pull-request. When you do so, split the edited line into multiple lines; it's getting a bit long.

Doing this will also allow you to test the result and fix issues, if any. Build the package and look at the result (using e.g. `tar -tf FILE | sort`). Repeat that until you get the result you wanted.

Both of these steps are documented at https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#preparing-a-pull-request-to-melpa.

**Comment by ouboub** [comment]
Hi
First I have to say that I think I am acquainted with VC systems (mostly mercurial and a bit of git).
I just want to provide a patch of a couple of lines, usually I would either send a patch or push it myself.
You require a more complicated process and unfortunately I got stuck:
I did change the recipe and run a test, it works finally.
I forked melpa to my account.
I created a branch matlab-recipe and pushed it to my personal fork, but the when trying to create a 
pull request, since there are THREE buttons, I attach the screenshot, please tell me what to do.
Frankly the complexity of the process compared to the size of the patch is a bit discouraging
![pull-request](https://user-images.githubusercontent.com/5957203/72202240-3be9c380-345d-11ea-83ee-fd5b38af298c.png)

**Comment by tarsius** [comment]
If it is only a short while since you pushed a new branch, then a yellow notification like thingy is shown. In this case it reads `ouboub:matlab-recipe (3 minutes ago) [Compare & pull request]`. Click on the `[Compare & pull request]` button. From that point on its about the same as opening a new issue.

However, since it has been three hours since you posted the above screenshot, that helpful notification probably isn't being displayed anymore. So you have to do it the hard way.

Click on `Pull requests` next to the `Code` tab. On the next page click on `[New pull request]`. On the next page, right below the heading `Compare changes`, there are two pull-downs. Leave the left one at `master` and change the right one to `ouboub:matlab-recipe`. Now you should be able to click on `[Create new request]`. Now you should be able to provide some information about your changes, the fields probably are already filled with the commit message. Finally click on `[Create pull request]` below the text field.

**Comment by ouboub** [comment]
I still don't understand. There is/was which reads compare & and pull request, this one I should have used, but now it is gone (not really convient, I must say).
Then there is a button below Branch: master New pull request,
This one is should **not ** use, is this correct (who the heck wrote that interface)
so I should use the one in the first line which reads
code <> |issues 55|pull requests 50|

is this correct?
who the heck wrote that interface, and all this procdure, just for a patch of 4 lines.
sorry I am sure you have your reasons

**Comment by tarsius** [comment]
> Then there is a button below Branch: master New pull request,
> This one is should **not ** use, is this correct 

I forgot about that one. No, these two buttons are actually equivalent:

1. While on https://github.com/melpa/melpa click on `New pull request`.
2. While on https://github.com/melpa/melpa click on `Pull requests` (next to `Issues` and `Actions`) to go to https://github.com/melpa/melpa/pulls, and then on that second page click on `New pull request`.

After doing either of these two things you land on the same page (https://github.com/melpa/melpa/compare). How to proceed on that page I have described above.

**Comment by ouboub** [comment]
ok, thanks, I did this, hopefully now everything is ok

**Comment by tarsius** [comment]
I've merged #6632. Thanks!

**Comment by ouboub** [comment]
good, last question for future contributions:
would it be ok, if my branch contained various commits?
I am asking this because there are maintainer, who think that branch for a short fix, should only contain one commit and who refused my patches because of this very reason.
what is your attitude?

**Comment by tarsius** [comment]
It depends.

In this repository most pull-requests are about adding a recipe for a new package. In most cases there should be one package per pull-request and that package should be added in a single commit.

So if you have written two new and completely unrelated packages, then you should create two separate pull-requests too. If you used a single pull-request instead then it could happen that a recipe that we consider ready to be merged does *not* get merged because we do not think the same about the other recipe in the pull-request. That can lead to unnecessary delays that are several weeks long.

Also there should be just one commit. For example you may push a first version of the recipe and then continues integration points out that there is something wrong. Often contributors then fix that and push a second commit for that with a summary such as "Fix mistake in foobar recipe". Don't do that, just squash the fix into the original commit and force-push.

But that is just what we like in this repository. Other repositories are very different and whether to use a single or multiple commits very much depends on the specific. So my recommendation is...

> who refused my patches because of this very reason.

... that once the maintainers tell you how they like the pull-requests, you do that.

**Comment by ouboub** [comment]
> Also there should be just one commit. For example you may push a first version of the recipe and >hen continues integration points out that there is something wrong. Often contributors then fix that and >push a second commit for that with a summary such as "Fix mistake in foobar recipe". Don't do that, j>ust squash the fix into the original commit and force-push.

this is what I meant. Ok understood.

which is different of the current situation, because the orginal recipe was pushed 3 years ago, meanwhile we added more subdirectories, so we needed to actualize that recipe, but 3 years later in a different pull request.

**Comment by tarsius** [comment]
> which is different of the current situation

Yes.
