### ISSUE TITLE
About Tomohiro Matsuyama's packages

### ISSUE THREAD

**Issue by jcs090218** [melpa/melpa#6641]
I recently encountered some issues with package [yascroll](https://github.com/m2ym/yascroll-el). I am hoping for a fix but the repository is archived and not able to opened an issue. 

I know @m2ym has many packages on melpa, is there a chance to keep all his packages to Emacs Orphanage or at least keep those packages active maintain? I have emailed him, but I am not getting his response. Hence, I opened an issue here. Can anyone contact him?

**Comment by tarsius** [comment]
@m2ym has archived virtually **all** of his repositories (his webpage repositories are the only exceptions). Looks like someone is *done*, which we have to respect. We have to respect that of course but I hope we can get him to hand off his repositories.

1. This included the following packages from [his personal account](https://github.com/m2ym), which are available from Melpa as well as the Emacsmirror.  IMO these packages should be transferred to the [Emacs orphanage](https://github.com/emacsorphanage).

   - [direx](https://github.com/m2ym/direx-el)
   - [mongo](https://github.com/m2ym/mongo-el)
   - [popwin](https://github.com/m2ym/popwin-el)
   - [thingopt](https://github.com/m2ym/thingopt-el)
   - [undohist](https://github.com/m2ym/undohist-el)
   - [yascroll](https://github.com/m2ym/yascroll-el)

2. It also included the following other emacs-lisp repositories from [his personal account](https://github.com/m2ym), but these are missing from Melpa and the Emacsmirror.  IMO they should **not** be transferred.

   - [autopair](https://github.com/m2ym/autopair-el) obsolete fork of https://github.com/joaotavora/autopair
   - [help-key](https://github.com/m2ym/help-key-el)
   - [make](https://github.com/m2ym/make-el) not a package
   - [gccsense](https://github.com/m2ym/gccsense) very old

3. Unfortunately this also included all the packages from the [auto-complete](https://github.com/auto-complete) organization.  This is a huge issue because these three packages are very popular.

   - [auto-complete](https://github.com/auto-complete/auto-complete) downloads 403736, percentile: 98.94
   - [popup](https://github.com/auto-complete/popup-el) downloads 731160, percentile: 99.80
   - [fuzzy](https://github.com/auto-complete/fuzzy-el) downloads 143555, percentile: 95.40
   
   We really need to find some people who are willing to do at least some maintenance.
   
   Since those repositories are already under an organization, it is best to leave them there instead of moving them to the orphanage.  But I recommend that @m2ym makes me and @purcell owners of the organization, so that we can promote the new maintainers once we have volunteers without him having to get involved again.

**Comment by jcs090218** [comment]
I think your decision is awesome. The major issue is that I couldn't  contact @m2ym, not sure if anyone could contact him?

**Comment by m2ym** [comment]
I am willing to transfer my repositories.

@tarsius I have sent an invitation to auto-complete organization. I would like to transfer my personal repositories to Emacs orphanage as well. No problem?

**Comment by tarsius** [comment]
Thanks!

> I have sent an invitation to auto-complete organization.

Thanks I have joined.

> I would like to transfer my personal repositories to Emacs orphanage as well.

I have sent an invitation to emacsorphanage organization. You should be able to transfer your repositories now.

Do you want to stay involved in some form? Should I make you a maintainer of the transferred repositories or on the opposite remove you from the organization again once the transfers are complete?

**Comment by jcs090218** [comment]
@tarsius Can you make me the collaborator to yascroll? Thanks!

**Comment by m2ym** [comment]
@tarsius I have transferred my personal repositories to emacsorphanage organization.

> Do you want to stay involved in some form? Should I make you a maintainer of the transferred repositories or on the contrary remove you from the organization again once the transfers are complete?
I want to step down from a maintainer.

Thank you for helping me transferring repositories.

**Comment by tarsius** [comment]
Thanks @m2ym!

@jcs090218 I have invited you to the organization. After you have accepted, i can give you access to the repo.

**Comment by jcs090218** [comment]
@tarsius I have joined the organization! Can you give the access to the repo? Thanks!! :D

**Comment by tarsius** [comment]
> I have joined the organization!

Would you care to make that public?

> Can you give the access to the repo?

Done.

**Comment by jcs090218** [comment]
> Would you care to make that public?

What public? Did I miss anything?

**Comment by tarsius** [comment]
At https://github.com/orgs/emacsorphanage/people you can control whether others can see that you are a member. I think it is important to be transparent about who has access.

**Comment by jcs090218** [comment]
Yeah, I just make myself public? Done!

**Comment by tarsius** [comment]
And while we are at it, it would be create if @purcell and @cireu could do the same.

**Comment by cireu** [comment]
> And while we are at it, it would be great if @purcell and @cireu could do the same.

Done.
