### ISSUE TITLE
Melpa appears broken since evening of 15.01.2020

### ISSUE THREAD

**Issue by doublep** [melpa/melpa#6644]
I made commits to two repositories yesterday (https://github.com/doublep/eldev and https://github.com/doublep/datetime) and also created a stable tagged release 0.1.2 in the first one. However, new packages are still not available from Melpa or Melpa Stable, despite the sites claiming that latest build have been finished just recently.

According to package list, there are no new packages from 16.01.2020 and only two packages from 15.01, but they are both from morning.

Current CI status on Melpa is "failing" since 15.01. It had been "passing" before that.

**Comment by milkypostman** [comment]
Will take a look this evening.

**Comment by milkypostman** [comment]
the problems with the packages not updating in Melpa for eldev and date time is that their commits don't affect the files that are packaged. the updates are to tests and docs which we don't package.

however, you did catch a bug in some changes that @tarsius made recently to stable Melpa. not a huge deal, but we were removing newer stable versions instead of the old version. very nice catch and thanks for reporting. also happy we caught this early since it just got pushed out yesterday!

**Comment by milkypostman** [comment]
696b5563839e07ed9cd2322b88c9b87bdc8c82cf is the fix if you're curious 👍

**Comment by milkypostman** [comment]
PS: I'm going to let Melpa-stable just work through the queue and make sure it resolves everything naturally. i.e., I'll look in the morning and it should be fixed and we should see the new version.

**Comment by doublep** [comment]
> the problems with the packages not updating in Melpa for eldev and date time is that their commits don't affect the files that are packaged

This was indeed true for `datetime`, but not for Eldev.  But now the problem is fixed and 0.1.2 is available from stable.melpa.org. Thank you.
