### ISSUE TITLE
Is neotree still maintaining?

### ISSUE THREAD

**Issue by jcs090218** [melpa/melpa#6700]
@jaypei has been inactive on GitHub for over a year and `neotree`'s last commit is on `2018.11.21`. Wonder if there is anyone maintaining this package? Can anyone contact him? Thanks!

**Link:** https://github.com/jaypei/emacs-neotree

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but It is good you open this issue [upstream](https://github.com/jaypei/emacs-neotree) first, maybe.
(The GitHub notification should have been sent to him because you mention him, but I think it's appropriate to raise this issue in the upstream)

And I ref his [GitHub user page](https://github.com/jaypei), find Email-address. So you can Email him to contact.

**Comment by jcs090218** [comment]
Yeah, I think there are several pings in upstream hence I decided to open the issue here instead. I would email him now even though I don't think he will response. Thanks!

**Comment by purcell** [comment]
Sometimes people turn off their github notifications when overwhelmed, so email is usually a good choice. :+1:

**Comment by jcs090218** [comment]
> Sometimes people turn off their github notifications when overwhelmed, so email is usually a good choice.

Got you! Just a quick update. I have emailed him and maybe we can wait for a week or two? Thanks!

**Comment by tarsius** [comment]
All of the most recent commits are by @palikar.

Hello @palikar, could you please tell as a little more? Are you in contact with @jaypei? Are you a co-maintainer? Do you have commit access?

**Comment by jcs090218** [comment]
@palikar Ping! :)

**Comment by tarsius** [comment]
Apparently the answer is "no" but as long as the package does not bit-rot, we can keep it on Melpa anyway.
