### ISSUE TITLE
About Greg Sexton's packages.

### ISSUE THREAD

**Issue by jcs090218** [melpa/melpa#6716]
I am using @gregsexton 's package [origami.el](https://github.com/gregsexton/origami.el) yet I think he has been inactive on GitHub for a long time. I have tried to contact him via email long time ago but no response. Can anyone contact him? Are those packages still maintain? Thanks!

**Link:** https://github.com/gregsexton

**Comment by tarsius** [comment]
Do you want to take over `origami`? That would be a lot of work though as you should go through the issues on the original repository.

**Comment by jcs090218** [comment]
I am willing to take over `origami`, yet there are many issues up there. This could be hard for maintainer for the lost of PRs and issues. :cry:

**Comment by jcs090218** [comment]
Anyway, there are total 3 package that @gregsexton owned.

* [origami.el](https://github.com/gregsexton/origami.el) (mentioned)
* [httprepl.el](https://github.com/gregsexton/httprepl.el)
* [ob-ipython](https://github.com/gregsexton/ob-ipython)

What about these packages? 😕

**Comment by purcell** [comment]
As usual, the process here would be to send Greg an email and suggest either co-maintainership of the existing repositories, or transfer to a new maintainer or to the `emacsorphanage` Github organisation as a staging location. Would you like to do that, @jcs090218?

**Comment by jcs090218** [comment]
> As usual, the process here would be to send Greg an email and suggest either co-maintainership of the existing repositories, or transfer to a new maintainer or to the emacsorphanage Github organisation as a staging location. Would you like to do that, @jcs090218?

I had sent the email already. Do you want me to send him another one? I would like to. 😕

**Comment by purcell** [comment]
Oh cool, how long ago was that?

**Comment by jcs090218** [comment]
I sent it on 2019 Oct. 7th. It was last year... I don't know if I should keep sending him? 😕

**Comment by purcell** [comment]
I just emailed him now to be more explicit about our plans:

> Hi Greg,
> 
> Thanks for your elisp packages. MELPA users have noted that you haven’t had time to maintain them in recent times, and we’re going to go ahead and allow volunteers to fork and actively maintain the corresponding repos as the official MELPA-distributed package sources.
> 
> If you’d consider transferring the repos to the emacsorphanage github organisation, though, it would be appreciated, as it would allow the new maintainers to pick up with the existing PRs and issues. That’s pretty much a fire-and-forget process, so very straightforward from your side.
> 
> Cheers, and wishing you a good 2020.
> 
> -Steve

Let's give it 3 weeks, then we'll feel free to switch over to forks if necessary.

**Comment by gregsexton** [comment]
Not sure where you emailed, Steve, but I didn't receive anything. Not to worry though, thanks for quoting the text.

I have no plans to work on ob-ipython. I'm happy to perform some transfer here. I haven't stopped working on origami or httprepl. Both provide a core functionality that works well and I consider them stable. If people make me aware of serious issues in either of these, I will find time to fix them. I'm not actively adding features to either.

@jcs090218 seems particularly keen to work on origami. What is the plan here? What is missing in your view? Emacs makes adding functionality trivial in an incremental way. Could you develop packages that depend on origami to achieve what you want? I would like to keep the core small and very stable.

**Comment by tarsius** [comment]
> I have no plans to work on ob-ipython. I'm happy to perform some transfer here.

You can transfer to my user account and I'll then transfer from there to `emacsorphanage`.

**Comment by jcs090218** [comment]
@gregsexton There are nothing missing in my view! First of foremost, thanks for your awesome package. I consider a package unmaintained base on the activity on the repository. Like answering question or making PR, etc. Is fine if you want to keep the core small and stable but I might willing to see you or the maintainers responding issue or PR? 😕 I find out there are many PRs and issues that are worth to discuss but without you, nothing is going to change! Thanks for you willing to keep maintaining these packages! 😄

**Comment by purcell** [comment]
> Not sure where you emailed, Steve, but I didn't receive anything. Not to worry though, thanks for quoting the text.

I used the gmail account that on your github page. Maybe it ended up in Junk.

**Comment by gregsexton** [comment]
![Screenshot 2020-03-17 at 09 07 49](https://user-images.githubusercontent.com/150883/76840286-ddf7a480-682e-11ea-8dc5-3cf57c77d196.png)

Yep, it did. I reported you as not spam. :)

**Comment by alphapapa** [comment]
*facepalm*  In fairness to Gmail (though it pains me to say), the general format of the message does resemble phishing/scam-type spam.  Swap a few words, mention a large sum of money, and there you go.  :laughing:

**Comment by purcell** [comment]
Haha, I'd suggest that I could have a successful career as a spam copywriter, but I guess the goal there is to *not* trip the spam filters.

**Comment by conao3** [comment]
And what do we do on this issue?
I am using `origami` and interested in continuous maintenance.
[origami](https://github.com/gregsexton/origami.el) has not been updated for two years and leaves [my PR](https://github.com/gregsexton/origami.el/pull/85) of Apr, 2019 and [the PR](https://github.com/gregsexton/origami.el/pull/87) from @jcs090218  of Jun, 2019.
I think either of them are minor changes and no blockers. How about @gregsexton think?

**Comment by jcs090218** [comment]
Is @gregsexton still here? Ping. 😕

**Comment by dvzubarev** [comment]
FYI https://github.com/dzop/emacs-jupyter can be used as replacement for ob-ipython. Many users already migrated to emacs-jupyter. @gregsexton if you don't want to maintain ob-ipython, you can mention emacs-jupyter in Readme.

**Comment by tarsius** [comment]
@gregsexton you can transfer `ob-ipython` to me and I will then transfer it to the `emacsorphanage` or `emacsattic` when I have decided what is appropriate. And take care of updating the README and such. You cannot transfer to either of these organizations directly because you are not a member you can transfer to some other user account though (the receiver still has to approve the move).

So basically you have do initiate the transfer and can then forget about it -- I'll take care of the rest.

**Comment by conao3** [comment]
@gregsexton here?

There is a problem with the recently merged changes, so please handle it. (gregsexton/origami.el/pull/64)

If @gregsexton will continue to do maintenance on `origami`, we can close this issue by your declaring it as such.
Also, please respond to @tarsius's suggestion about `ob-ipython`.

**Comment by jcs090218** [comment]
If @gregsexton continues to do the maintenance, I might ask him for someone who willing to work as collaborator. Because I think @gregsexton is often inactive on GitHub? 😕 Thanks!

**Comment by gregsexton** [comment]
> FYI https://github.com/dzop/emacs-jupyter can be used as replacement for ob-ipython. Many users already migrated to emacs-jupyter. @gregsexton if you don't want to maintain ob-ipython, you can mention emacs-jupyter in Readme.

> @gregsexton you can transfer ob-ipython to me and I will then transfer it to the emacsorphanage or emacsattic when I have decided what is appropriate. And take care of updating the README and such.

I use ob-ipython occasionally these days. I like that it's just small, simple, and stable. I've been considering what I want to do with this package and I think I'll reserve the right to preserve it in its current state and maybe pick it back up someday.

People should feel free to fork or whatever. I vaguely recall someone reaching out to me about emacs-jupyter and this may even have started life as a fork.

Melpa folks, I love what you do. If you're unhappy with my approach to maintaining these packages and don't consider it responsible enough - I can see that - feel free not to distribute them. I think most of these have reverse-dependencies though.

I hope not to come across as an irresponsible maintainer. From my point of view, these packages work and are stable. It is a choice to not keep adding features. People sending me PRs and issues is great. I'll occasionally find energy and time and look at them and consider merging them. I don't exactly keep an SLA though.

> I am using origami and interested in continuous maintenance.

> Is @gregsexton still here? Ping. 😕

Comments like this are mostly why I don't choose to spend more time working in open source. I haven't open sourced anything for a few years now, because it's just not worth the hassle. Why are you not happy to respect my cadence here? I'll reply if and when I choose to. I don't get anything out of sharing code with you. Literally nothing.

> There is a problem with the recently merged changes, so please handle it.

I looked at that PR. The very next comment is someone telling you that your tone is inappropriate. You're actually right, we shouldn't pollute the namespace and there are better ways of defining that function. But you know what, I don't care. It's not actually causing any issue. I might fix it at some point.

**Comment by tarsius** [comment]
@gregsexton Thanks for the response.

> Melpa folks, I love what you do. If you're unhappy with my approach to maintaining these packages and don't consider it responsible enough - I can see that - feel free not to distribute them.

That's fair. I think Melpa should continue to distribute your packages.

> I haven't open sourced anything for a few years now, because it's just not worth the hassle. Why are you not happy to respect my cadence here? I'll reply if and when I choose to. I don't get anything out of sharing code with you. Literally nothing.

I understand where you are coming from and accept your decision.

I also think that you *could* get something out of sharing your code if you accepted more contributions. But doing that takes time, which you might not have. So again, this is fine, it is your decision. (I would like to encourage you to add a note to you readmes about the limited amount of work you are willing to invest.)

Even so this might force other people to fork, which is *also fine*. With `ob-ipython` that apparently has already happened, while in the case of `origami`@jcs090218 might do it and we most likely would add it to Melpa.

**Comment by alphapapa** [comment]
> > There is a problem with the recently merged changes, so please handle it.
> 
> I looked at that PR. The very next comment is someone telling you that your tone is inappropriate. 

@gregsexton You mean that very rude comment that accuses Naoya of doing what the accuser has done?  The one written in a very nasty tone?  In contrast, I see no "tone" in the simple observation and recommendation that Naoya made.

> You're actually right, we shouldn't pollute the namespace and there are better ways of defining that function. But you know what, I don't care. It's not actually causing any issue. I might fix it at some point.

Polluting the namespace is a problem in and of itself, because Emacs packages share a single namespace.  Users of the package who upgrade it will suddenly have a new symbol whose name doesn't respect the symbol-naming convention that all MELPA packages are expected to follow.

Since you merged that PR, and since it's your package, isn't it your responsibility as the maintainer to fix that, rather than expecting someone else to send a PR to fix it?

MELPA is trying to uphold higher standards than it used to.  With nearly 5,000 Emacs packages sharing a single namespace, it's necessary to do so to prevent conflicts and breakage.  This Emacs package "ecosystem" is like a garden in which we all tend our plants.  If you graft a new branch onto your plant that blocks another plant's sunlight, you harm not only that plant, but the garden, and all who visit it.

I don't understand the hostile attitude.  Is it too much to ask that you neatly trim the plants you've contributed to the garden so they don't interfere with others?

You say you're not getting anything out of it.  What you're getting out of it is a vibrant community full of packages for you to use.  What you're getting out of it is giving back to the Emacs and Free Software community that has given you so much without asking anything in return.  What you're doing is standing on the shoulders of giants and building new giants for others to stand on.  

"But what does this bug report do for me?  I'll merge a PR for my oversight if someone else makes it" is a very poor attitude.  What is needed most is good stewardship of the code that we share.

**Comment by alphapapa** [comment]
@gregsexton  This PR is the one that you merged and want someone else to fix for you?https://github.com/gregsexton/origami.el/commit/e558710a975e8511b9386edc81cd6bdd0a5bda74  It's a `defun` inside a lambda that declares a top-level function outside of the package's namespace at runtime!  `cl-labels`, anyone?  This would never be accepted in a new MELPA package.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Sorry for warming up this "old" thread. I didn't get all details here but it seems that the maintainership of `origiami` is overhanded to someone other?

Currently I use `origiami` version `20200331.1019` which seems to be is the current freshest release. Isn't it?
The `list-packages` tells me that there is still Greg Sexton the head in charge for that package.

Did I missed something? Is there a fresher GitHub repo that wasn't released on Melpa/Elpa yet?

Today the `origami` version has some issues e.g. the deprecated `cl` dependency.
