### ISSUE TITLE
Refactoring package

### ISSUE THREAD

**Issue by ema2159** [melpa/melpa#6721]
Hello! I'm refactoring my package by changing from a single package.el file to lets say package-functions.el, package-variable.el, package-misc.el and package.el files. Is there anything important to take into consideration? Like the `requires` or file order or anything? I think the recipe should remain the same according to the documentation. Thanks in advance!

**Comment by milkypostman** [comment]
Should be good. Let us know if there are issues. We somewhat rely on the
community to alert us to problems with specific packages so if it doesn’t
update for a day after you push your changes please file a bug.

**Comment by alphapapa** [comment]
@ema2159 After you've refactored the files, be sure to test that the package installs and works correctly.  You can use this to help: https://github.com/alphapapa/makem.sh  If it works correctly with `makem.sh --sandbox`, then you should probably test one more time using Quelpa, which uses the default recipe (you could test a branch instead of `master`).  If it works in both of those, it should work for other users once it's rebuilt on MELPA, so then it should be okay to push it to `master`.

**Comment by ema2159** [comment]
Thanks @milkypostman @alphapapa! I will take your advice. Another option I think is worth considering is using `straight.el` and switching to the branch that contains the new code and rebuilding the package to see if it works.
