### ISSUE TITLE
p4.el unmaintained since 2015

### ISSUE THREAD

**Issue by alexhutcheson** [melpa/melpa#6898]
The [p4](https://melpa.org/#/p4) package (used for communicating with the [Perforce](https://www.perforce.com/products/helix-core) VCS) hasn't received any updates since 2015, even though it has had open [issues](https://github.com/gareth-rees/p4.el/issues) and [pull requests](https://github.com/gareth-rees/p4.el/pulls).

I've reached out to the maintainer, @gareth-rees over email, but haven't received a response yet, although they may just be busy. 

Given the status of the project and the relatively high number of downloads, I would propose moving the project to the [Emacs Orphanage](https://github.com/emacsorphanage) so existing pull requests can be handled and outstanding bugs can be fixed.

**Comment by tarsius** [comment]
@gareth-rees would you be willing to do that?

If so, then please transfer the repository to me and I then transfer it to the orphanage. Doing it directly does not work because Github disallows transfers to an organization by non-members. I would then take care of vetting and assigning one or more maintainers.

**Comment by tarsius** [comment]
@gareth-rees Friendly ping?

@alexhutcheson Are you volunteering to become the maintainer? What's your experience maintaining emacs packages?

@qoocku As the author of magit-p4 you might be interested in helping with this.

**Comment by jcs090218** [comment]
I think magit-p4 is also looking for maintainer? See their readme page [here](https://github.com/qoocku/magit-p4).

It's kind of sad that these packages are unmaintained. :( I can help maintain these packages if these packages are transfer to emacsorphanage. ;)

**Comment by qoocku** [comment]
Yes, sorry for the delayed reaction. `magit-p4` will not be maintained by me or Alexei - we have lost contact with Perforce long ago I think ;). So what are the steps to help? Where should I transfer this repo?

**Comment by tarsius** [comment]
> If [you want to transfer to the Emacsorphanage], then please transfer the repository to me and I then transfer it to the orphanage. Doing it directly does not work because Github disallows transfers to an organization by non-members. 

:grinning:

**Comment by purcell** [comment]
Ping!

**Comment by alexhutcheson** [comment]
Apologies for the delayed response. I would prefer not to be the maintainer - I don't have experience maintaining emacs packages, and (more importantly), I don't use a vanilla Perforce (now [Helix Core](https://www.perforce.com/products/helix-core)) instance, so it would be difficult for me to test that changes won't break others.

**Comment by tarsius** [comment]
Okay, thanks for the information.

If @gareth-rees wants to transfer to the Emacsorphanage, then he can still do that.

(Due to permission settings you would have to transfer to me and I would then transfer to the orphanage.)

But since he has not chimed in yet in all this time, I don't count on that and close this issue.
