### ISSUE TITLE
Add "*.md" and "*.org" to the default :files value?

### ISSUE THREAD

**Issue by lockywolf** [melpa/melpa#7178]
I believe that 99% of the package repositories that have .org files have either a README in them, or a github introduction page.

Doesn't it make sense to include them?

**Comment by purcell** [comment]
This has been considered previously and here's why we don't do it:

* Packages are installed into an obscure subdirectory of `~/.emacs/elpa/...` so such docs are not convenient for a user to find
* Info docs are supported and encouraged, because they then automatically augment the build-in info manual
* If a package contains interactive commands which find and display docs in another format, then we are fine for the author to include such files in the recipe by adding them to the `:files` list

Hope that makes sense.

**Comment by meedstrom** [comment]
Huh.  This default behavior is why I have all my README.org files export to texinfo. Early on in Emacs journey, I was constantly frustrated by not finding a README.org included in `elpa/` :)

It's a double-edged sword because a README is not *quite* a manual, but it also did teach me how to generate texinfo in the first place, so then when I get around to it I can make a separate, better manual.  

If other people are like me, then Melpa's default might have helped spread Info manuals, which is a good thing. Even if some of them are just READMEs.
