### ISSUE TITLE
Support TLS 1.3 on melpa.org

### ISSUE THREAD

**Issue by kmwyard** [melpa/melpa#7200]
Supporting TLS 1.3 on melpa.org could make [more secure and faster](https://netflixtechblog.com/how-netflix-brings-safer-and-faster-streaming-experience-to-the-living-room-on-crowded-networks-78b8de7f758c?gi=165d095f9426) downloading Emacs packages on melpa.

**Comment by purcell** [comment]
Good idea.

**Comment by purcell** [comment]
This is a good source for the setting btw: https://ssl-config.mozilla.org/

**Comment by kmwyard** [comment]
But [melpa.org is graded B in Qualsys SSL Lab's SSL Test](https://www.ssllabs.com/ssltest/analyze.html?d=melpa.org). and Applying TLS 1.3 makes [downloading faster](https://netflixtechblog.com/how-netflix-brings-safer-and-faster-streaming-experience-to-the-living-room-on-crowded-networks-78b8de7f758c), too

**Comment by purcell** [comment]
Not sure why you're replying with "but" - I agreed we should do this, when time permits. You could argue it's more important to drop TLS 1.0 and 1.1 support, since that's the main thing that reduces the SSL Labs test score these days. I don't think we have any automatic rebuilds of the docker containers, so probably @milkypostman would have to take a look at this. (Our nginx config is [here](https://github.com/melpa/melpa/blob/master/docker/nginx/default.conf) btw.)

**Comment by milkypostman** [comment]
done. Now we score A+

**Comment by purcell** [comment]
Nice, what a team! :tada:

**Comment by milkypostman** [comment]
❤️
