### ISSUE TITLE
More maintainers?

### ISSUE THREAD

**Issue by minad** [melpa/melpa#7266]
Ist there some process to propose more melpa maintainers? Or is there some other alternative to improve the process - maybe some volunteers could help and tag PRs as "recommendation to merge", "needs revision", "recommendation to close", "invalid license - waiting", "does not pass checks - waiting" or sth along those lines. Has something like this discussed before? The maintainers could concentrate on the PRs which are ready.

**Comment by cniles** [comment]
Also along these lines, I think a democratic process to help eliminate packages that don't meet the "reasonably innovative" requirement could be helpful.  This is a somewhat subjective criteria that community feedback could help with.

**Comment by jpablobr** [comment]
There was some discussion in [Automate purcell #4154](https://github.com/melpa/melpa/issues/4154) and what I gather in that one is basically free to just jump in. That seems to have been [alphapapa's approach](https://github.com/melpa/melpa/issues/4154#issuecomment-247224482) and has been appreciated.

**Comment by minad** [comment]
Just to make this clear - my question is if there is some process to add other maintainers or if there is some kind of possibility to introduce new maintainers with fewer rights as a starting point, doing some basic testing, preselection and tagging. I don't think we should go too much into the other details before answering that question.

----

Since you mention it, I can offer my standpoint on this issue:

> I think a democratic process to help eliminate packages that don't meet the "reasonably innovative" requirement could be helpful

I must say, I am not a big fan of this requirement. I consider quality/well written/well behaved/stable code to be more important than the innovation aspect. There are already many packages on melpa which are not innovative and that is okay, they solve something we want and maybe the solve it in only a minimally different way than some other existing packages. Furthermore there are already packages on melpa which I consider rather simple - things you might rather copy to another package instead of introducing a leftpad-situation. I also have some code lying around which I find useful, which is maybe not innovative but just does some things slightly different or in my opinion slightly better than something existing. But I would not call that innovative. I think this criterion is also too fuzzy and too judgemental. For me Emacs is also about choice.

Maybe something I would like is that packages could be marked as alternatives to something else - I find this important to make it clear that there are alternatives and to make it clear what the distinction is. So if the reviewer sees that a package is too similar to an existing package, this should be noted. I guess this should be a requirement for inclusion. But on the other hand it is not a good requirement if the submitter is required to do overly extensive comparisons to existing packages. I guess it is okay if it can be shown that there are differences and that they are significant in some sense. But maybe after all this is just the "reasonably innovative" criterion applied?

I would like to focus on the maintainer discussion if possible!

**Comment by minad** [comment]
@jpablobr I did not see the automate purcell issue before. I will take a look - but it is rather old from 2016. So maybe some new discussion is appropriate?

**Comment by jpablobr** [comment]
@minad Yes, I agree, definitely not a closed discussion but @riscy pointed it out (#4154) on my last PR a couple of days ago so thought it was worth mentioning. 

My concern was more as to assuring a package's code quality (to MELPA's standards) after a merge; but yes, maintainers/automation seems to be still the biggest bottle neck.

**Comment by cniles** [comment]
> I would like to focus on the maintainer discussion if possible!

I felt it was in-line with the discussion.  Despite your opinion, the language exists.  To that point, auditing packages for being useful, non-trivial, non-redundant (or at least solving something in a new / better way) and engaging submitters on that criteria takes maintainer time as well.  Whether that effort is substantial or not I don't know.

**Comment by alphapapa** [comment]
> auditing packages for being useful, non-trivial, non-redundant (or at least solving something in a new / better way) and engaging submitters on that criteria takes maintainer time as well. Whether that effort is substantial or not I don't know.

IMO that effort can be substantial, especially if the submitter has not even attempted due diligence (which is usually the case).  Then there are the submissions that are trivial in functionality but have 15 files of boilerplate in the repository obscuring that fact.

I think it boils down to this: quality isn't free.  Someone has to pay for it, whether the submitter or the reviewer.  It takes a lot of time to manually review packages for all these issues.  It takes time to review code to ensure that it's decently idiomatic Elisp.  It takes time to go through a file and point out issues, like, "These functions X, Y, and Z are each one-line and each called in one place--they don't need to be named functions cluttering the obarray."  

Now, do those kinds of issues *need* to be caught?  Would MELPA users be significantly worse off without that detailed of a review?  (Nevermind that there's no review or enforcement after initial review.)  To some degree, probably, but it's hard to say how much.  I think the whole is more than the sum, if you know what I mean, and I think it's worth it to share this kind of knowledge with new package authors.  Hopefully they then share it as well.

FWIW, @purcell, as I said on Reddit: if you would like me to help with reviews in a more official capacity, I'm willing to do so.  If not, I'll continue to offer reviews on my own where it seems helpful.  Thanks for your work.

**Comment by jpablobr** [comment]
> Now, do those kinds of issues need to be caught?

I think that's a pandora's box and probably the most important question. Because on one hand, the more complex and subjective those issues are the harder it is to automate and ensure code quality after a merge, but on the other hand,  once your package has been accepted/merged it suggests a certain quality which is what we seem to value the most from MELPA. 

While I like the just jump in approach (mostly from people who at least already have been through a package review process) you'll always have to debate if you'll be making things more difficult for the actual reviewer so I imagen people would be somewhat hesitant to do it (not to mention that unless you've read #4154 you might not even have known that in the first place).  

I think officially assigning some maintainers/reviewers roles might be worth it? And maybe someone can open a Maintainers/Reviewers Manual repo (in MELPA) so people can start submitting PRs? That way @purcell [would not have to spend too much initial time getting something out](https://github.com/melpa/melpa/issues/4154#issuecomment-240604301), and it can be just a WIP for a while.

The manual can just be (or start with) a bullet-points based document similar to [bbatsov Emacs Lisp Style Guide](https://github.com/bbatsov/emacs-lisp-style-guide) but for MELPA. Whenever someone opens a PR/Issue over there there's usually some interesting back and forth.   

There are many little maintainer/reviewer related issues that probably could be sorted out over there as well. Like the fact that Package Addition PRs are only a link to the actual code and if the submitter continues to work on his package's repo the code that the reviewer is going through might be outdated (mostly when it can take up to a week for a reviewer to start checking a PR).

**Comment by riscy** [comment]
> Ist there some process to propose more melpa maintainers?

Probably by raising an issue like this. :)  My involvement started by jumping in (as @jpablobr describes) and bugchecking and commenting on the checklist items.  I guess I became a consistent enough presence that I was given permissions to merge as a collaborator.

One thing I continue to learn while doing this is that programmers have strong opinions, so when you're getting started it's better to stick to objective criteria like the checklist (while being able to spot false positives) and documented elisp best practices.

My own view is that it would surely be helpful to have reviewers specialized to e.g. the org-sphere (which @alphapapa does a fantastic job of), elisp programming (libraries like s-, dash-, async...), networking, etc.  Areas where one needs deeper knowledge which I often lack.

> I think a democratic process to help eliminate packages that don't meet the "reasonably innovative" requirement could be helpful.

@cniles got a couple of downthumbs but -- while it's not exactly a democratic process -- it can be helpful when people add comments like, "Did you know about `@soandso`'s package?  Can you work with them?"  I also hugely appreciate it when authors post an RFC somewhere, since the community obviously knows the Emacs ecosystem better than any one person.  This kind of feedback can drastically simplify the review process.

Regarding innovative packages,

> I think this criterion is also too fuzzy and too judgemental. For me Emacs is also about choice.

Yes, but to be fair MELPA's aim is not choice but curation.  It just so happens it's also the _largest_ package index, but that might not always be the case.  You're also correct when you say there are lots of packages that don't meet contemporary guidelines.  Identifying and flagging them would be a useful thing for MELPA to do.

Nevertheless I sometimes merge packages that are similar to existing ones after hearing an appeal/explanation from the author.  These authors could speed up the review process by doing this footwork ahead of time (see above re: RFCs) and not expecting it of reviewers, which is one of the reasons I recently merged https://github.com/melpa/melpa/commit/15a6136c1988b620bf745985ea4f7f3c4c6e6127.

**Comment by minad** [comment]
> My involvement started by jumping in...

Great! Maybe more reviewers can be added in a similar way. I would very much like to see more maintainers. My recent experience with @alphapapa went well as in #7240, despite us having had an overly heated discussion on reddit :)

> One thing I continue to learn while doing this is that programmers have strong opinions, so when you're getting started it's better to stick to objective criteria like the checklist (while being able to spot false positives) and documented elisp best practices.

This is a point, I would like to see emphasized. Ideally the reviewer should adhere to some kind of formal list in order to make things not too opinion based (in my opinion regarding the process). But I think it is okay if the reviewer also states their opinion and makes a few opinion-based improvement suggestions, as @alphapapa did for example in #7240.

> Yes, but to be fair MELPA's aim is not choice but curation. It just so happens it's also the largest package index, but that might not always be the case. You're also correct when you say there are lots of packages that don't meet contemporary guidelines. Identifying and flagging them would be a useful thing for MELPA to do.

I agree with that in general - having a review is good and it is great to have quality assurance. 

But regarding similar/innovative packages etc - I am not a fan of this specific rule. In particular since it could make sense to have two very similar packages which only do things in a slightly different way, since often I think the perfect solution might have not been found yet. For example if you consider the packages around completion systems, e.g., consult and marginalia which I am currently involved with - overall they are not innovative. They are trying a different approach to a problem which has already been solved a few times, even if maybe not to everyone's satisfaction. But still I am 100% convinced that they are useful (already used by a few people) and that they have their place in a curated package repository. But in that case the reasons are probably good enough, I think there are more problematic edge cases. 

> Nevertheless I sometimes merge packages that are similar to existing ones after hearing an appeal/explanation from the author. These authors could speed up the review process by doing this footwork ahead of time (see above re: RFCs) and not expecting it of reviewers, which is one of the reasons I recently merged 15a6136.

What you say sounds very fair. Authors can explain their reasons make an appeal in questionable cases. So from what I am seeing now - nothing to change here.

**Comment by alphapapa** [comment]
> This is a point, I would like to see emphasized. Ideally the reviewer should adhere to some kind of formal list in order to make things not too opinion based (in my opinion regarding the process). But I think it is okay if the reviewer also states their opinion and makes a few opinion-based improvement suggestions, as @alphapapa did for example in #7240.

> But regarding similar/innovative packages etc - I am not a fan of this specific rule. In particular since it could make sense to have two very similar packages which only do things in a slightly different way, since often I think the perfect solution might have not been found yet. For example if you consider the packages around completion systems, e.g., consult and marginalia which I am currently involved with - overall they are not innovative. They are trying a different approach to a problem which has already been solved a few times, even if maybe not to everyone's satisfaction. But still I am 100% convinced that they are useful (already used by a few people) and that they have their place in a curated package repository. But in that case the reasons are probably good enough, I think there are more problematic edge cases.

What is a rule but ink on paper, pixels on a screen.  In every system, ultimately, it's a matter of people exercising good judgment, with wisdom, in accordance with their understanding of the system's purpose.  

Rules best serve as advance notice to others of how those in charge will generally apply their judgment.  They do not, and should not be expected to, cover all scenarios.

It would be a mistake to attempt to expand rules to do so--such would create unwieldy rules that can't be easily comprehended and applied.  It would also be a mistake to demand rigid adherence to them--such would create a kind of vulnerability in the system by which bad actors may take advantage of good faith.

Our best defense of excellence is to invest good people with the necessary authority and let them work.  This is what I've always seen MELPA doing, and I think we need not challenge them.  If it ain't broke...

And, of course, being the world of FOSS, if one doesn't agree with MELPA's vision, one is free to create an alternative.  Before MELPA, there was Marmalade, and someday there may be another.  If MELPA is too curated for someone's taste, there's nothing stopping one from forking it and accepting submissions more liberally.  Some users might find value in such a thing.  Go for it!
