### ISSUE TITLE
Correct way of providing multiple themes

### ISSUE THREAD

**Issue by topikettunen** [melpa/melpa#7388]
I recently added new dark variant of my theme in already existing package in Melpa (see: https://github.com/topikettunen/brutal-emacs). I wasn't able to figure out a way where I could provide both light and dark theme with only one package without changing the existing recipe, so the current way feels very wrong.

Since the recipe was named `brutal-theme`, I made new file by that name with only containing following:

``` elisp
;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide 'brutal-theme)
```

After which I can load the package with:

``` elisp
(use-package brutal-theme
  :load-path "themes/brutal-emacs" ; for local testing
  :config
  (load-theme 'brutal-dark t))
```

Sure after that, I can correctly load both dark and light themes with `load-theme` but this also provides an empty theme named `brutal` for me.

So what would be the correct way to provide both of these?

**Comment by purcell** [comment]
What you're doing is basically fine, but the "brutal-theme.el" is interpreted as a theme file because it is on `custom-theme-load-path`. The best choice here would probably be renaming the overall package and that .el file to `brutal-themes`. If you don't have many users it's not super disruptive. The new melpa recipe can use `:old-name` (IIRC?) to indicate it has been renamed. Alternative here is to put the actual theme files in a subdir and add that to the theme load path instead - this would also require a change to the recipe.

**Comment by purcell** [comment]
I see from #7381 that the intent is to maintain continuity of the package name, so perhaps try the second approach: move the theme files to a "themes" subdir, adjust the autoload accordingly, and add `:files (:defaults "themes")` to the recipe.

**Comment by topikettunen** [comment]
I think this answered my question! Thanks for the response. I'll close this ticket for the time being.
