### ISSUE TITLE
Update to python 3

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#7482]
Cask is dropping support for python 2, so we need to install version 3.

https://github.com/cask/cask/issues/498
https://github.com/cask/cask/pull/524

**Comment by milkypostman** [comment]
Can you fill me in on where we use cask?

**Comment by tarsius** [comment]
We use it for CI: https://github.com/melpa/melpa/blob/master/run-ci.sh, https://github.com/melpa/melpa/blob/master/.github/workflows/ci.yml.

**Comment by lassik** [comment]
Seems the GitHub actions version of Ubuntu has both Python 2 and 3 installed by default. If https://github.com/cask/cask/issues/498#issuecomment-803116040 is implemented so that Cask uses `#! /usr/bin/env python3` to automatically pick the right Python then we shouldn't have to do anything on MELPA's end.

**Comment by lassik** [comment]
However, MELPA should still switch to the new way to install Cask by cloning the git repo instead of using the `go` script.

**Comment by lassik** [comment]
The above PR's now got everything covered as far as I can tell.

**Comment by tarsius** [comment]
@milkypostman we *only* use it for CI (I think), so actually you don't have to update anything.

**Comment by milkypostman** [comment]
Will it “just work” or do I perchance need to update some script?

**Comment by riscy** [comment]
I was looking at this a little while ago [here](https://github.com/melpa/melpa/compare/python36-for-cask) and I thought the cleanest path would just be to update Ubuntu (so that we don't have python2 installed on the worker, thus no disambiguation).

As far as I can tell inside the melpa/melpa repository, we only use cask to prepare the worker to attempt to install the package, e.g. from ~/run-ci.sh:
```bash
~/.cask/bin/cask emacs --batch --eval \
    "(progn (add-to-list 'load-path \"$PWD/package-build/\")(load-file \"package-build/package-build.el\")(package-build-archive \"$recipe_name\"))"
```
I'm not seeing any other reference to it, but I don't have a deep understanding of the MELPA build process.

**Comment by riscy** [comment]
Maybe this issue is also an opportunity to ask whether we want to rely on the latest version of Cask, or whether we want to target a specific version and only upgrade when we're ready to test for regressions.  q.v. https://github.com/melpa/melpa/pull/7487

**Comment by dickmao** [comment]
Since you `git subtree` package-build, it's not clear why you introduce cask at all.

`cask` does however solve just as many problems as it creates, in particular, it's more or less required if you want to #4154 (Automate Purcell).  It can also get rid of the git subtree of package-build, altogether.

**Comment by riscy** [comment]
Cask has been a part of the MELPA build for a long time, so my hunch is that just ripping it out would bring problems to light that aren't front-of-mind.  But I do see your point.

In any case, I took a quick look at Cask's recent development and it seems to be change way more rapidly than I thought, with frequent pushes to its master branch.  It also seems to [add a package repository](https://github.com/cask/cask/commit/a05bdf9451db4717c169c9804f0c5259ca2d3a71) that conflicts with MELPA, which hosts a forked version of origami with the same name.

I think this is a good time for MELPA's CI to pin to a specific version of Cask, which will give us a bit more breathing room to test for regressions.  I've opened a PR to do this [here](https://github.com/melpa/melpa/pull/7488) and address some of the issues above as well.

**Comment by dickmao** [comment]
> It also seems to add a package repository that conflicts with MELPA

I'm not party to that amendment, but I wouldn't take it very seriously.

**Comment by akirak** [comment]
> It also seems to add a package repository that conflicts with MELPA, which hosts a forked version of origami with the same name.

Addition of CELPA has been suggested in several places, and I am **not** welcome to the change. Since one of the important roles of MELPA is curation, it should not depend on a more liberally curated set of packages. In Nixpkgs, it was turned down (and I was behind the decision): https://github.com/NixOS/nixpkgs/issues/103047

**Comment by milkypostman** [comment]
Let me do my best to summarize what I understand is going on here,

- Cask updating to Python3
- Our CI is based on using Cask to easily load a base set of packages needed for `package-build`. But other than that, it's not really part of our process. *It's not used for building packages.*
- There were two PRs I have seen: #7484 by @lassik and #7488 by @riscy. @lassik has said that #7488 is the way to go and closed #7484.

I wanted to summarize because based on email notifications for this issue and PR -- and also cloned repo by @dickmao which referenced this issue 😈 -- I was a bit confused. This may help others that arrive later.

❤️

**Comment by dickmao** [comment]
> This may help others that arrive later

With all due respect, the preceding comment does nothing of the sort.  Here is a conciliatory :heart:.  In the words of Ari Gold, I cannot promise to be kind, but I'll always apologise afterwards.

As of https://github.com/cask/cask/commit/d1ee01ba3c06a62e784c3982ad6f50dbabf5c00f Cask is a bash script.  Cask has nothing to do with python at the present moment.  The chicken little of https://github.com/cask/cask/pull/524 inciting this python2/3 consternation was the ill-advised, unilateral action of an inexperienced, overeager, but well-meaning cask maintainer.

Your CI currently has no need for Cask.  And yes, it is also not needed *for building packages* (italics original).

My recommendation is to close #7488 and #7484 out of hand, and stay the course.  With possibly a few tweaks, recipe registration should continue working as-is.

**Comment by milkypostman** [comment]
Ah, I see. Although a bit cryptic, I now see your point.

Still #7488 makes a lot of sense here. It will,

1. Remove our dependence on the `go` script which is the thing that is going to move to Python3 and, in my opinion, a bad way to install software.
2. Updates to the latest-1 version of Emacs.

While the original motivation may have been this discussion about Python, this does fix the issue.

I think it'd be valuable to see (from a PR) how we remove our dependency on Cask. I'm not going to go try to find the history of when that dependency was added, maybe @purcell knows, but ultimately if someone wants to submit the PR I'm here and listening and will review.

**Comment by dickmao** [comment]
> I think it'd be valuable to see (from a PR) how we remove our dependency on Cask.

[You got it](https://github.com/melpa/melpa/pull/7491).

**Comment by tarsius** [comment]
Can we close this now?

**Comment by riscy** [comment]
Yes, I think we're all set on this one since efd78c643a0ebfe006e87e9e950dd056d04a1b37 -- I'll go ahead and close.
