### ISSUE TITLE
Will performing a large rebase on packages mess up MELPA building?

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#7508]
Hello,

I am terribly fickle with my git author name/email info in my commit histories. I'm considering performing a `git rebase --root` on a couple of packages to shake out these inconsistencies.

Will this mess up MELPA building these packages?

Thanks.

**Comment by purcell** [comment]
You're probably making life more complicated than you need to, but it won't mess up MELPA afaik: so long as the tags and commit dates remain unchanged, and the commit history overall remains consistent, there will be no user-visible effect.

**Comment by purcell** [comment]
`package-build` basically does a hard reset to the head of the default branch (or latest stable tag, for MELPA Stable) each time it builds, which is why this should continue to work. Timestamp versions for MELPA are determined by the time of the most recent commit to modify any of the files included in the package.

**Comment by rnkn** [comment]
Thanks @purcell, and yes, making life more complicated for myself than need be is one of my key strengths.

**Comment by purcell** [comment]
> yes, making life more complicated for myself than need be is one of my key strengths.

We are software engineers, after all. 😁
