### ISSUE TITLE
problems with matlab emacs in melpa

### ISSUE THREAD

**Issue by ouboub** [melpa/melpa#7523]
Hi

I am one of the maintainers of matlab emacs, whose development takes
place in https://sourceforge.net/p/matlab-emacs/src/ci/master/tree/
and which is also mirrored github
git@github.com:matlab-mode/mirror.git

Be it as it may, I and submitted some months ago (and don't recall all
the details) recipe file for building matlab emacs pointing to the
github mirror.

Now it turn out, after receiving some bug reports by melpa users (I
use myself the master version from our repositories), that the
following links are not correct

    1. Source: it reads https://git.code.sf.net/p/matlab-emacs/src 
       instead of https://sourceforge.net/p/matlab-emacs/src/ci/master/tree/

    2. Homepage should be
       https://sourceforge.net/projects/matlab-emacs/

However worse is that the build process is not correct, when compiled
from master a matlab-load.el is generate which is absent in the melpa
version.

Since I forgot the details of the melpa recipes, I would appreciate if
someone could tell me how to solve these issues.

Thanks and regards

Uwe Brauer

**Comment by purcell** [comment]
> However worse is that the build process is not correct, when compiled
> from master a matlab-load.el is generate which is absent in the melpa
> version.

This is how MELPA works: we don't perform any server-side build steps or compilation defined by authors, for security reasons. If there's a `matlab-load.el` file you need to ship, then it would have to be included in the repo. 

*However*, such `-load.el` files are generally manually-maintained files that mostly contain autoloads, and autoloads *are* generated from the package source code at installation time, so the best solution is usually to set up the elisp code properly with `;;;###autoload` cookie comments, such that package installation will do the right thing, and then you can generate the `-load.el` file yourself as part of a script for non-`package.el` usage by using the same autoload file generation functionality built into Emacs.


Regarding the homepage link issue, that is taken from the package metadata, so if you have a `-pkg.el` file then it should go in there, or if you just have package metadata in the main `.el` file then you should add a `;; Homepage:` header.

The source link is auto-generated from the URL in the recipe, and our code for that was wrong. I've fixed it now, and the link will point to https://sourceforge.net/projects/matlab-emacs/, which is a little better. That change will take effect in the next build cycle.

**Comment by purcell** [comment]
I took a quick look at your repo, and indeed your `matlab-load.el` file does indeed appear to be produced by extracting autoloads. So two points about that:

1. That wouldn't be entirely safe to generate on the server and then distribute, because the autoload generate process can differ from Emacs version to Emacs version. For example, autoloads generated with Emacs 27 might not work with an Emacs 25.x.
2. The file will be redundant in the MELPA case, because a (presumably identical) `matlab-autoloads.el` will be generated by `package.el` at installation time and loaded automatically at startup time. Probably what you need to do is update any installation instructions to reflect this and avoid confusion.

**Comment by tarsius** [comment]
I assume you were satisfied by Steve's answers.
