### ISSUE TITLE
Melpa no longer updating

### ISSUE THREAD

**Issue by jcs090218** [melpa/melpa#7642]
I think the system no longer pulling the latest version? This may due to recent commits from @tarsius? 😕

**Comment by tarsius** [comment]
I noticed that very late last night and was hoping that https://github.com/melpa/package-build/commit/cbb9f6174a74fa390909c588c60ba6d05c5ba873 / https://github.com/melpa/melpa/commit/4e7a0f8a71efead4ad890085bbc77f3d331df2a9 would fix it.

This happened because the tests only test whether beginning to package a new package works but not whether updating a package that is already being packaged also works.

**Comment by tarsius** [comment]
I don't understand why its not starting to build again now that this has been fixed. Both cloning and pulling work when I test locally.

**Comment by tarsius** [comment]
Oh, there seems to be a second problem. I'm on it.

**Comment by tarsius** [comment]
https://github.com/melpa/package-build/commit/db227b020f2f8c0161eccec16cc9122e802ed543 / https://github.com/melpa/melpa/commit/4e7a0f8a71efead4ad890085bbc77f3d331df2a9 should fix that too.

**Comment by jcs090218** [comment]
I don't know what fixes the issue, but by seeing the Melpa's website, the last timestamps is `php-scratch` with version of `20210706.459`.

**Comment by tarsius** [comment]
I just noticed that I forgot to push. I have done that now. Everything should be fine after the next full update round.

**Comment by jcs090218** [comment]
@tarsius Thanks for the quick fix! ;)
