### ISSUE TITLE
Stable distfiles

### ISSUE THREAD

**Issue by houseofsuns** [melpa/melpa#7856]
Hi,

I'm trying to improve the integration of melpa with Gentoo and I noticed that some files changed content without changing name. Take for example the helm-core package which currently provides helm-core-3.8.2.tar; this file (as observed by its checksum) changed between last year and now without changing name.

My question: Is this intended behaviour? Has the code actually changed without the version being increased? Or is this merely some artefact?

For my use-case it would be best if each file were stable and did not change. If this is not possible I'll have to think about how to handle this on my side, but before going all out on this, I wanted to ask whether I'm just "holding it wrong"?

**Comment by aplaice** [comment]
(Disclaimer: Not a MELPA maintainer)

I don't think that there are any _guarantees_ that the package files will be immutable. Some reasons why their contents might change:

1. The source repository of the package changes what the relevant tag points towards. (Unlikely but possible.)
2. The recipe of the package might change in melpa.
3. MELPA's `package-build` (the build machinery) might be modified, resulting in a slightly different output (e.g. slightly different metadata). `package-build` is stable and rarely changed, so it'll occur infrequently, but not never. (You could maybe check whether this was the reason in this case by building `helm-core` with an older version of `package-build`, by yourself, and comparing hashes?)

(AFAIU already built package files usually aren't regenerated, but sometimes the entire build process/infrastructure is restarted from scratch.)

**Comment by houseofsuns** [comment]
Thanks for the input. I discovered that on the package page one can see the last build log. It seems that today helm-core was rebuilt at least four times (2022-01-09T10:50:01+0000, 2022-01-09T13:44:26+0000, 2022-01-09T16:39:38+0000 and 2022-01-09T19:35:31+0000) every time referencing the same upstream commit 94cf15. This feels strange.
Even if reproducible builds would be off the table this indicates quite some wasted CPU cycles of busy work.
Additionally there is what looks like a listing of the distfile content on the package page which indicates changing time stamps which of course would explain the changing checksums.

**Comment by milkypostman** [comment]
@houseofsuns This is all correct. I will try to address things in this thread here,

- I don't know if integration between MELPA and Gentoo is a great thing. MELPA is just a place to build packages that work with the `package.el` package in Emacs core. It's intended to be like doing `git checkout` in a local directory except that because we integrate with `package.el`, we get dependency management for free. As well as byte compilation at install time that `package.el` provides.

- MELPA stable is *really* not our top priority. It was added a user feature and there have been a lot of discussions about getting rid of stable because it's a maintenance overhead. Also, we don't control the versions. Developers can tag their code with a version label and we will build their package, but they could go back and tag the same reversion to different code later and it may change.

- There are also cases where with core MELPA (building from head) we can get weird timestamp problems due to a merge commit having a timestamp that is earlier than the previous build but this has mostly gone away because people tend to rebase nowadays rather than merge.

- We always rebuild because (i) we are already paying for the CPU resources to host the server, whether we use the cycles or not so it doesn't seem that bad to just rebuild every time, and (ii) it would be drastically more complex to write and maintain code to "decide if something has changed". We already have to maintain the local git repository so doing a `pull` and then comparing files and trying to manage a checksum means we may as just do the rebuild. The simplicity has treated us well over the years. It allows us to completely rebuild MELPA at any time. Also, `package.el` doesn't rely on a checksum for installation so it doesn't install packages unless the actual version number changes.

    If I remember correct, MELPA was originally *push* based, where I had setup hooks so that repros could ping the server to kick off a new build of their package but it was decide to not do this anymore as the added complexity wasn't worth it. This was when the server code was actually written in Python I think and when we moved to elisp it just didn't seem worth it.

I guess I'm curious why Gentoo needs MELPA anyways. It seems like just additional complexity. It would be easy to adapt the melpa/package-build code to be something that builds packages for Gentoo specifically.

**Comment by houseofsuns** [comment]
@milkypostman Thanks for the detailed response. I see that my use-case is simply not aligned with melpa's design.

The example I looked at (helm-core-3.8.2) probably was not typical. There a simple check of the git revision would have been all to check whether anything changed, so the state to be kept would have been quite minimal. But I also see the elegance in the stateless design of simply doing a rebuild every time.

The main upside of consuming MELPA is gaining access to the package selection / index (especially as it includes machine-readable dependency information). It is totally possible (and often probably quite easy) to create Gentoo packages (called ebuilds) for individual upstream projects (like helm-core). However all of them need to be maintained somehow so it's attractive to reuse your work and generate the ebuilds automatically from the MELPA directory.

There actually exists a working solution for the integration (named gs-elpa) which however has the drawback that it needs to dynamically fetch "random" code from the internet on package install. This I wanted to rectify by adding checksum digests for the distfiles, thinking that the current Gentoo solution simply stopped at an easy working stage. However it is impossible if the source does not offer stable distfiles (not implying any fault on your part, it's simply not in your design).

Also the integration gs-elpa is part of a framework (named g-sorcery) that is intended to provide interfaces to all kinds of package directories (like PyPI, CTAN, ...) so that we can utilize one piece of infrastructure on the Gentoo side to access lots of package directories. And for example in the case of PyPI adding checksum digests should be feasible as they have stable distfiles so far as I know.

**Comment by milkypostman** [comment]
actually I think we do already keep the commit checksum for the package as part of the build process, but I wouldn't want to "guarantee" it would never change. Some day we may lose the package directory and it would cause the metadata to be lost.

I would definitely encourage you to look somewhere else for "stable" package building because our stable system is not the main focus of our work here. But you can feel free to rely on the recipes here in the format they exist. There are other projects that use our repo of "recipes" to do their own thing. 

It would be fairly easy to build something that does what you want starting with the package recipes and bits of the melpa/package-build library. But it would certainly take some time and custom code.

Sorry we can't be of more help out of the box. Best of luck!
