### ISSUE TITLE
Add 552 packages from emacsmirror (discussion)

### ISSUE THREAD

**Issue by BenediktBroich** [melpa/melpa#7892]
Hello,

so i was trying to get some packages to melpa and found this [emacsmirror Package List (552)](https://emacsmirror.net/stats/melpa.html). The list ist described as:
"Many mirrored packages are actually missing from Melpa. [Here](https://emacsmirror.net/stats/melpa.html) you can find some lists of such packages, in case you would like to help making Melpa more complete."

I had the following idea: 
I could write script that forks the given repository's, add a pull request for a workflow like [melpazoid](https://github.com/melpa/melpa/issues/new) to these repos and automate the recipe commits to melpa.

So i wrote it: [melpify](https://github.com/BenediktBroich/melpify)

I can add these packages one by one and fix there issues, but i can also just add all the recipes so you can join. 

What do you think about this? Any ideas?

Vote:
Just Do It! 👍
Stop it. Get some help. 👎

**Comment by milkypostman** [comment]
Thank you for sending this issue before sending the PRs. I am a 👎🏼 on this simply because I want to avoid cruft. I mean, there are other reasons too (see the PR checklist we have).

Probably at some point we need to look at the packages we have and say "If a package hasn't been downloaded in N years, let's get rid of it". But that's kinda the same thing here, where I think it's worth someone actively *wanting* a package as motivation for adding it. Because ultimately there is a maintenance cost to having many packages in MELPA.

I don't think you need help, this is a well-intentioned and appreciated approach to MELPA but I don't think it's healthy for the project.

I will leave this open for discussion incase someone else wants to chime in. Thanks again.

**Comment by Boruch-Baum** [comment]
I just took a small peek at the list (ie [emacsmirror Package List (552](https://emacsmirror.net/stats/melpa.html) and can immediately report that it's not accurate. It reports package [w3m](https://github.com/emacs-w3m/emacs-w3m) as not being in melpa due to that project's choice of version control; however, the package *is* in melpa, and did switch to git version control several years ago.

So, it's a good thing you didn't blindly dive in and devote effort solely based upon the list. The list seems to have been created fairly recently, by @tarsius, so I'm mentioning him so he gets this as a heads-up.

**Comment by tarsius** [comment]
@Boruch-Baum Well I wouldn't call it "fairly recent" but "surprisingly outdated". Now that I have heard from someone actually using it, I will try to update it more often or maybe even automate it. Even so it might at times be a week or two behind.

By the way you looked at another list from the same page as the list Benedikt worked with. I have removed that list a while ago (but not published the html until now) because it indeed is not accurate/relevant anymore.

@BenediktBroich A more recent (though potentially also slightly outdated) version can be found at https://github.com/emacsmirror/epkg-reports.

The code-block used to generate that list comes with a second variant that is commented out because I considered it to be too slow. It seems fast enough to me now, so I just switched to that variant. Have another look. The list is sorted by upstream url but it might be more useful to sort by last-modified date. Changing the order should be easy if you use the org file instead of the html export.

**Comment by BenediktBroich** [comment]
Thanks for all you reply's. 

@tarsius The [epkg-reports](https://github.com/emacsmirror/epkg-reports) is perfect for finding new packages. Next to the modified date I think about adding Github stars and forks to better decide what project would be good to add to melpa. And i will create a checklist with all the points to check and where to check them.

I would be good to have a list of deleted packages, as well as duplicates (function wise) and not responding, or no longer mainained. @milkypostman @Boruch-Baum Do you have a list of packages that were already deleted from MELPA? Is there a way to organize this.

**Comment by tarsius** [comment]
> I would be good to have a list of deleted packages

```
git log  --pretty=format: --name-only --diff-filter=D recipes | sort -u
```

(This also includes packages that have since been added back.)

> as well as duplicates (function wise)

For that someone has to go through all packages, spending a few minutes to analyze and categorize each, while improving the categories in the process. It would be nice to have the result of that available but someone has to do it first. Of course one could start small by only categorizing a subset of packages or using only basic categories such "major-mode for a specific programming language" / "additional functionality for a certain programming language" > "the language", "general purpose text editing utility", "client for a certain service" > "the service"; while allowing for some level of mis-categorization. Are you volunteering? :smile: Of course it would be best if a multiple people worked on that and if they repeatedly exchanged notes to improve how packages an classified and go back to the already classified packages where necessary...

**Comment by Boruch-Baum** [comment]
On 2022-02-08 12:59, Benedikt Broich wrote:
> ...
> ***@***.*** ***@***.*** Do you have a list of packages that
> were already deleted from MELPA? Is there a way to organize this.

Not me. This is all beyond my expertise.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by BenediktBroich** [comment]
I am working on it [branch](https://github.com/BenediktBroich/melpa/tree/categories/html).

![Screenshot_20220211_003955](https://user-images.githubusercontent.com/32903896/153515811-c21aa052-62b5-4f1b-944f-985c5f695b2b.png)

![Screenshot_20220211_004045](https://user-images.githubusercontent.com/32903896/153515820-bb909b6e-ff1d-4417-8ec8-e3b335b5062b.png)

![Screenshot_20220211_004110](https://user-images.githubusercontent.com/32903896/153515829-1faa07fd-739a-43bd-8d5b-e5dc3b331783.png)

**Comment by tarsius** [comment]
In summary, some of these package should be added, but to avoid overwhelming the reviewer, the person who opens the prs (one per package), should try to resolve any issues from the checklist.
