### ISSUE TITLE
homepage for package 'annotation'

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7893]
Using the melpa online package search, the page for melpa package [annotation](https://melpa.org/#/annotation) points to the home page of the `agda` programming language. The melpa recipe format presumes that the home page of a fetcher repository is the home page for the emacs/melpa packge, but in this case, this isn't so. What amounts to the emacs/melpa package is just one of nine elisp files in one [sub-sub-sub directory](https://github.com/agda/agda/tree/master/src/data/emacs-mode) of the `agda` project.

Thus, in this case, the melpa link to the 'home page' is confusing and not useful.

A little digging brought me to a description of the agda repository [emacs-mode](https://agda.readthedocs.io/en/v2.6.2.1/tools/emacs-mode.html), but even that wasn't helpful for information about package `annotation`.

I see that the emacs-mirror does not seem to mirror this package, in that a search yields no result...

My opinion is that a melpa package should have a discoverable home page, but without feedback from melpa, I have no basis to make any suggestion directly to the package owner.

**Comment by tarsius** [comment]
> Using the melpa online package search, the page for melpa package [annotation](https://melpa.org/#/annotation) points to the home page of the agda programming language.

I think that could be changed by adding a `Homepage` header to `annotation.el`.

> Thus, in this case, the melpa link to the 'home page' is confusing and not useful.

IMO it is not optimal but better than not knowing what repository the package comes from.

> I see that the emacs-mirror does not seem to mirror this package, in that a search yields no result...

The Emacsmirror mirrores complete repositories, while Melpa sometimes splits up a repository into multiple packages. Actually the Emacsmirror sometimes only mirrors a subdirectory of repository. Trimming down the history of a single subdirectory is simple enough, while extracting the history of arbitrary files is a major pain.

`annotation` is affected by this. On the Emacsmirror it is part of the `agda2-mode`, which contains all the files in the `src/data/emacs-mode` repository.

> My opinion is that a melpa package should have a discoverable home page, but without feedback from melpa, I have no basis to make any suggestion directly to the package owner.

Ask them to add the `Homepage` header but maybe wait for someone else to confirm that that is actually used on the webpage. I am fairly confident it is but am not familiar with the javascript side of things.

Ideally `annotation` should be maintained in its own repository since (as far as I can tell) it has nothing to do with the Agda language. That would make it easier/less intimidating to contribute to that package (i.e. to add actually useful information to the library commentary).
