### ISSUE TITLE
What to do with packages that work in old emacs versions, but not in emacs 27.x?

### ISSUE THREAD

**Issue by BenediktBroich** [melpa/melpa#7898]
Hey,
i was [contributing](https://github.com/mickeynp/ligature.el/pull/37) to ligature mode, when the following [Issue](https://github.com/mickeynp/ligature.el/issues/28) emerged. I read in the docks that Package-Requires can only be used to state a minimal version number. So maybe you can answer me the following question.
 
- What to do with packages that work in old emacs versions, but not in emacs 27.x? But maybe again in emacs 28?
- Does Emacs's package.el respects a version check for itself?

**Comment by tarsius** [comment]
> What to do with packages that work in old emacs versions, but not in emacs 27.x? But maybe again in emacs 28?

I would say it is up to the package maintainer. The could depend on 26  and show an error popup when someone tries to use it with 27. Or they could depend on 28, either publishing it on melpa now or waiting for 28 to be released. @mickeynp has decided to wait. Personally I would publish now for the reason given by @rski. But it is up to Mickey and I don't think we should have a general policy, not least because this must be a very rare situation.

> Does Emacs's package.el respects a version check for itself?

If "itself" refers to `package`, then I fail to see how that is relevant. If `emacs`, then yes.
