### ISSUE TITLE
issues with magit recipe

### ISSUE THREAD

**Issue by baron** [melpa/melpa#7943]
@tarsius the recipe excludes "magit-section.el" which is needed for the "magit--propertize-face" in order for magit to function.

see:
https://github.com/magit/magit/issues/4626

https://github.com/melpa/melpa/blob/144364ae1ab127dd4e630a848741eb561e00ab24/recipes/magit

**Comment by tarsius** [comment]
@baron said:

> Unable to use magit when installing the latest version from MELPA, I get the error "Symbol's function definition is void: magit--propertize-face".
>
> I can see that "lisp/magit-section.el" is excluded from MELPA and was missing from my local installation.
>
> https://github.com/melpa/melpa/blob/master/recipes/magit
>
> Issue was resolved by manually downloading "magit-section.el" and loading file contents.

**Comment by tarsius** [comment]
`magit-section.el` is distributed as a separate package `magit-section`, which is a dependency of the `magit` package. I don't know why Package did not install `magit-section` for you when you installed `magit`. To fix it I recommend you `package-install` `magit-section` explicitly instead of fetching the library manually.
