### ISSUE TITLE
Deprecate/drop library "a"

### ISSUE THREAD

**Issue by minad** [melpa/melpa#7977]
I've seen that https://github.com/plexus/a.el is marked as "sunsetting":

> This library is sunsetting, you are advised not to use it on new projects.

Unfortunately it seems that the library is still picked up by recent packages, e.g., [blamer](https://melpa.org/#/blamer) and [code-review](https://melpa.org/#/code-review). Is there any way to prevent this from happening? Would it make sense to drop "a" from MELPA, forcing the depending packages to replacing the usage of "a" with simple builtins? Overall not many packages depend on "a", so it seems feasible to do this. Maybe that step is a bit radical. One should probably ask the maintainer of "a" about their recommendation.

**Comment by minad** [comment]
@plexus Your README is unclear in that respect since you marked your library as "sunsetting". I wonder if MELPA should establish some guidelines such that new packages avoid building upon libraries which are not supposed to be used in newer projects. Note that the aforementioned "blamer" and "code-review" packages are recent developments. It makes sense that the maintainers of these new packages are at least informed about the remark in your README. I think it is not good if new package dependencies are created in this case, even if there is no technical problem with your "a" package per se. I've also observed a few times that @tarsius dropped packages from the MELPA repository, which were archived.

**Comment by alphapapa** [comment]
FTR, I would not be interested in maintaining this package, and I agree with Arne that the status quo seems fine.

**Comment by plexus** [comment]
Thanks for clarifying @minad. `a` is not in active development, and we somewhat discourage new usage because there are better alternatives, but it's all fairly straightforward code that will continue to work for a long time, so it's not problematic per-se that people use it. In a sense not being in active development is a plus here, it is highly unlikely that we'll ever introduce a breaking change.

Deprecated does not always mean bad. There are APIs in Java that have been marked as deprecated for 20 years because better alternatives exist, but if you understand the trade-offs you can still use them just fine. They are not being removed because there is no reason to, and it would break a lot of existing software that is still working fine. Don't break userspace. Don't break downstream consumers. These are great values to hold.

`a` is inspired by Clojure, and in that ecosystem this kind of stability is highly valued. I hope that if packages are dropped from MELPA it's for very good reasons, like a security exploit, or someone sneaking in a bitcoin miner, and not for something like having the word "sunsetting" in its README.

**Comment by tarsius** [comment]
> I've also observed a few times that @tarsius dropped packages from the MELPA repository, which were archived.

I only do that if they have been archived (or deleted) and no other packages depend on them.

I agree that nothing has to be done here. Except maybe update the comment in the readme, because the used term implies that while the sun has not gone down yet, it eventually will:

> sunsetting
> (of a programme, agency, regulation, etc.) expire or be terminated automatically at the end of a fixed period unless renewed by legislative action.

**Comment by tarsius** [comment]
You could also explicitly mention the better alternatives.

**Comment by plexus** [comment]
I already do.

**Comment by plexus** [comment]
Thanks everyone for chiming in. I've updated the README to elaborately clarify the project status, and to help people make informed decisions. After having another look at the landscape I can understand why people would still choose to build on a.el, and I think that is ok, as long as they are aware of the trade-offs.

tl;dr

- your package can't be included in GNU ELPA if you use a.el
- a's value semantics can be costly
- your code will become easier to work on by people coming from Clojure, but harder for experienced elisp devs
- it's an extra dependency you may not need

https://github.com/plexus/a.el#project-status

**Comment by tarsius** [comment]
Assume!

**Comment by cadadr** [comment]
Next time can you please do some due diligence before @'ing a bunch of people about a non-issue?
