### ISSUE TITLE
Maybe add more host-specific fetchers

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8043]
In #8040 @ideasman42 proposes that we add a dedicated fetcher for https://codeberg.org.

I am not sure the time for that has come yet, but if we do add that fetcher, then we should also add a few others.

Here are all the git hosts that are not specific to one person/project:

| Host                     | Repos | Accounts |
| ------------------------ | ----- | -------- |
| codeberg.org             |    49 |        9 |
| git.sr.ht                |    40 |       18 |
| repo.or.cz               |    23 |  unknown |
| bitbucket.org            |    16 |       12 |
| framagit.org             |     7 |        1 |
| git.savannah.nongnu.org  |     3 |        1 |
| git.code.sf.net          |     3 |        1 |
| gist.github.com          |     2 |        2 |
| scm.osdn.net             |     1 |        1 |
| gitee.com                |     1 |        1 |
| git.savannah.gnu.org     |     1 |        1 |

Maybe we should add fetchers for the first four, or maybe we should wait until they have gotten more popular.  We don't really gain much by adding dedicated fetchers.

**Comment by minad** [comment]
I think support for codeberg and srht is justified - these two forges seem worth to recommend based on their policies. In contrast gitlab seems to move to a model which is less friendly to FOSS?

**Comment by akirak** [comment]
[Nix](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html) has dedicated URL schemes for sourcehut and github. It would be nice if there were support for sourcehut.

The service is quite different from github and gitlab, though:

- Sourcehut hosts both Git and Mercurial repositories. I think most users of the service are using Git, but it would be necessary to add a note on how one should refer to Hg repositories on the service.
- User names are prefixed with `~`, which can be more prone to errors.

**Comment by tarsius** [comment]
#8170 starts using the new `codeberg` and `sourcehut` fetcher types. Obviously I have to merge the respective changes to `package-build` first.

@melpa/maintainers do you agree with adding these two fetchers?

IMO it would make less sense also adding `bitbucket` and `framagit`; those are on a downward trajectory.

I would like to keep the types/classes used by Melpa and the Emacsmirror in sync as much as possible. So I'll teach the Emacsmirror about `codeberg` as well.

The Emacsmirror also has dedicated fetchers for git.savannah.nongnu.org and git.savannah.gnu.org, but those don't make much sense for Melpa at this time. The Emacsmirror mirrors more packages from there than Melpa; 8 resp. 10, but that isn't much either.

But there are three more fetcher types I meant to ask about for a long time: `emacsmirror`, `emacsattic` and `emacsorphanage`. Adding these types would make a lot of code on the mirror side simpler. In particular it would help simplifying code involved in comparing Melpa and the mirror for the purpose of detecting packages that have been moved in one archive but not yet the other. How do you feel about adding these new fetchers as well?

Also, it isn't great that Melpa needs to get any packages from these three organizations -- using dedicated fetcher types could possibly help keeping track of the issue.

(As a side-note, the Emacsmirror benefits from specialized types/classes much more than Melpa. For example using the Github API determining which packages need to be updated is a lot faster than "fetch & see" as is done for packages hosted elsewhere (resp. all repositories when using `package-build`).)

**Comment by riscy** [comment]
I don't do any package-build maintenance. But I think if this makes code on the mirror side simpler, it's probably worth doing.  However,  one concern I have with these new fetchers is that MELPA may not be the only consumer of MELPA recipes.  For example, will [straight.el](https://github.com/radian-software/straight.el) break on these specific kinds of recipes (I am not yet a straight.el user, so I don't actually know)?  Should we make their maintainers aware?

**Comment by akirak** [comment]
I consume MELPA recipes in my project. This change is fine for me (it's easy to fix), and it will benefit many people who authors recipes.

Here is a list of other projects I know of which will be affected by this change:

- [quelpa](https://github.com/quelpa/quelpa)
- [elpaca](https://github.com/progfolio/elpaca): The author is active at present

I think people who maintain a system consuming MELPA recipes should watch updates in package-build. It was nice of you to make an RFC for an important change like this, because it gives the maintainers to prepare for it.

**Comment by milkypostman** [comment]
Dedicated fetchers seem reasonable. It's just more maintenance for the maintainers, mostly @tarsius since most of `package-build.el` is owned my them. But it's essentially a mapping from target to URL scheme so I don't think it's that much complexity.

**Comment by tarsius** [comment]
I've pinged some off the affected folks using https://github.com/melpa/package-build/issues/63.

**Comment by alphapapa** [comment]
Interesting.  Not to argue with the proposed changes, but I've long wondered what benefit there is to having these host-specific fetchers instead of just using URLs.  Jonas said that the GitHub API allows more efficient checking for updated repos that fetching with git, which seems like a good reason, but is that being done?

It seems to me that using host-specific fetchers has some downside as well.  For example, every host will have the URL for a repo available for copying and pasting, which a user should need no further research to use.  But to use a host-specific fetcher requires the user to look up whether a host has a specific fetcher and how to use it.  It may also require the user to update some software to install a version supporting newer fetchers, while the URL-based one would always work.  As well, if a repo host changes something on their end which breaks a fetcher, users would have no recourse but to wait for the software to receive updates to support the new fetcher--but if the URL were used and the host changed it (which seems very unlikely, given the potential for breakage), the users could easily update the URLs in their configurations without waiting for other software to update.

Given these considerations, IMHO we should tend toward using fewer host-specific fetchers and using plain URL-based fetchers instead.

**Comment by alphapapa** [comment]
> Some forges support Git's unsafe
> native protocol, Github did that until fairly recently. We don't want
> that, so we would always have to double check that that isn't being used.
> Sometimes we would forget to do so.

To solve that, could "we" (since I'm just pontificating here, not contributing actual work) just require URLs to use HTTPS?

> Given that we already have two fetchers for proprietary forges ("open core" in the case of Gitlab), adding new fetchers for two free forges doesn't seem to complicate things much.

No, but it would likely open the door to "just a few more..." and "why not this one?"  ;)

Anyway, not my problem, just my two cents.

**Comment by tarsius** [comment]
Merged!
