### ISSUE TITLE
jedi in melpa should depend on jedi-core from melpa not melpa-stable

### ISSUE THREAD

**Issue by paaguti** [melpa/melpa#8051]
The `jedi` package depends on `jedi-core` in melpa stable and that creates a lot of annoying traffic in the minibuffer.
Making `jedi` depend on the melpa `jedi-core` silences all that traffic and gives a better user experience.

I'm currently solving this by adding this in my .emacs.d/init.el

```(use-package jedi-core
  :after python
  :pin melpa
  :ensure t)

(use-package jedi
  :after jedi-core
  :pin melpa
  :ensure t
...
```
But the `use-package jedi-core`can be avoided by fixing the dependencies

**Comment by akirak** [comment]
As far as I know, there is no point in using MELPA Stable (#6656). I would suggest simply dropping the configuration for MELPA Stable from your `package-archives` (or make MELPA precede over MELPA Stable).

MELPA itself doesn't specify which package registry `package.el` selects as a preferred source. It is determined by your package manager.

**Comment by paaguti** [comment]
But jedi in melpa specifies a dependency on jedi-core 0.2.2 and that is melpa-stable and produces a whole lot of messages
/PA

Enviado desde mi iPhone

**Comment by akirak** [comment]
@paaguti What's the value of your `package-archives`?

**Comment by tarsius** [comment]
Until we use a different versioning scheme, this is how it works: foo depends on, say bar-1, which would be satisfied by bar-1, bar-1.1... or *any* snapshot from melpa (because a timestring YYYYMMDD is larger than 1).

There is nothing special about this pair of packages; unfortunately this is how it (currently) works for all packages.
