### ISSUE TITLE
Introduce melpa-devel

### ISSUE THREAD

**Issue by minad** [melpa/melpa#8135]
I propose the addition of a third MELPA distribution channel MELPA-devel which uses similar version numbers as ELPA-devel. The version numbers would look like 0.8.20150717.123 for example, where the date is added after the version number. By introducing a separate channel we would avoid backward compatibility issues with MELPA(-unstable) and MELPA-stable and at the same time sort out possible versioning compatibility issues, which are a result of the data-based MELPA versioning. In the (very) long term one could deprecate MELPA(-unstable) in favor of this new MELPA-devel scheme. This has been discussed or proposed previously in #2944 and #2955. I would like to revive this discussion.

**Comment by tarsius** [comment]
*[I am currently on a break, but since I am having a bit of a relapse anyway (i.e., I'm working on stuff again), I am quickly responding here as well.]*

I have been working toward this goal for a *long* time, but there always was one more thing that had to be taken care of first. Currently that would be https://github.com/melpa/package-build/pull/61.

I'll work on https://github.com/melpa/package-build/pull/61 and better version numbers in the fall.

I have a different naming scheme in mind, basically `TAG-VERSION.NUMBER-OF-COMMITS-SINCE-THEN`. Of course there are complications, such as when `TAG-VERSION` gains or looses components, or when upstream rewrites history and the number of commits gets smaller. I've thought about such details quite a bit already and believe I have solutions for them, but I don't want to outline that in more detail right now (as that would conflict with my break).

**Comment by tarsius** [comment]
> How about using the version attribute as the only sole source of truth

IMO one problem with "version attributes" (the `;; [Package-]Version:` "header keyword") is that they *cannot* be used as the only sole source of truth. You always have to walk the history to determine the first version that introduced a new version. This is hostly, error prone and can be ambiguous. Bumping only some version strings when creating a release and forgetting about other occurrences is a common mistake.

Also, if you look at a file, which self-identifies as `1.0`, you cannot know if it really is `1.0` (the overwhelming odds are that it is not), or `1.0` plus a thousand commits, and only one commit before `2.0`. Calling that `1.0` is very misleading.

Tags on the other hand are unambiguous and cheap to lookup. I also think that putting version strings inside files that are tracked in a vcs is very 1999. (Nothing against putting version strings inside build artifacts like the packages on the various *elpa.)

I tried to convince Stefan Monnier to change [Non]GNU Elpa to use tags, but we ended up having to agree to disagree.

This puts package authors in the unfortunate position of having to bump the string in the file *and* having to create a tag, while trying to never mess it up. My [`sisyphus`](https://github.com/magit/sisyphus) package can help with that.

> [@tarsius Ignore this if you are still on break.]

So far I am only succeeding in not creating any new things that are going to cause my more work. Or to at least keep them hidden away. Which is why I haven't put `sisyphus` on Melpa yet.
