### ISSUE TITLE
Alchemist.el package doesn't have a maintainer

### ISSUE THREAD

**Issue by Sasanidas** [melpa/melpa#8140]
It has been some time, and it seems like the (popular?) package alchemis.el doesn't have a mantainer anymore.

There were some attempts some years ago to resurrect the project, but for some reason it's not going forward.

The package has a few issues and a some pull requests ready to merge, I think ideally MELPA should point to a fork that is maintain.

At the moment, I raise the issue here https://github.com/tonini/alchemist.el/issues/371

**Comment by tarsius** [comment]
Any progress?

IMO there's not much reason to keep this issue open especially because is also being discussed in the upstream repository. There are many packages that aren't maintained any more.

Thanks for bringing it to our attention though. Ccing @melpa/maintainers in the upstream discussion would achieve the same. If we wanted to track some problem in this issue tracker, e.g., because it concerns a very important package, or because Melpa maintainers are actively involved in getting the problem resolved, we could open an issue here, after being notified elsewhere.
