### ISSUE TITLE
Melpa has the Agda programming language as "functions for annotating text with faces and help bubbles"

### ISSUE THREAD

**Issue by salehmu** [melpa/melpa#8415]
Please check https://melpa.org/#/annotation. The source code points to the agda programming language GitHub repo.

**Comment by tarsius** [comment]
> Melpa has the Agda programming language as "functions for annotating text with faces and help bubbles"

No, it does have `annotation.el` "functions for annotating text with faces and help bubbles", because that file happens to be maintained in the agda repository.

It would be better if that file were maintained in a separate repository. While it is used by `agda2-mode.el`, which is also maintained in that repository, it is implements an ui feature that is independent of agda/agda2-mode. That's why it is distributed as a separate package on Melpa.

Better yet` `agda*.el` would also be moved to a separate repository. See #5361 for similar efforts for other repositories. As you can see a lot of that hasn't been acted on yet and in some cases a lot of communication is required. I don't have the motivation to do the same for this repository as well right now. Maybe you do?
