### ISSUE TITLE
package-build.el only recognizes one maintainer

### ISSUE THREAD

**Issue by petermao** [melpa/melpa#8441]
I'd like org-noter to list at least myself and @dmitrym0 as maintainer, so I have a commit that looks like this:
```
;; Maintainer: Peter Mao <peter.mao@gmail.com>
;;             Dmitry M <dmitrym@gmail.com>
```
but the generated `org-noter-pkg.el` only lists the first maintainer:
```
  :authors
  '(("Gonçalo Santos (aka." . "weirdNox@GitHub)"))
  :maintainer
  '("Peter Mao" . "peter.mao@gmail.com")
  :keywords
```

I couldn't find an example in MELPA with multiple maintainers, so I'm not sure if I made a syntax error in the preamble or if it's a bug in `package-build.el`.

**Comment by alphapapa** [comment]
Use this:
```
;; Maintainer: Peter Mao <peter.mao@gmail.com>
;; Maintainer: Dmitry M <dmitrym@gmail.com>
```

**Comment by dmitrym0** [comment]
Close @alphapapa, the format is here: https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/lisp-mnt.el#L62-L71

so it's gotta be 

```
;; Maintainer: Peter Mao <peter.mao@gmail.com>
;;      Dmitry M <dmitrym@gmail.com>
```

2nd line on has to be `;;<TAB>` 🤷 

@petermao this is what I get when I run `lm-maintainers` now:

    (("Peter Mao" . "peter.mao@gmail.com") ("Dmitry M" . "dmitrym@gmail.com"))

**Comment by alphapapa** [comment]
@dmitrym0 Hm, I feel like I've used the format I described and it worked.  Maybe MELPA has its own parser that handles both formats, or maybe I'm just forgetful.  Thanks.

**Comment by petermao** [comment]
When I run `lm-maintainers` on the file `org-noter.el`, I get the correct answer with `SPACE`s or `TAB` in front of `Dmitry M <...>`, but not with "Maintainer:".

However, when I run the MELPA recipe locally, the second maintainer's name does not show up in the `<PACKAGE>-pkg.el` file.  I thought maybe my customizations were giving me grief, but I tried this under an `emacs -Q` session and the same behavior remained.

**Comment by akirak** [comment]
> However, when I run the MELPA recipe locally, the second maintainer's name does not show up in the <PACKAGE>-pkg.el file.

@petermao I think `package-build` fetches the source file from the remote repository. Have you pushed the change to master in `weirdNox/org-noter` (or pointed the recipe to your repository)?

**Comment by petermao** [comment]
I was using a recipe that pulled from my local drive:
```
(org-noter :fetcher git
           :url "file:///home/<path-to>/org-noter"
           :branch "dev"
           :files ("*.el" "modules"
                  (:exclude "*-test-utils.el" "*-devel.el")))
```
and changed the branch name to try the different options (space, tab, "Maintainer:").  I have verified that the recipe pulls from the intended repo by swapping names around and seeing the change in the output file.

**Comment by dmitrym0** [comment]
I can confirm this behaviour:

- recipe [link](https://github.com/melpa/melpa/compare/master...dmitrym0:melpa:org-noter-update)
- [org-noter.el](https://github.com/dmitrym0/org-noter-plus/blob/merge-with-peter/org-noter.el#L5-L8) from @petermao branch:

```elisp
  ;; Author: Gonçalo Santos (aka. weirdNox@GitHub)
  ;; Maintainer: Peter Mao <peter.mao@gmail.com>
  ;;	Dmitry M <dmitrym@gmail.com>
  ;; Homepage: https://github.com/org-noter/org-noter
```

Running `lm-maintainers` locally gives me the correct list but building the recipe doesn't (some output removed for brevity):


```
❯ make recipes/org-noter
 • Building package org-noter ...
Package: org-noter
Fetcher: github
Source:  https://github.com/dmitrym0/org-noter-plus.git

Cloning https://github.com/dmitrym0/org-noter-plus.git to /Users/dmitrymarkushevich/workspace/melpa/working/org-noter/
Checking out origin/merge-with-peter
Checking out 89221a47f46864f5e1d9927190831e70a5dca0ac
...
...
Built org-noter in 1.333s, finished at 2023-03-13T12:31:43+0000
 ✓ Success:
  8 -rw-r--r--  1 dmitrymarkushevich  staff   523B 12 Mar 19:35 packages/org-noter-20230312.1911.entry
336 -rw-r--r--  1 dmitrymarkushevich  staff   165K 12 Mar 19:35 packages/org-noter-20230312.1911.tar
  8 -rw-r--r--  1 dmitrymarkushevich  staff   522B 13 Mar 05:31 packages/org-noter-20230313.513.entry
272 -rw-r--r--  1 dmitrymarkushevich  staff   135K 13 Mar 05:31 packages/org-noter-20230313.513.tar
```


```bash
❯ cat packages/org-noter-20230313.513.entry
...
	     (:authors
	      ("Gonçalo Santos (aka." . "weirdNox@GitHub)"))
	     (:maintainer "Peter Mao" . "peter.mao@gmail.com")
	     (:keywords "lisp" "pdf" "interleave" "annotate" "external" "sync" "notes" "documents" "org-mode")
	     (:url . "https://github.com/org-noter/org-noter"))])
```

**Comment by tarsius** [comment]
Step one is to teach the low-level "maintainer extraction" function that there may be more than one maintainer. I partially succeeded in doing that, see https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-05/msg01747.html. But that required a surprising amount of convincing, and after that I no longer felt like continuing with the second step.

What has to happen next is that `describe-package-1` has to learn that there may be more than one maintainer. Could someone else please do that?

(Ideally (and not because of this issue alone) `package` would be distributed on GNU Elpa, that way it could be improved, potentially even in backward incompatible ways, and even those users who want to stick on older Emacs releases could benefit. Again, maybe someone wants to tackle that. But that probably won't happen anytime soon, so we have to proceed with step three anyway:)

Once a new version of `package` displays all maintainers listed in `maintainerS` and older versions continue to use the one maintainer at `:maintainer``, we can adjust `package-build` to set both of those properties.

Before `package` has been improved there is not much benefit in improving this in `package-build`. Once this has been done for `package`, please open a pr in the `package-build` repository.

**Comment by tarsius** [comment]
> ```
> ;; Maintainer: Peter Mao <peter.mao@gmail.com>
> ;;      Dmitry M <dmitrym@gmail.com>
> ```
>
> 2nd line on has to be `;;<TAB>` 🤷 

You can use spaces, as long as its enough of them (don't remember the exact number).

**Comment by dmitrym0** [comment]
> Step one is to teach the low-level "maintainer extraction" function that there may be more than one maintainer. I partially succeeded in doing that, see https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-05/msg01747.html. But that required a surprising amount of convincing, and after that I no longer felt like continuing with the second step.

I read through the entire thread. You made a good case. Working with Emacs, I suppose some level of conservatism is not surprising.

What's puzzling to me (has this changed since 2021?) is that the `authors` header is there and it's pluralized by default. Why not maintainers too?

```
(:authors
	      ("Gonçalo Santos (aka." . "weirdNox@GitHub)"))
```

> What has to happen next is that `describe-package-1` has to learn that there may be more than one maintainer. Could someone else please do that?

~Where do I find this?~ Ah, it's a built in. 

> (Ideally (and not because of this issue alone) `package` would be distributed on GNU Elpa. That way it could be improved, potentially even in backward incompatible ways, and even those users who want to stick on older Emacs releases could benefit. Again, maybe someone wants to tackle that. But that probably won't happen anytime soon, so we have to proceed with step three anyway:)
> 
> Once a new version of `package` displays all maintainers listed in `:maintainerS` and older versions continue to use the one maintainer at `:maintainer`, we can adjust `package-build` to set both of these extra properties.

Adjusting package-build is [trivial](https://github.com/dmitrym0/melpa/commit/1baf4e5ffe56f66afc550a92832bd7d238ff432d) but of course useless as you say.

> Before `package` has been improved there is not much benefit in improving this in `package-build`. Once this has been done for `package`, please open a pr in the `package-build` repository.

Where is `maintainer` field used anyway? I'm not entirely sure it's worth the effort to be honest.

**Comment by petermao** [comment]
> What has to happen next is that `describe-package-1` has to learn that there may be more than one maintainer. Could someone else please do that?

After @dmitrym0 and I get org-noter officially under new maintainership, I'll take this on.  It may be a few months before I get started in earnest, though.

I'm fully on board with @tarsius's rationalle for listing multiple maintainers in the `bug-gnu-emacs` email thread.  I was surprised that `author(s)` and `maintainers` are not treated the same!

**Comment by tarsius** [comment]
I've just added support for displaying multiple maintainers to Emacs 30 (`master` branch) and have taught Melpa to include `:maintainers` (in addition to `:maintainer`) in `archive-contents`.

**Comment by petermao** [comment]
thank you, Jonas!
