### ISSUE TITLE
Ignore some checkdoc lints during recipe review?

### ISSUE THREAD

**Issue by riscy** [melpa/melpa#8450]
The checkdoc lints - required per our [PR checklist](https://github.com/melpa/melpa/blob/master/.github/PULL_REQUEST_TEMPLATE.md) - are sometimes very valuable and sometimes noisy.  For the last three years or more ,I have unilaterally decided that the following are noisy and safe to ignore:

- `checkdoc-proper-noun-list` is nil for me - don't nag to capitalize "emacs", "lisp", etc.
- `checkdoc-verb-check-experimental-flag` is nil for me - don't nag to use "active" voice
- `sentence-end-double-space` is nil for me - single or double space is a-okay

(Maybe someone disagrees with me ignoring these-- if so, this is a good place to let me know. :)

Should we expand the list of ignored issues when it comes to checkdoc?  For instance

1. All variables and subroutines might as well have a documentation string (this arises when a **private** function isn't documented)
2. Argument x should appear (as X) in the doc string (I think this one is useful because it yields syntax-highlighted help, but the checker is a bit buggy and doesn't catch everything)
3. First line should be capitalized (sometimes a non-capitalize entity is being referred to, like a variable)

If we do decide to let these (or others) pass, I'll see if we can do a good job of describing these exceptions somewhere, e.g. in CONTRIBUTING.org

**Comment by tarsius** [comment]
IMO the issues you already ignore are fine to ignore.  I probably would not have chosen to ignore the departure from the capitalization and active voice conventions. But I figure you do that because there would be a lot of "issue" to be fixed otherwise, and it just isn't worth the hassle to get the resolved.

1. Personally I find it very annoying to be told to document everything. I would recommend not doing that anymore by default. Of course commands and options should be documented, but everything else is up to the maintainer and if we you force people to document everything, you get a lot of shitty documentation.
2. It probably wouldn't be a good idea to turn the reporting off completely, but if there are a lot of other issues, you might want to filter out some of them manually.
3. If the docstring begins with a symbol, then it should by "symbol-quoted", just like everywhere else. If that isn't appropriate for some reason, then I feel it is appropriate to insist on capitalization instead.

**Comment by alphapapa** [comment]
IMHO:

> * `checkdoc-proper-noun-list` is nil for me - don't nag to capitalize "emacs", "lisp", etc.

I think that those actually improve readability and consistency.  I think they may also help authors think more carefully about how they write their docstrings so as to be clearer, which may be especially helpful for those for whom English isn't their native language.  So I'd suggest that authors be encouraged to fix those, but to not make it a requirement.

> * `checkdoc-verb-check-experimental-flag` is nil for me - don't nag to use "active" voice

The passive voice can be more appropriate and natural, and modern advice against it can be dogmatic and infantile.  And Checkdoc isn't sophisticated enough to understand when it's appropriate.  So I'd suggest that this check be omitted entirely.

> * `sentence-end-double-space` is nil for me - single or double space is a-okay

I disagree fairly strongly here, because this is Emacs we're talking about, and using single spaces between sentences defeats Emacs's powerful navigation tools (e.g. `M-a` / `M-e`).  This isn't just a matter of style; it's a technical matter which impacts practicality.  And how irritating it is when one file or docstring follows this convention, and another doesn't--or, worse, when it's not consistent within a document!  "A foolish consistency is the hobgoblin of little minds," but this isn't one of them--what is foolish, IMO, is a stubborn refusal to use two spaces so simple machines can find the boundaries between sentences and users of those machines can be more efficient.  (Ok, I'm done.  ;)

**Comment by alphapapa** [comment]
> 1. Personally I find it very annoying to be told to document everything. I would recommend not doing that anymore by default. Of course commands and options should be documented, but everything else is up to the maintainer and if we force people to document everything, we just ensure that we get a lot of shitty documentation.

Jonas, I hope you know how much I appreciate your work, so I say this respectfully: I often wish that you documented internal functions and variables more consistently, e.g. in Magit and related libraries.  A few moments spent to document a function can save many minutes of time for others trying to understand how a library works and integrate with it.

So, IMHO, this is not a piece of advice that we should omit, but I don't think it should be a requirement.

**Comment by riscy** [comment]
Thank you both!

I'll quietly re-enable `checkdoc-proper-noun-list` based on @alphapapa's feedback, to get a better sense of its false positive rate.  (I seem to remember false positives being one of my reasons for disabling it.)

Regarding `sentence-end-double-space`, I personally agree with @alphapapa for similar reasons (we don't have a dedicated "sentence mark" like `。` in English, but we *do* have the unambiguous machine-readable equivalent of two spaces after a period, i.e. `.  `.  But there are some people who are vehemently for the other side and I found the juice often wasn't worth the squeeze.

I agree with you both when you say we shouldn't turn the reporting for some of these off, but that they shouldn't be strict requirements.  I think we should rephrase the checklist re: checkdoc, and add a couple details to CONTRIBUTING.org -- I'll think this over and open a PR for these.

**Comment by riscy** [comment]
> Three or more semicolons for headings and two semicolons for comments.

I've currently got one active check for this:
```
Triple semicolons `;;;` are usually for section headings"
```
and there is also this one that I retired but may bring back as a strong suggestion:
```
Use a blank line instead of `;;` by itself under your `;;; Commentary` header")
```

> By the way, how is the automation of some of these checks coming along?

The above is as far as it goes (they're regexp based and get flagged when I run my scripts).  They're hardly a burden at all at the moment.

**Comment by tarsius** [comment]
> and there is also this one that I retired but may bring back as a strong suggestion:
> 
> ```
> Use a blank line instead of `;;` by itself under your `;;; Commentary` header")
> ```

While I usually do that, I sometimes do connect two blocks together as in:

```
;; Bla bla bla sdfsdafsdf sdfdsfdsf
;; sdfdsfds.  For example:
;;
;;     (setq foo 'bar)

;; Paragraph with unrelated information.
```

**Comment by galdor** [comment]
I'm no Emacs expert, and I do not own MELPA, but please remember this simple fact: bike shedding endlessly on which checkdoc rule to enforce for initial submissions is ultimately meaningless because these rules are not checked for any subsequent commit.

For example for my own rfc-mode, I remember having to change docstrings in way I fundamentaly disagree for the first submission. Then I ignored them all after that. And to be blunt, if these rules were enforced for every commit, I would simply not use MELPA.

To demonstrate how annoying this is, I had a few ideas about new modules these last months, and each time the first thought was "oh crap I'm going to have to make it pass the linter and checkdoc for the initial MELPA submission. Frustrating enough that I simply did a mess in my init file instead of a proper module and too bad for anyone potentially interested. Yes I'm not forced to put anything on MELPA, but this is what people expect for simple installation.

Imagine being forced to have your package pass Rubocop to be allowed to upload to RubyGem in the first time.

**Comment by galdor** [comment]
And yet users are not entitled to the free work of developers. Users who do not like the docstrings in a package are free not to install it.

Of course MELPA is also free to reject packages for any reason. But this how we end up for example with users missing the extremely useful [`screenshot`](https://github.com/tecosaur/screenshot) because it was rejected for submission even though it works perfectly.

It is sad to see on a regular basis people trying really hard to control what others do and block things which do not affect them.

A practical solution would be to allow all non-malicious packages, and add a specific badge for those which pass a list of stringent controls. It could even be a separate curated index. This way, everyone would have what they want, and you could just add the curated index to your Emacs setup.

**Comment by progfolio** [comment]
> Of course MELPA is also free to reject packages for any reason. But this how we end up for example with users missing the extremely useful [`screenshot`](https://github.com/tecosaur/screenshot) because it was rejected for submission even though it works perfectly.


https://github.com/melpa/melpa/pull/7327
Doesn't look like a rejection at all to me.
Looks like the author did not follow through due to lack of time/interest. 

> It is sad to see on a regular basis people trying really hard to control what others do and block things which do not affect them.

I am the maintainer of two Emacs package managers. I have received many bug reports which are due to third party elisp which would have been caught if the package author adhered to the standards used in the MELPA review process. Both of those package managers also make it possible for people to easily create their own ELPAs. So I can't speak for those whom are not affected when elisp is shared.

> A practical solution would be to allow all non-malicious packages, and add a specific badge for those which pass a list of stringent controls. It could even be a separate curated index. This way, everyone would have what they want, and you could just add the curated index to your Emacs setup.

IMO the standards of a curated package archive should be above and beyond "non-malicious".

**Comment by galdor** [comment]
I won't try to argue, this is pointless. You want more control on what developers do, I believe it's none of your business. Let's just agree to disagree.

Ultimately Emacs 29 will let people install packages directly from Git repositories, which will make things a easier for everyone (yes they can already do that with third party package managers, but this will make it 100x simpler).

**Comment by galdor** [comment]
> You've misunderstood me, then. I work on package managers which enable people to create their own ELPAs (for which they can enforce their own standards, if any). So I don't think MELPA should lower its standards to spare developers the hardship of documenting functions.

The elephant in the room, as I already explained, is that these standards are **not** respected. There is no check of any kind after the first submission. It would be insightful to run package-lint and checkdoc on the last version of all current packages. I suspect the vast majority of them, including the bigger ones, are not up to these standards. And nobody cares for good reasons: as long as the package installs, somehow works as intended and is not malicious, the rest is a matter of preferences (i.e. don't use it if you don't like it). Every language package manager I'm aware of operate in a similar way, because upholding subjective quality standards is restrictive, time consuming and ultimately useless. Increasing the size of the ecosystem is so much more important.

**Comment by Fuco1** [comment]
I would also add that documenting all `defmethod`s is actually SUPER noisy, because it just repeats the same `defgeneric` comment everywhere instead of actually documenting the implementation differences.  Because you have to repeat all the arguments in every method, it just get soooo noisy.

**Comment by riscy** [comment]
Thanks all for the productive discussion.  I've settled on relaxing the language around the checkdoc requirements, which gives reviewers more leeway ("within reason").  I'll close this one up.
