### ISSUE TITLE
Missing magit-section.el file in magit-20230402.1342

### ISSUE THREAD

**Issue by dacap** [melpa/melpa#8476]
Installing the latest magit from melpa brings the following error when we do magit-status:

    byte-code: Symbol’s function definition is void: magit-menu-item

It looks like the package (https://melpa.org/packages/magit-20230402.1342.tar) doesn't contain the [magit-section.el](https://github.com/magit/magit/blob/main/lisp/magit-section.el) file (and magit-section-pkg.el).

**Comment by tarsius** [comment]
Yes, while `magit-section` is maintained in the same repository as `magit`, it is distributed as a separate package (because it is potentially useful for third-party packages that have nothing to do with Git).

Package should automatically install `magit-section`, when you update `magit`. Apparently that hasn't happened, so you have to install it manually. But before you do that, you may wish to restart Emacs to see whether that fixes it.
