### ISSUE TITLE
oauth repository has been archived

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8510]
@psanford you recently archived https://github.com/psanford/emacs-oauth. Would you be willing to transfer it to the [Emacsorphange](https://github.com/emacsorphanage) instead? Packages exist that depend on this library, some of them [on melpa](https://melpa.org/#/oauth), so it would be better if there were a way to make changes, should the need arise.

Better yet, maybe one of the maintainers of a package that depends on it, could maintain `oauth` too? /cc @pavpanchekha @gcr @fvdbeek

**Comment by psanford** [comment]
The library is licensed GPL v3. You are free to fork it if you feel it is necessary. However...

I archived the repo because I would not recommend anyone build on top of this library today. It targets oauth 1 which is mostly not used anymore. It does some weird things for how it makes requests that a library written today would not do. It likely has a some security issues. And no one has seriously looked at this code in over 10 years.

**Comment by tarsius** [comment]
> You are free to fork it if you feel it is necessary.

Transferring the repository would be better because that would preserve all old issues in the "new upstream" repository.

If you don't want to do that, that's fine too.

> [shouldn't be used anymore]

I figured as much, but that doesn't change the fact that some packages still use it. Granted, some of them haven't been touched in a long time either, and should probably should be removed from Melpa. Let's wait for some feedback from the maintainers of dependent packages.

**Comment by pavpanchekha** [comment]
I maintain the [dropbox.el](https://github.com/pavpanchekha/dropbox.el) which depends on this feature. It does appear to have users, because I get bug reports, but I haven't done significant work on this package for a decade. Frankly it is a surprise Dropbox still maintains the APIs.

Ultimately, if the other users of oauth aren't active, I'm happy to call my package deprecated, delist it from MELPA, and give @psanford a nice sense of closure while relieving the need to find a maintainer.

**Comment by fvdbeek** [comment]
I maintain [emacs-zotero](https://gitlab.com/fvdbeek/emacs-zotero) that depends on emacs-oauth. [Zotero only supports OAuth 1.0a for authenticating](https://www.zotero.org/support/dev/web_api/v3/oauth), and I suspect there are more APIs that don't support OAuth 2.0. Therefore emacs-oauth is still useful. If no one else will volunteer, I am willing to maintain it.

**Comment by fvdbeek** [comment]
Aha, I never realized that a repository could be transferred. That would be better than forking, so I deleted my fork.

**Comment by fvdbeek** [comment]
The repository will not be transferred, see #8512. So I forked it again, but imported it to GitLab this time.

**Comment by gksudolol** [comment]
Just a bystanders point of view, I don't think a fork and moving the package off GitHub is very fitting.. emacsorphanage seems the more sensible approach

**Comment by fvdbeek** [comment]
Emacsorphanage would be the best option if the package is not maintained, but less so if I become the new maintainer.

**Comment by fvdbeek** [comment]
This issue is solved by #8512.

**Comment by tarsius** [comment]
Thanks!

(I agree that moving to your account is better in this case than moving to the orphanage. I don't want to endlessly accumulate packages there.)
