### ISSUE TITLE
Multi-file single package

### ISSUE THREAD

**Issue by eyeinsky** [melpa/melpa#8728]
Hi! I'm confused as to how would I make a multi-file (multi-module) single package in Melpa? Or, what is the way to do it in elisp in generally? :)

I've asked about it on [Emacs' StackExchange](https://emacs.stackexchange.com/questions/75398/how-to-have-a-multi-file-emacs-package) and just recently on [reddit](https://www.reddit.com/r/emacs/comments/16f2hr0/modules_in_emacs_packages/) and found [Emacs documentation for multi-file packages](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html).

What's still unclear is that 
- how does a "multi-module single-package" look in elisp (require/provide, or load-file)?
- how would one organize a receipt and a git repo such that the result is *one package* but distributed to multiple modules (files)?

I guess my confusion is in that whether a package that does one thing is a feature in elisp speak, or is a file (module) a feature? In English, I'd say the package is a feature (adds some single functionality to Emacs), but maybe in elisp it has the meaning of a file (module)?

**Comment by tarsius** [comment]
I recommend you update your question on reddit with the same level of detail as you have provided here. The question as you asked it on reddit is a bad one, because you provide way too few details. The question you asked here is much better -- more experienced users will know what you are confused about -- but its not the best place to ask it.
