### ISSUE TITLE
spray's URL out of date in archive.json

### ISSUE THREAD

**Issue by progfolio** [melpa/melpa#8888]
Spray's url still points to  "https://github.com/ian-kelling/spray", but the upstream repo has been moved to sourcehut.

**Comment by tarsius** [comment]
That's why, since a3645b08cb46e3d91081da7baa982b5283918447 (2022), we get it from sourcehut.

The reason Melpa and `package` still link to the now 404 github repository, is that the package header still contains `;; URL: https://github.com/ian-kelling/spray`. It's the package maintainer's responsibility to fix that. Unfortunately they often forget that.

Ping @ian-kelling.
