### ISSUE TITLE
How is melpa built?

### ISSUE THREAD

**Issue by ayys** [melpa/melpa#8896]
I am trying to figure out how Melpa is built and deployed. Apologies if this is already documented somewhere. These are the questions I have.

### How are the packages being built?
  - is it a private server somewhere?
  - Are there specific Emacs versions or configurations used during the package build process to ensure compatibility?
  - How do package metrics get collected? (total downloads, number of packages, list of package dependencies)
### How is it being deployed?
  - Is there a deployment script?
  - Are the packages on object-storage somewhere?
  - How are build failures handled in the CI/CD pipeline

**Comment by ayys** [comment]
@milkypostman thanks for the response. I am researching alternative deployment strategies for Melpa. One of the ways is by moving the build+deployment process to github actions. The cronjobs can be moved to github as well with [schedule-triggered actions ](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule). 

Depending on what we are using to store the packages, we can maybe move that to something that runs https://github.com/halverneus/static-file-server. I am still thinking this through, but the goal is to make ready a proposal for a more transparent way to build and deploy Melpa.
I am very willing to put in my time to work on making Melpa deployments more transparent.

**Comment by purcell** [comment]
The code for all of this, including metrics and periodic rebuilds etc., is right here in the repo: there's a docker-compose config and all the necessary scripts.

So I don't know that any transparency is lacking here.

The config in this repo is a little short of being able to spin up everything conveniently on a different blank machine, and I do think that would be a good goal.

I don't think we'd be terribly interested in changing from our well-tested and reliable setup to alternatives without compelling reasons, because it involves work for us too, but feel free to share ideas or thoughts.

**Comment by tarsius** [comment]
For testing things locally you might find the "[TMP] ..." commits on https://github.com/melpa/melpa/compare/master...snapshot-channel useful.
