### ISSUE TITLE
[Feature Request] Website: sort package list by recent downloads

### ISSUE THREAD

**Issue by psionic-k** [melpa/melpa#9047]
When sorting by downloads, I can't tell how recent they are: https://melpa.org/#/?sort=downloads&asc=false

Example on crates.io: https://crates.io/search?q=jwt&sort=recent-downloads

If it is already a recent rather than all-time count, I apologize and will recommend adding this information to the site.

For package developers and users alike, we are extremely starved of this kind of ecosystem awareness.

Now I will just pray that the implementation was log-based and not by incrementing a counter unless there is an old database backup that can be used to calculate a starting delta.

**Comment by alphapapa** [comment]
I guess you're wanting a moving window of downloads?  What qualifies as a "recent download"?

> For package developers and users alike, we are extremely starved of this kind of ecosystem awareness.

Are we?  I guess it could be interesting, but is it important?

Besides, this doesn't even touch on the issue of discerning "real" downloads from "inflated" ones, e.g. ones made by automated scripts, CI, a rogue author who wanted to inflate his numbers, etc.

**Comment by psionic-k** [comment]
> Moving window

Yes.  Recent... 3 months for "hot" and one year for "solid".

> doesn't even touch on the issue of discerning "real" downloads from "inflated"

Arguably, using numbers with no rolling window is more dangerous already because any past distortions are retained forever.  In the end, maintaining such a distortion can't be expected to have much impact beyond writing a better package because you can't just pad the download numbers on a garbage can and expect people to install it.

> is it important?

As starved for signal as we are, both as package maintainers and users browsing packages, it would be a ray of brilliant illumination in a world shrouded behind an event horizon.  We have N users evaluating M packages, and such a simple feedback mechanism can greatly lower the cost of M.

**Comment by alphapapa** [comment]
It's not that I'm against the idea, but I'm not sure if it would be worth the trouble to implement.  In my own experience, some of my packages get cloned thousands of times a week, presumably by CI for distros they are included in.  I'd guess that that can happen by pulling directly from MELPA sometimes, too, and if so, all download numbers are "contaminated."

As well, there are, IMHO, some simply inferior packages that are far more popular than their superior alternatives, probably because the inferior one came first, and it has a higher download count.  I see users on Reddit every week asking about various packages that have far better alternatives, but they end up finding the inferior one first, and they don't look beyond it.  And I wonder how a download counter like this would affect that problem.

I tend to think that package repos aren't really great for discovery, in the first place; and all the more for large ones like MELPA.  If we want to solve the problem of discovering the best package for a purpose, I think this wouldn't do that.

**Comment by psionic-k** [comment]
>  If we want to solve the problem of discovering the best package for a purpose, I think this wouldn't do that.

Yeah, that's a problem for tools superior to Reddit.  I am building the tool after I finish delivering a better fund-raising model.

If this issue was fast to implement, we probably wouldn't be talking about it.  Closing.
