### ISSUE TITLE
git-commit recipe still references non-existant git-commit-pkg.el file

### ISSUE THREAD

**Issue by jtamagnan** [melpa/melpa#9142]
# Problem

The Elpaca package manager fails to install git-commit from melpa

# Diagnosis

https://github.com/melpa/melpa/blob/master/recipes/git-commit#L5 still references `git-commit-pkg.el` even though it was removed in https://github.com/magit/magit/commit/bc5149c8de010e9d469e0b324a207b0e86297792

# Solution

It seems like we can remove this line from the recipe. If this seems suitable I can take it on

**Comment by tarsius** [comment]
This file is now being generated using github actions, but I forgot to check in the generated files. Code fixed in https://github.com/emacscollective/workflows/commit/545516bb7952aa136e6478574fe4151fff58228f. Once I've pushed another commit to the magit repository this will be fixed for melpa and downstreams. That should happen today or tomorrow.

**Comment by progfolio** [comment]
> This file is now being generated using github actions

If the files are generated, why not include the package's actual version instead of the placeholder "0"?

**Comment by tarsius** [comment]
I though nothing was using the value from this file. Will look into it later, gotta run now.

**Comment by tarsius** [comment]
I've pushed a fix. It can take up to three hours until that hits Melpa.

**Comment by jtamagnan** [comment]
@tarsius thanks for the super quick fix. I've tested and everything seems to be working as far as I can tell
