### ISSUE TITLE
tangotango-theme is not updating

### ISSUE THREAD

**Issue by fapdash** [melpa/melpa#9245]
As far as I understand melpa should automatically release a new version when new commits are added to the default branch.
Somehow this isn't happening for the tangotango-theme,

Is there anything we have to do or can someone else fix this?

Also see https://github.com/juba/color-theme-tangotango/issues/20

**Comment by fapdash** [comment]
Is it possible that the package didn't update because the file that is referenced in the recipe didn't get changed?

https://github.com/melpa/melpa/blob/6c1d8ed99c3769f6a789fb51dc37794b95f8bb37/recipes/tangotango-theme#L3

**Comment by tarsius** [comment]
> Is it possible that the package didn't update because the file that is referenced in the recipe didn't get changed?

Yes, a new package version is only made available if a file that is included in the package on Melpa changes. Otherwise we could end up creating many package versions that are identical except for the version number.

@fapdash changed the wrong file (unless they are still using Emacs 21, but that is unlikely, Emacs 22.1 has been releases 17 years ago). See the commentary in https://github.com/emacsattic/color-theme.

I recommend you remove `color-theme-tangotango.el`. (Also, I think the time has come for me to remove `color-theme` from Melpa. :grin:)

**Comment by tarsius** [comment]
> I recommend you remove `color-theme-tangotango.el`. (Also, I think the time has come for me to remove `color-theme` from Melpa. 😁)

I see you instead (#9246) started to include the alternative implementation, which depends on the very obsolete `color-theme`. I mentioned that I would likely remove `color-theme` from Melpa. Once I have done that, users will get a compile error when the install your package, because it will contain a library whose dependencies cannot be satisfied. I still think it would be better to remove the legacy `color-theme-tangotango.el`.

**Comment by fapdash** [comment]
> @fapdash changed the wrong file (unless they are still using Emacs 21, but that is unlikely, Emacs 22.1 has been releases 17 years ago). See the commentary in https://github.com/emacsattic/color-theme.

@tarsius Ah, of course, that explains our confusion. I'll open a PR on the `tangotango-theme` to remove the legacy `color-theme-tangotango.el`.
